# FBX -> .ma bake script (foreign-scene reference path). Generated by BlenderSceneImport -- do not edit by hand.

"""Import an FBX headlessly (mayapy) and save it as a ``.ma`` so a foreign scene can be REFERENCED.

Maya references FBX natively, so this hop is not a capability gap the way the Blender side's
is -- it is deliberate **symmetry**: both panels reference a cached *native* scene, so the
referenced-file surface (edits, namespaces, reload, relocate, display overrides) behaves
identically no matter which DCC the row came from. The mirror of blendertk's
``templates/_bake_scene.py`` (FBX -> cached ``.blend`` for ``link_blend_file``).

Runs under ``mayapy`` via ``pythontk.run_script_to_artifact``, which judges success by the
saved ``.ma``'s existence -- NOT the exit code (standalone teardown is a known crasher,
hence the ``os._exit`` below, which skips it entirely).

Materials: FBX carries only the classic model, so the conversion's ``.manifest.json``
sidecar is replayed through the SAME engine the direct-import path uses
(:meth:`BlenderSceneImport._apply_texture_manifest`) rather than a second copy of that
logic. ``EXTRA_SYS_PATH`` carries the parent Maya's ``sys.path`` into this child (same Maya
version, same interpreter -- the entries are valid), so mayatk is normally importable. When
it is not, the bake still succeeds and keeps the FBX-carried materials (logged).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python at module scope: no mayatk/blendertk imports (the target
# machine's mayapy only has Maya's own modules). mayatk is imported *optionally*, inside
# the manifest step, and its absence is never fatal.
import os
import sys
import traceback

SRC_FBX = r"__SRC_FBX__"
OUT_MA = r"__OUT_MA__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__


def _extend_sys_path():
    """Make the parent's importable set visible here (mayatk for the manifest replay)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def _engine():
    """The mayatk import engine, or None when mayatk is not importable in this child.

    Reusing it keeps the bake's FBX import + material rebuild byte-identical to the
    direct-import path instead of maintaining a second copy of that logic here.
    """
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        return BlenderSceneImport()
    except Exception:
        print("mayatk unavailable in this child; using the plain FBX import path:")
        traceback.print_exc()
        return None


def import_fbx(cmds, engine):
    """Import *SRC_FBX* into the empty standalone scene; return ALL new nodes.

    All nodes, not just transforms: the manifest rebuild needs the shading engines.
    """
    if engine is not None:
        return engine._import_fbx(SRC_FBX)
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    return (
        cmds.file(
            SRC_FBX, i=True, type="FBX", ignoreVersion=True, returnNewNodes=True
        )
        or []
    )


def apply_manifest(engine, new_nodes):
    """Replay the conversion's texture sidecar through the shared rebuild engine.

    Best-effort by contract: a bake whose materials stay classic-model is a fidelity
    loss, not a failure, and must never cost the user the referenceable .ma.
    """
    manifest = SRC_FBX + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._apply_texture_manifest(manifest, new_nodes)
    except Exception:
        print("Texture-manifest replay failed; keeping FBX materials:")
        traceback.print_exc()


def main():
    import maya.standalone

    maya.standalone.initialize(name="python")
    import maya.cmds as cmds

    _extend_sys_path()
    cmds.file(new=True, force=True)
    engine = _engine()
    imported = import_fbx(cmds, engine)
    apply_manifest(engine, imported)
    # mayaAscii: a referenced .ma is diffable/greppable and survives a version bump that
    # would make a .mb unreadable -- the right trade for a disposable cache artifact.
    cmds.file(rename=OUT_MA)
    cmds.file(save=True, type="mayaAscii", force=True)
    print("Baked {} node(s) into {}".format(len(imported), OUT_MA))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
sys.stdout.flush()
os._exit(0)
