# Intermediate -> .ma bake script (foreign-scene reference path). Generated by BlenderSceneImport -- do not edit by hand.

"""Import a converted intermediate (USD or FBX) headlessly (mayapy) and save it as a ``.ma``
so a foreign scene can be REFERENCED.

Maya references FBX natively, so this hop is not a capability gap the way the Blender side's
is -- it is deliberate **symmetry**: both panels reference a cached *native* scene, so the
referenced-file surface (edits, namespaces, reload, relocate, display overrides) behaves
identically no matter which DCC the row came from. The mirror of blendertk's
``templates/_bake_scene.py`` (intermediate -> cached ``.blend`` for ``link_blend_file``).

The source branches on extension. A ``.usd*`` intermediate imports natively through the
mayaUsd translator -- visibility and UV sets arrive natively -- then ``apply_instances``
rebuilds real Maya instances from the conversion sidecar (the USD is written flat because
Blender's ``use_instancing`` yields read-only prototypes, not the shared-shape model a Maya
artist edits; see the export template). An ``.fbx`` intermediate (a raw ``.fbx`` source, or
the ``via="fbx"`` route) takes the classic path: FBX import + texture-manifest replay.

Both routes therefore carry a ``.manifest.json`` -- they just carry different things in it
(FBX: textures; USD: instance grouping) -- and ``BlenderSceneImport.import_payload``, the
SAME consumer the direct import runs, replays it (empties, instances, materials, the scene
clock, shots, the rig).

Runs under ``mayapy`` via ``pythontk.run_script_to_artifact``, which judges success by the
saved ``.ma``'s existence -- NOT the exit code (standalone teardown is a known crasher,
hence the hard exit below, ``_exit``, which skips it).

Materials (FBX branch only): FBX carries only the classic model, so the conversion's
``.manifest.json`` sidecar is replayed through the SAME engine the direct-import path uses
(:meth:`BlenderSceneImport._apply_texture_manifest`) rather than a second copy of that
logic. ``EXTRA_SYS_PATH`` carries the parent Maya's ``sys.path`` into this child (same Maya
version, same interpreter -- the entries are valid), so mayatk is normally importable. When
it is not, the bake still succeeds and keeps the FBX-carried materials (logged).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python at module scope: no mayatk/blendertk imports (the target
# machine's mayapy only has Maya's own modules). mayatk is imported *optionally*, inside
# the manifest step, and its absence is never fatal.
import os
import sys
import traceback

SRC_FILE = r"__SRC_FILE__"
OUT_MA = r"__OUT_MA__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__

USD_EXTENSIONS = (".usd", ".usda", ".usdc", ".usdz")


# The *USD Import* translator options every hand-off importer uses -- mirror of
# mayatk ``UsdUtils.INTERCHANGE_IMPORT_OPTIONS`` (pinned equal): time samples as
# keys (the translator's default is OFF -- every animated prim arrived static,
# measured) and Blender's ``st`` (its exporter's name for the render-active UV
# map) landing as Maya's ``map1``, the FBX route's spelling.
USD_IMPORT_OPTIONS = "readAnimData=1;remapUVSetsTo=[[st,map1]]"


def _extend_sys_path():
    """Make the parent's importable set visible here (mayatk for the manifest replay)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def _engine():
    """The mayatk import engine, or None when mayatk is not importable in this child.

    Reusing it keeps the bake's FBX import + material rebuild byte-identical to the
    direct-import path instead of maintaining a second copy of that logic here.
    """
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        return BlenderSceneImport()
    except Exception:
        print("mayatk unavailable in this child; using the plain FBX import path:")
        traceback.print_exc()
        return None


def import_source(cmds):
    """Import *SRC_FILE* into the empty standalone scene without mayatk; return ALL
    new nodes (the fallback when the engine is not importable in this child).
    Dispatched on extension: ``.usd*`` -> the native mayaUsd translator; ``.fbx``
    -> the plain FBX import.
    """
    if SRC_FILE.lower().endswith(USD_EXTENSIONS):
        if not cmds.pluginInfo("mayaUsdPlugin", query=True, loaded=True):
            cmds.loadPlugin("mayaUsdPlugin")
        return (
            cmds.file(
                SRC_FILE.replace("\\", "/"),
                i=True,
                type="USD Import",
                ignoreVersion=True,
                returnNewNodes=True,
                options=USD_IMPORT_OPTIONS,
            )
            or []
        )
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    return (
        cmds.file(SRC_FILE, i=True, type="FBX", ignoreVersion=True, returnNewNodes=True)
        or []
    )


def restore_usd_locators(cmds, new_nodes):
    """Give point-marker Empties their locator shapes back (USD source): every
    Empty arrives SHAPELESS off a USD layer. The children heuristic of a child
    without mayatk (the engine's manifest-aware repair runs in ``import_payload``).
    Dependency-free copy of ``BlenderSceneImport._restore_usd_locators``; its
    fallback loop is held token-identical across the three templates that carry
    it by ``test_scene_import.py::
    test_locator_fallback_loops_are_one_copy_across_the_three_templates``."""
    # exactType: a joint IS a transform, and a shapeless leaf joint is a
    # skeleton tip, not a point marker.
    for transform in cmds.ls(new_nodes, exactType="transform", long=True) or []:
        if cmds.listRelatives(transform, shapes=True, fullPath=True):
            continue
        if cmds.listRelatives(
            transform, children=True, type="transform", fullPath=True
        ):
            continue
        short = transform.rsplit("|", 1)[-1].rsplit(":", 1)[-1]
        cmds.createNode("locator", name=short + "Shape", parent=transform)


def apply_instances():
    """Refuse a USD sidecar the child cannot replay (no mayatk): GUARANTEED-OR-FAIL.

    Without the rebuild, a foreign scene REFERENCED through the bake would carry N
    independent shapes -- a scene that renders correctly and only betrays itself
    when an artist edits one "instance" and its siblings don't follow. So a present
    sidecar raises: main() exits 1 with NO artifact written, and the parent's
    judged-by-artifact contract reports a failed bake instead of caching a
    flattened .ma. (With mayatk, ``import_payload`` replays it.)

    A MISSING sidecar is a hand-fed USD with nothing to replay -- allowed; the
    bridge's own conversions always ship one (v2 contract, enforced upstream
    by bake_scene).
    """
    if not os.path.isfile(SRC_FILE + ".manifest.json"):
        return
    raise RuntimeError(
        "mayatk is unavailable in this child (see the traceback above), so "
        "the USD sidecar's instances cannot be rebuilt; refusing to bake a "
        "flattened scene."
    )


def _progress(done, total, text):
    """A ``pythontk.ProgressRelay`` marker line, flushed so the parent's footer sees it
    while the bake runs. Spelled out: the marker protocol needs no import."""
    print("::progress:: {}/{} {}".format(done, total, text), flush=True)


def main():
    import maya.standalone

    _progress(0, 4, "Starting Maya")
    maya.standalone.initialize(name="python")
    import maya.cmds as cmds

    _extend_sys_path()
    cmds.file(new=True, force=True)
    engine = _engine()
    _progress(1, 4, "Importing the intermediate")
    usd = SRC_FILE.lower().endswith(USD_EXTENSIONS)
    if engine is not None:
        # The ONE payload consumer -- the import plus every manifest section
        # (empties, instances, materials, the scene clock, shots, the rig) --
        # shared with the direct-import path, so a bake and an import never
        # disagree about the same scene.
        imported = engine.import_payload(
            SRC_FILE,
            via="usd" if usd else "fbx",
            adopt_scene=True,
            step=lambda done, total, text: _progress(1 + 2 * done // total, 4, text),
        )
    else:
        imported = import_source(cmds)
        _progress(2, 4, "Rebuilding the scene")
        if usd:
            apply_instances()
            restore_usd_locators(cmds, imported)
    # mayaAscii: a referenced .ma is diffable/greppable and survives a version bump that
    # would make a .mb unreadable -- the right trade for a disposable cache artifact.
    _progress(3, 4, "Saving the .ma")
    cmds.file(rename=OUT_MA)
    cmds.file(save=True, type="mayaAscii", force=True)
    print("Baked {} node(s) into {}".format(len(imported), OUT_MA))
    _progress(4, 4, "Baked")


def _exit(code):
    """Leave without teardown. ``os._exit`` is not enough on Windows: it still runs every
    DLL's detach, where Maya's static destructors fault and its crash handler saves the
    open scene into the temp dir (a ``[Recovered]`` copy per bake). ``pythontk.ProcessExit``
    skips detach; without pythontk on the path this degrades to ``os._exit``."""
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        from pythontk.core_utils.process_exit import ProcessExit
    except Exception:  # noqa: BLE001 -- the exit must never raise
        os._exit(code)
    ProcessExit.hard_exit(code)


try:
    main()
except Exception:
    traceback.print_exc()
    _exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
_exit(0)
