# Intermediate -> .ma bake script (foreign-scene reference path). Generated by BlenderSceneImport -- do not edit by hand.

"""Import a converted intermediate (USD or FBX) headlessly (mayapy) and save it as a ``.ma``
so a foreign scene can be REFERENCED.

Maya references FBX natively, so this hop is not a capability gap the way the Blender side's
is -- it is deliberate **symmetry**: both panels reference a cached *native* scene, so the
referenced-file surface (edits, namespaces, reload, relocate, display overrides) behaves
identically no matter which DCC the row came from. The mirror of blendertk's
``templates/_bake_scene.py`` (intermediate -> cached ``.blend`` for ``link_blend_file``).

The source branches on extension. A ``.usd*`` intermediate imports natively through the
mayaUsd translator -- materials and visibility need no sidecar -- then ``apply_instances``
rebuilds real Maya instances from the conversion sidecar (the USD is written flat because
Blender's ``use_instancing`` yields read-only prototypes, not the shared-shape model a Maya
artist edits; see the export template). An ``.fbx`` intermediate (a raw ``.fbx`` source, or
the ``via="fbx"`` route) takes the classic path: FBX import + texture-manifest replay.

Both routes therefore carry a ``.manifest.json`` -- they just carry different things in it
(FBX: textures; USD: instance grouping) and replay it through different engine methods.

Runs under ``mayapy`` via ``pythontk.run_script_to_artifact``, which judges success by the
saved ``.ma``'s existence -- NOT the exit code (standalone teardown is a known crasher,
hence the ``os._exit`` below, which skips it entirely).

Materials (FBX branch only): FBX carries only the classic model, so the conversion's
``.manifest.json`` sidecar is replayed through the SAME engine the direct-import path uses
(:meth:`BlenderSceneImport._apply_texture_manifest`) rather than a second copy of that
logic. ``EXTRA_SYS_PATH`` carries the parent Maya's ``sys.path`` into this child (same Maya
version, same interpreter -- the entries are valid), so mayatk is normally importable. When
it is not, the bake still succeeds and keeps the FBX-carried materials (logged).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Maya Python at module scope: no mayatk/blendertk imports (the target
# machine's mayapy only has Maya's own modules). mayatk is imported *optionally*, inside
# the manifest step, and its absence is never fatal.
import os
import sys
import traceback

SRC_FILE = r"__SRC_FILE__"
OUT_MA = r"__OUT_MA__"
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__

USD_EXTENSIONS = (".usd", ".usda", ".usdc", ".usdz")


def _extend_sys_path():
    """Make the parent's importable set visible here (mayatk for the manifest replay)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def _engine():
    """The mayatk import engine, or None when mayatk is not importable in this child.

    Reusing it keeps the bake's FBX import + material rebuild byte-identical to the
    direct-import path instead of maintaining a second copy of that logic here.
    """
    try:
        from mayatk.env_utils.blender_bridge._scene_import import BlenderSceneImport

        return BlenderSceneImport()
    except Exception:
        print("mayatk unavailable in this child; using the plain FBX import path:")
        traceback.print_exc()
        return None


def import_source(cmds, engine):
    """Import *SRC_FILE* into the empty standalone scene; return ALL new nodes.

    All nodes, not just transforms: the manifest rebuild needs the shading engines.
    Dispatched on extension: ``.usd*`` -> the native mayaUsd translator (no engine
    needed -- materials arrive natively); ``.fbx`` -> the classic FBX path.
    """
    if SRC_FILE.lower().endswith(USD_EXTENSIONS):
        if not cmds.pluginInfo("mayaUsdPlugin", query=True, loaded=True):
            cmds.loadPlugin("mayaUsdPlugin")
        return (
            cmds.file(
                SRC_FILE.replace("\\", "/"),
                i=True,
                type="USD Import",
                ignoreVersion=True,
                returnNewNodes=True,
            )
            or []
        )
    if engine is not None:
        return engine._import_fbx(SRC_FILE)
    if not cmds.pluginInfo("fbxmaya", query=True, loaded=True):
        cmds.loadPlugin("fbxmaya")
    return (
        cmds.file(
            SRC_FILE, i=True, type="FBX", ignoreVersion=True, returnNewNodes=True
        )
        or []
    )


def apply_manifest(engine, new_nodes):
    """Replay the conversion's texture sidecar through the shared rebuild engine.

    Best-effort by contract: a bake whose materials stay classic-model is a fidelity
    loss, not a failure, and must never cost the user the referenceable .ma.
    Never reached by a USD source -- ``main`` routes that to ``apply_instances``.
    """
    manifest = SRC_FILE + ".manifest.json"
    if engine is None or not os.path.isfile(manifest):
        return
    try:
        engine._apply_texture_manifest(manifest, new_nodes)
    except Exception:
        print("Texture-manifest replay failed; keeping FBX materials:")
        traceback.print_exc()


def restore_empty_groups(engine, new_nodes):
    """Empties -> correct Maya node types (FBX branch; see the engine method).

    Maya's FBX importer gives every null a locator shape, so a referenced
    .blend's group hierarchy would arrive as locators. Engine path only: the
    bake is rendered by ``BlenderSceneImport`` itself, so mayatk is on
    ``EXTRA_SYS_PATH`` whenever the bake can run at all; without it the nulls
    stay locators (a display nuisance, never a structural loss).
    """
    if engine is None:
        return
    try:
        engine._restore_empty_groups(new_nodes, SRC_FILE + ".manifest.json")
    except Exception:
        print("Empty-group repair failed; imported nulls stay locators:")
        traceback.print_exc()


def apply_instances(engine, new_nodes):
    """Rebuild real Maya instances from Blender's linked-duplicate groups.

    USD-source branch only, through the SAME engine method the direct-import
    path uses. GUARANTEED-OR-FAIL: without the rebuild, a foreign scene
    REFERENCED through the bake would carry N independent shapes -- a scene
    that renders correctly and only betrays itself when an artist edits one
    "instance" and its siblings don't follow. So a present sidecar that cannot
    be replayed (engine unavailable, bad data) raises: main() exits 1 with NO
    artifact written, and the parent's judged-by-artifact contract reports a
    failed bake instead of caching a flattened .ma.

    A MISSING sidecar is a hand-fed USD with nothing to replay -- allowed; the
    bridge's own conversions always ship one (v2 contract, enforced upstream
    by bake_scene).
    """
    manifest = SRC_FILE + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    if engine is None:
        raise RuntimeError(
            "mayatk is unavailable in this child (see the traceback above), so "
            "the USD sidecar's instances cannot be rebuilt; refusing to bake a "
            "flattened scene."
        )
    engine._apply_instance_manifest(manifest, new_nodes)


def main():
    import maya.standalone

    maya.standalone.initialize(name="python")
    import maya.cmds as cmds

    _extend_sys_path()
    cmds.file(new=True, force=True)
    engine = _engine()
    imported = import_source(cmds, engine)
    if SRC_FILE.lower().endswith(USD_EXTENSIONS):
        apply_instances(engine, imported)
    else:
        restore_empty_groups(engine, imported)
        apply_manifest(engine, imported)
    # mayaAscii: a referenced .ma is diffable/greppable and survives a version bump that
    # would make a .mb unreadable -- the right trade for a disposable cache artifact.
    cmds.file(rename=OUT_MA)
    cmds.file(save=True, type="mayaAscii", force=True)
    print("Baked {} node(s) into {}".format(len(imported), OUT_MA))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; skip standalone teardown (known access violations).
sys.stdout.flush()
os._exit(0)
