# Blender-scene -> USD conversion script (Blender -> Maya pull). Generated by BlenderSceneImport -- do not edit by hand.

"""Open a .blend headlessly (blender --background) and export it as USD for a Maya import.

The USD sibling of ``templates/_import_scene.py`` (the FBX route), selected via
``import_scene(via="usd")`` -- the mirror of blendertk's
``templates/_import_scene_usd.py``. Runs under ``blender --background
--factory-startup`` via ``pythontk.run_script_to_artifact``, which judges success
by the exported USD's existence, NOT the exit code (the ``os._exit`` below makes
the code honest).

Where the FBX route carries only the classic material model and sidecars the PBR
textures in a ``.manifest.json`` for a Maya-side ``GameShader`` rebuild, USD needs
neither: Blender's exporter converts the Principled BSDF to ``UsdPreviewSurface``
(metallic / roughness / normal / emissive textures included), which Maya's USD
importer wires into native shading. Known limit (same as the FBX route): images
packed into the .blend with no on-disk file are not exported
(``export_textures`` stays off so the artifact references the ORIGINAL files --
texture edits flow through on cache hits, and there is no textures/ folder to
lose in the cache promotion).

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python: no mayatk/blendertk/pythontk imports (only
# Blender's own bundled modules are guaranteed in the child process).
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_USD = r"__OUT_USD__"
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def export_usd(bpy):
    """Whole-scene USD export with per-kwarg tolerance across Blender versions.

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in another exporter version is dropped and the
    call retried -- the same tolerance loop as the FBX template.
    ``relative_paths=False`` is the load-bearing one: the USD lives in the temp
    dir, so relative texture refs would be unresolvable in Maya (the FBX
    route's ``path_mode='ABSOLUTE'`` mirror).
    """
    kwargs = {
        "filepath": OUT_USD,
        "selected_objects_only": False,
        "visible_objects_only": False,  # pre-5.x only; dropped elsewhere
        "export_materials": True,
        "generate_preview_surface": True,
        # Reference the ORIGINAL texture files, never copy: the USD lives in
        # scratch, so a copied textures/ dir would be cleaned away right after
        # the import (dangling file nodes — observed live on 5.1, whose
        # default is NEW/copy) and would freeze texture edits out of cache
        # hits. Two spellings of the same intent — the tolerance loop drops
        # whichever one this Blender doesn't know.
        "export_textures_mode": "KEEP",  # 4.2+ / 5.x name
        "export_textures": False,  # pre-4.2 name
        "relative_paths": False,
        "use_instancing": True,
        "export_animation": INCLUDE_ANIMATION,
        # One prim per object (Blender otherwise writes an Xform + child Mesh
        # pair) and no /root wrapper — flat parity with the FBX route's
        # import structure on the Maya side.
        "merge_parent_xform": True,
        "root_prim_path": "",
    }
    while True:
        try:
            bpy.ops.wm.usd_export(**kwargs)
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs and key != "filepath":
                print("USD kwarg skipped (unsupported by this exporter): " + key)
                del kwargs[key]
                continue
            raise


def main():
    import bpy

    bpy.ops.wm.open_mainfile(filepath=SRC_PATH, load_ui=False)
    export_usd(bpy)


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
