# Blender-scene -> USD conversion script (Blender -> Maya pull). Generated by BlenderSceneImport -- do not edit by hand.

"""Open a .blend headlessly (blender --background) and export it as USD for a Maya import.

The USD sibling of ``templates/_import_scene.py`` (the FBX route), selected via
``import_scene(via="usd")`` -- the mirror of blendertk's
``templates/_import_scene_usd.py``. Runs under ``blender --background
--factory-startup`` via ``pythontk.run_script_to_artifact``, which judges success
by the exported USD's existence, NOT the exit code (the ``os._exit`` below makes
the code honest).

Where the FBX route carries only the classic material model and sidecars the PBR
textures in a ``.manifest.json`` for a Maya-side ``GameShader`` rebuild, USD needs
neither: Blender's exporter converts the Principled BSDF to ``UsdPreviewSurface``
(metallic / roughness / normal / emissive textures included), which Maya's USD
importer wires into native shading. Known limit (same as the FBX route): images
packed into the .blend with no on-disk file are not exported
(``export_textures`` stays off so the artifact references the ORIGINAL files --
texture edits flow through on cache hits, and there is no textures/ folder to
lose in the cache promotion).

A glTF source (.glb/.gltf) is opened by IMPORT into an emptied factory scene instead
(``open_source``). Its images are packed by definition, so they are written out to
TEX_DIR -- a persistent, SOURCE-keyed dir the Maya side owns, not the conversion
scratch -- before the export. KEEP then references those files, which is exactly why
the unpack cannot write beside the USD: that folder is what the cache promotion loses.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python at module scope: no mayatk/blendertk/pythontk imports
# (only Blender's own bundled modules are guaranteed in the child process). blendertk
# is imported OPTIONALLY, inside ``scene_data_sections``, and its absence is never fatal.
import glob
import math
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_USD = r"__OUT_USD__"
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
TEX_DIR = r"__TEX_DIR__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores
# PYTHONPATH, so the one OPTIONAL toolkit pass below (``scene_data_sections``) could
# not import otherwise; the core conversion never needs them.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
# Rig transfer (schema section 15): the mode, and the CONSUMER's capability
# manifest (JSON; empty unless the mode is "rig") this side plans against.
RIG_MODE = __RIG_MODE__
RIG_CAPABILITY = __RIG_CAPABILITY__

# glTF containers the conversion opens by IMPORT rather than by open_mainfile.
_GLTF_EXTENSIONS = (".glb", ".gltf")

# Blender file_format -> the extension its saved file must carry. A glTF's images
# are named without one ("Image_0"), and image.save() picks the encoder from the
# extension, so guessing wrong writes a PNG called .jpg that Maya then misreads.
_IMAGE_EXTENSIONS = {
    "PNG": ".png",
    "JPEG": ".jpg",
    "JPEG2000": ".jp2",
    "TARGA": ".tga",
    "TARGA_RAW": ".tga",
    "TIFF": ".tif",
    "OPEN_EXR": ".exr",
    "OPEN_EXR_MULTILAYER": ".exr",
    "HDR": ".hdr",
    "BMP": ".bmp",
    "WEBP": ".webp",
}


def _image_filename(image, taken, classified=None):
    """A unique, filesystem-safe filename for *image* inside TEX_DIR.

    *classified* is the map-type-bearing stem from _classified_names when the image
    feeds a recognized PBR socket; it is what makes the file classifiable on the
    Maya side. Falling back to the datablock name is deliberate rather than fatal --
    an unrecognized socket then behaves exactly like an oddly-named .blend texture.

    Datablock names are not filenames (a glTF's are often "Image_0", and Blender
    de-duplicates with a ".001" suffix that reads as an extension), and two
    datablocks can collide once sanitized -- so the extension comes from the
    ENCODER and uniqueness is enforced here rather than trusted.
    """
    if classified:
        # Already a stem by construction -- never splitext it. A Blender material
        # named "Mat.001" (the norm for any duplicate) would otherwise have its
        # whole map suffix read as an extension: "Mat.001_Base_Color" -> stem
        # "Mat", written as "Mat.png", which classifies as NOTHING on the Maya
        # side -- silently undoing the rename this function exists to perform.
        stem, ext = classified, ""
    else:
        stem, ext = os.path.splitext(os.path.basename(image.name or "image"))
    stem = re.sub(r"[^A-Za-z0-9_.-]", "_", stem).strip("._") or "image"
    if ext.lower() not in _IMAGE_EXTENSIONS.values():
        ext = _IMAGE_EXTENSIONS.get(image.file_format, ".png")
    name, n = stem + ext, 1
    while name.lower() in taken:
        name, n = "%s_%d%s" % (stem, n, ext), n + 1
    taken.add(name.lower())
    return name


# Principled inputs whose upstream image identifies the map. Both the pre-4.x and
# 4.x+ emission spellings are listed; only the one this Blender has will resolve.
_PBR_SOCKETS = (
    "Base Color",
    "Metallic",
    "Roughness",
    "Normal",
    "Emission Color",
    "Emission",
    "Alpha",
)

# Read off the "glTF Material Output" node group instead of the Principled BSDF --
# see _classified_names.
_GLTF_OUTPUT_SOCKETS = ("Occlusion",)


def _images_feeding(socket, seen=None):
    """Every image datablock upstream of *socket* (through Separate Color, Normal
    Map, Mix, node groups -- whatever the glTF importer wired in between)."""
    found, seen = [], set() if seen is None else seen
    for link in getattr(socket, "links", ()) or ():
        node = link.from_node
        if node in seen:
            continue
        seen.add(node)
        if node.bl_idname == "ShaderNodeTexImage":
            if node.image is not None and node.image not in found:
                found.append(node.image)
            continue
        for inp in node.inputs:
            for image in _images_feeding(inp, seen):
                if image not in found:
                    found.append(image)
    return found


def _map_suffix(sockets):
    """The canonical map-type name for an image feeding *sockets*, or None.

    This is the whole reason the unpack renames rather than reusing datablock
    names: the Maya side classifies a manifest file by FILENAME (the shared
    ptk.MapFactory taxonomy), and a glTF's images are named "Image_0" -- they
    would classify as nothing and every PBR slot would be left empty, which is
    an untextured material with no warning at all. The socket a texture feeds is
    the authoritative signal, and it is only available HERE, in the node tree.
    """
    if "Base Color" in sockets:
        return "Base_Color"
    # ANY two of occlusion/roughness/metallic sharing one image is an ORM: its
    # canonical layout (R=AO, G=Roughness, B=Metallic) is exactly glTF's packing,
    # so this covers occlusionRoughnessMetallic and the metallicRoughness-only
    # and occlusionRoughness subsets alike, without naming a channel that is
    # there after one that is not.
    if len(sockets & {"Metallic", "Roughness", "Occlusion"}) > 1:
        return "ORM"
    if "Metallic" in sockets:
        return "Metallic"
    if "Roughness" in sockets:
        return "Roughness"
    if "Occlusion" in sockets:
        return "Ambient_Occlusion"
    if "Normal" in sockets:
        return "Normal_OpenGL"  # glTF normals are OpenGL-convention by spec
    if sockets & {"Emission Color", "Emission"}:
        return "Emissive"
    if "Alpha" in sockets:
        return "Opacity"
    return None


def _classified_names(bpy):
    """``{image: "<material>_<Map_Type>"}`` for every image on a recognized socket.

    First claim wins when two materials share an image, and it HAS to: an image
    datablock carries exactly one filepath, so one file is all that can be written
    for it. Materials sharing an image in the same role (the norm) all resolve to
    the same map type either way; the pathological cross-role case (base colour in
    one material, roughness in another) is unrepresentable, not merely unhandled.
    """
    names, roles = {}, {}

    def claim(mat_name, socket, role):
        if socket is None:
            return
        for image in _images_feeding(socket):
            roles.setdefault((mat_name, image), set()).add(role)

    for mat in bpy.data.materials:
        tree = getattr(mat, "node_tree", None)
        if tree is None:
            continue
        for node in tree.nodes:
            if node.bl_idname == "ShaderNodeBsdfPrincipled":
                for socket_name in _PBR_SOCKETS:
                    claim(mat.name, node.inputs.get(socket_name), socket_name)
            elif node.bl_idname == "ShaderNodeGroup":
                # Occlusion never reaches the Principled BSDF: the glTF importer
                # hangs it off a "glTF Material Output" group, so a walk of
                # Principled inputs alone is BLIND to a separate AO texture.
                # Blender's own exporter merges occlusion into the roughness
                # image (verified on 5.1), but Substance / Maya glTF exporters
                # ship a standalone one, and it would arrive unclassified.
                if (getattr(node.node_tree, "name", "") or "").startswith("glTF"):
                    for socket_name in _GLTF_OUTPUT_SOCKETS:
                        claim(mat.name, node.inputs.get(socket_name), socket_name)
    for (mat_name, image), sockets in roles.items():
        suffix = _map_suffix(sockets)
        if suffix and image not in names:
            names[image] = "%s_%s" % (mat_name, suffix)
    return names


def _unpack_images(bpy):
    """Write every PACKED image to TEX_DIR and repoint its datablock at the file.

    Load-bearing for a glTF source: the container holds its images, so without this
    every one of them resolves to no on-disk file -- the FBX route would write a
    file-less texture manifest (a NAMED warning and gray materials on the Maya side)
    and the USD route's KEEP texture mode would reference nothing. A .blend needs
    none of it; its images already point at files.

    Each file is named for the MAP TYPE its socket implies (see _map_suffix), not for
    the datablock -- the Maya-side rebuild classifies by filename, and "Image_0" is
    not a classification. An image feeding no recognized socket keeps its datablock
    name and degrades exactly as an oddly-named .blend texture already does.

    TEX_DIR is a persistent, source-keyed dir the Maya side owns (BlenderSceneImport
    ._texture_dir), deliberately NOT the conversion scratch: the intermediate is
    promoted into a cache slot and outlives that scratch, so textures written beside
    it would be swept out from under the payload referencing them.

    Best-effort per image -- one unwritable datablock degrades to the existing
    file-less-entry warning instead of failing the whole conversion.
    """
    if not TEX_DIR:
        return
    os.makedirs(TEX_DIR, exist_ok=True)
    classified = _classified_names(bpy)
    taken, saved = set(), 0
    for image in bpy.data.images:
        if image.packed_file is None:
            continue
        path = os.path.join(
            TEX_DIR, _image_filename(image, taken, classified.get(image))
        )
        try:
            image.filepath_raw = path
            # Unconditional: this runs only on a conversion cache MISS (a full
            # Blender launch), so skipping a write that "looks done" saves nothing
            # measurable and would silently adopt a truncated file left by a
            # killed or half-failed earlier run.
            image.save()
            saved += 1
            print("  unpacked %r -> %s" % (image.name, os.path.basename(path)))
        except Exception as e:
            print("could not unpack image %r: %s" % (image.name, e))
    print("unpacked %d packed image(s) to %s" % (saved, TEX_DIR))


def _import_gltf(bpy):
    """Import SRC_PATH, tolerant of the importer's home moving between versions.

    ``import_scene.gltf`` is the long-standing spelling; Blender's newer file
    handlers register importers under ``wm.*``, so the ``wm.gltf_import`` fallback
    keeps a rename from breaking the pull -- the same per-version tolerance the
    export call applies to its kwargs.
    """
    errors = []
    for name, op in (
        ("import_scene.gltf", getattr(bpy.ops.import_scene, "gltf", None)),
        ("wm.gltf_import", getattr(bpy.ops.wm, "gltf_import", None)),
    ):
        if op is None:
            continue
        try:
            op(filepath=SRC_PATH)
            return
        except Exception as e:
            errors.append("%s: %s" % (name, e))
    raise RuntimeError(
        "no usable glTF importer in this Blender (%s)"
        % ("; ".join(errors) or "none found")
    )


def open_source(bpy):
    """Load SRC_PATH into the conversion session.

    A .blend REPLACES the session (``open_mainfile``). A glTF is *imported* into it,
    so the factory startup scene is emptied first -- ``--factory-startup`` still
    loads the default cube/camera/light, which would otherwise ride the intermediate
    straight into the user's Maya scene. Nothing downstream can tell the two source
    kinds apart after this.
    """
    if os.path.splitext(SRC_PATH)[1].lower() not in _GLTF_EXTENSIONS:
        bpy.ops.wm.open_mainfile(filepath=SRC_PATH, load_ui=False)
        return
    bpy.ops.wm.read_factory_settings(use_empty=True)
    _import_gltf(bpy)
    _unpack_images(bpy)


def _narrow_frame_range(bpy):
    """Clamp the scene's frame range to what actually animates; False if nothing does.

    USD has no animation *curves* -- ``export_animation`` writes a time sample per
    frame for every prim, so the frame range is a direct multiplier on export cost
    (the Maya-side mirror of this gate measured 234s -> 1.8s on a 755-object static
    module). Blender's exporter reads ``scene.frame_start/end`` rather than taking a
    range argument, so narrowing means assigning them -- safe here because this
    conversion scene is a throwaway process that is never saved.

    Constraints and drivers move things without keys of their own, so their range
    can't be derived; they keep the scene's full range. Actions report their own
    ``frame_range``, which is clamped to the scene range (a stray far-out key must
    not multiply the sample count).
    """
    scene = bpy.context.scene
    lo = hi = None

    for ob in scene.objects:
        if ob.constraints:
            return True  # motion with no keys of its own -- can't infer a range
        data = getattr(ob, "data", None)
        owners = (ob, data, getattr(data, "shape_keys", None))
        for ad in [getattr(o, "animation_data", None) for o in owners if o]:
            if ad is None:
                continue
            if ad.nla_tracks or ad.drivers:
                return True
            if ad.action:
                a, b = ad.action.frame_range
                lo = a if lo is None else min(lo, a)
                hi = b if hi is None else max(hi, b)

    if lo is None:
        return False
    # floor/ceil, not int(): int() truncates toward zero, which would clip a key
    # at 20.5 down to 20 (losing motion) and mis-round negative frames.
    start = max(scene.frame_start, math.floor(lo))
    end = min(scene.frame_end, math.ceil(hi))
    if end < start:  # keys live entirely outside the scene's own time
        return False
    scene.frame_start, scene.frame_end = start, end
    print("USD export: sampling frames {}-{}".format(start, end))
    return True


def export_usd(bpy):
    """Whole-scene USD export with per-kwarg tolerance across Blender versions.

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in another exporter version is dropped and the
    call retried -- the same tolerance loop as the FBX template.
    ``relative_paths=False`` is the load-bearing one: the USD lives in the temp
    dir, so relative texture refs would be unresolvable in Maya (the FBX
    route's ``path_mode='ABSOLUTE'`` mirror).
    """
    kwargs = {
        "filepath": OUT_USD,
        "selected_objects_only": False,
        "visible_objects_only": False,  # pre-5.x only; dropped elsewhere
        "export_materials": True,
        "generate_preview_surface": True,
        # Reference the ORIGINAL texture files, never copy: the USD lives in
        # scratch, so a copied textures/ dir would be cleaned away right after
        # the import (dangling file nodes — observed live on 5.1, whose
        # default is NEW/copy) and would freeze texture edits out of cache
        # hits. Two spellings of the same intent — the tolerance loop drops
        # whichever one this Blender doesn't know.
        "export_textures_mode": "KEEP",  # 4.2+ / 5.x name
        "export_textures": False,  # pre-4.2 name
        "relative_paths": False,
        # Flat export, instances rebuilt Maya-side from the sidecar below. USD's
        # instancing gives Maya read-only prototypes, not the shared-shape model
        # a Maya artist edits (measured: 6 transforms -> 6 independent shapes
        # either way), and prototype prim names break 1:1 name matching. Flat +
        # recorded grouping is the mirror of the Maya->Blender direction.
        "use_instancing": False,
        # Only pay for time samples when something actually animates, and only
        # across the frames that carry motion (see _narrow_frame_range).
        "export_animation": INCLUDE_ANIMATION and _narrow_frame_range(bpy),
        # One prim per object (Blender otherwise writes an Xform + child Mesh
        # pair) and no /root wrapper — flat parity with the FBX route's
        # import structure on the Maya side.
        "merge_parent_xform": True,
        "root_prim_path": "",
        # Maya reads a USD layer in its own cm without converting (mayaUsd 0.30
        # has no unit conversion on import -- probed), so the layer is written
        # in centimeters: a scale of 100 on the ROOT prims, exactly how the FBX
        # route lands (apply_unit_scale), world bounds correct.
        "convert_scene_units": "CENTIMETERS",
        # ...and in Maya's Y-up: mayaUsd reads a layer WITHOUT converting
        # (``upAxis`` is inert on import -- probed), so a Z-up stage landed a
        # production module rotated +90 about X (2026-08-22). The exporter
        # bakes the conversion onto the ROOT prims beside the unit scale, where
        # the FBX exporter's axis conversion lands too. Mirror of
        # btk.UsdUtils' Y-up export options.
        "convert_orientation": True,
        "export_global_forward_selection": "NEGATIVE_Z",
        "export_global_up_selection": "Y",
    }
    # Blender 5.1 drops an animated object's Mesh when merged + animated (see
    # fold_single_mesh_xforms): export unmerged, then fold back.
    fold = bool(kwargs["export_animation"])
    if fold:
        kwargs["merge_parent_xform"] = False
    # The hidden set travels hidden, as it does through FBX. Blender's exporter
    # has no such mode: it skips an object by ``hide_render`` in its RENDER
    # evaluation and by ``hide_viewport`` / the eye in VIEWPORT evaluation
    # (probed on 5.1 -- a hidden bake-source set arrived in Maya VISIBLE), so
    # every hide flag is cleared for the call and the viewport-hidden set's
    # prims are stamped invisible afterwards (btk.UsdUtils.export's contract).
    # A KEYED show/hide travels as keys (the manifest's visibility section).
    hidden = [o for o in hidden_objects(bpy) if not hide_is_animated(o)]
    # Blender's USD camera writer supports perspective only -- an ORTHO camera
    # leaves a bare Xform (probed on 5.1), which is how a production module's one
    # authored camera never reached Maya. Written as perspective, re-authored
    # orthographic below.
    ortho = _as_perspective(bpy.data.objects)
    for obj in bpy.data.objects:  # this Blender is disposable: no state to restore
        obj.hide_viewport = False
        obj.hide_render = False
        try:
            obj.hide_set(False)
        except RuntimeError:
            pass
    while True:
        try:
            bpy.ops.wm.usd_export(**kwargs)
            if fold:
                fold_single_mesh_xforms(OUT_USD)
            # After the fold, which RENAMES prims; both address them by path.
            pinned = pin_primvar_indices(OUT_USD)
            if pinned:
                print("USD export: pinned {} primvar index array(s)".format(pinned))
            if fold:  # an animated export: every object holding an action is sampled
                held = collapse_static_xforms(OUT_USD)
                if held:
                    print("USD export: held {} static transform(s)".format(held))
            marked = mark_skinning_methods(bpy, OUT_USD)
            if marked:
                print("USD export: stamped {} skinning method(s)".format(marked))
            containers = mark_container_skeletons(OUT_USD)
            if containers:
                print("USD export: marked {} container skeleton(s)".format(containers))
            if ortho:
                print(
                    "USD export: {} orthographic camera(s) re-authored".format(
                        mark_orthographic(OUT_USD, ortho)
                    )
                )
            if hidden:
                print(
                    "USD export: {} hidden object(s) stamped invisible".format(
                        mark_invisible(OUT_USD, hidden)
                    )
                )
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs and key != "filepath":
                print("USD kwarg skipped (unsupported by this exporter): " + key)
                del kwargs[key]
                continue
            raise


def hidden_objects(bpy):
    """The viewport-hidden objects: ``hide_viewport`` (the monitor toggle) or
    the view layer's eye (``hide_get``) -- what Maya's ``visibility`` off means.
    Dependency-free copy of ``btk.UsdUtils.hidden_objects`` (pinned equal)."""
    out = []
    for o in bpy.data.objects:
        try:
            hidden = o.hide_viewport or o.hide_get()
        except RuntimeError:  # not in the view layer: the eye is undefined
            hidden = o.hide_viewport
        if hidden:
            out.append(o)
    return out


def sanitize_prim_name(name):
    """*name* as Blender's USD exporter spells the prim (``Chair.001`` ->
    ``Chair_001``; a leading digit is prefixed ``_``). Dependency-free copy of
    ``btk.UsdUtils.sanitize_prim_name`` (pinned equal)."""
    if not name:
        return "_"
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name[0].isdigit():
        name = "_" + name
    return name


def export_prim_path(obj, root_prim_path=""):
    """The prim path the exporter writes for *obj* (one prim per object): its
    parent chain through ``sanitize_prim_name``. Dependency-free copy of
    ``btk.UsdUtils.export_prim_path`` (pinned equal)."""
    parts, cur = [], obj
    while cur is not None:
        parts.append(sanitize_prim_name(cur.name))
        cur = cur.parent
    return (root_prim_path or "").rstrip("/") + "/" + "/".join(reversed(parts))


def pin_primvar_indices(filepath):
    """Give every indexed primvar a DEFAULT index array, copied from its lone
    time sample when that is the only place one was authored; return the count.
    Dependency-free copy of ``btk.UsdUtils.pin_primvar_indices`` (pinned equal).

    Blender 5.1 writes a SKINNED mesh's UVs split across time -- values at the
    default, indices as one sample at the first frame -- and mayaUsd, reading at
    the default, refuses the set and lands the mesh with UV coordinates and NO
    assigned faces. Measured on a production module: 7 of 7 skinned meshes, 0 of
    1498 unskinned."""
    from pxr import Usd, UsdGeom

    stage = Usd.Stage.Open(filepath)
    if stage is None:
        return 0
    count = varying = 0
    for prim in stage.Traverse():
        for primvar in UsdGeom.PrimvarsAPI(prim).GetPrimvars():
            attr = primvar.GetIndicesAttr()
            if not attr or not attr.HasAuthoredValue() or attr.Get() is not None:
                continue  # absent, or already readable at the default
            samples = attr.GetTimeSamples()
            if len(samples) != 1:
                # Exactly one sample is the measured defect: a constant mapping
                # written to the wrong place. Several mean the indices genuinely
                # vary, and pinning the first would publish one frame's mapping
                # as the answer for all of them.
                varying += bool(samples)
                continue
            indices = attr.Get(samples[0])
            if indices is None:
                continue
            attr.Set(indices)
            count += 1
    if varying:
        print(
            "USD export: {} primvar(s) index over TIME with no default; left as "
            "authored".format(varying)
        )
    if count:
        stage.GetRootLayer().Save()
    return count


def mark_skinning_methods(bpy, filepath, objects=None, root_prim_path=""):
    """Stamp each skinned mesh's ``skinningMethod`` from its Armature modifier's
    Preserve Volume; return the count. Dependency-free copy of
    ``btk.UsdUtils.mark_skinning_methods`` (pinned equal).

    Blender's exporter authors the attribute for nothing, so a dual-quaternion
    skin returned to Maya deforming LINEARLY -- 4.03 mm of shape error on a
    production module, against 0.22 mm of placement."""
    from pxr import Sdf, Usd, UsdSkel

    layer = Sdf.Layer.FindOrOpen(filepath)
    if layer is None:
        raise FileNotFoundError("USD layer not found: " + filepath)
    stage = Usd.Stage.Open(layer)
    count = 0
    for obj in bpy.data.objects if objects is None else objects:
        if getattr(obj, "type", "") != "MESH":
            continue
        armatures = [
            m
            for m in (getattr(obj, "modifiers", None) or [])
            if getattr(m, "type", "") == "ARMATURE"
        ]
        if not armatures:
            continue
        prim = stage.GetPrimAtPath(export_prim_path(obj, root_prim_path))
        if not prim or not prim.IsValid():
            continue
        method = (
            "dualQuaternion"
            if any(m.use_deform_preserve_volume for m in armatures)
            else "classicLinear"
        )
        UsdSkel.BindingAPI.Apply(prim)
        UsdSkel.BindingAPI(prim).CreateSkinningMethodAttr().Set(method)
        count += 1
    if count:
        layer.Save()
    return count


def mark_container_skeletons(filepath):
    """Mark each Skeleton prim that is only a container for its bones with
    mayaUsd's ``customData Maya:generated``, so Maya makes no joint of it;
    return the count. Dependency-free copy of
    ``btk.UsdUtils.mark_container_skeletons`` (pinned identical by
    ``test_scene_import.py::TestUsdContainerSkeletons``).

    Unmarked, every armature arrived with an extra joint at its origin that a
    bone's path named whenever the data is called like its root bone -- the
    rig transfer measured it 2.4-2.6 m off. A skeleton at the root or one
    carrying its object's transform (a static export's merged leaf armature)
    is left alone: marked, mayaUsd lands either with no joints at all."""
    import os

    if os.path.splitext(str(filepath))[1].lower() == ".usdz":
        return 0
    from pxr import Sdf, Usd, UsdGeom, UsdSkel

    layer = Sdf.Layer.FindOrOpen(str(filepath))
    if layer is None:
        raise FileNotFoundError("USD layer not found: " + str(filepath))
    stage = Usd.Stage.Open(layer)
    count = 0
    for prim in stage.Traverse():
        if not prim.IsA(UsdSkel.Skeleton) or prim.HasCustomDataKey("Maya:generated"):
            continue
        if prim.GetParent().IsPseudoRoot():
            continue  # no parent node to hold the joints
        xformable = UsdGeom.Xformable(prim)
        if xformable.GetOrderedXformOps() or xformable.GetResetXformStack():
            continue  # the object's own transform lives here
        prim.SetCustomDataByKey("Maya:generated", True)
        count += 1
    if count:
        layer.Save()
    return count


def mark_invisible(filepath, objects, root_prim_path=""):
    """Stamp ``visibility = invisible`` on the prims *objects* exported to;
    return the count (the layer is saved in place). Dependency-free copy of
    ``btk.UsdUtils.mark_invisible`` (pinned equal)."""
    from pxr import Sdf, Usd, UsdGeom

    layer = Sdf.Layer.FindOrOpen(filepath)
    if layer is None:
        raise FileNotFoundError("USD layer not found: " + filepath)
    stage = Usd.Stage.Open(layer)
    count = 0
    for obj in objects:
        prim = stage.GetPrimAtPath(export_prim_path(obj, root_prim_path))
        if not prim or not prim.IsValid():
            continue
        UsdGeom.Imageable(prim).CreateVisibilityAttr().Set(UsdGeom.Tokens.invisible)
        count += 1
    if count:
        layer.Save()
    return count


def _as_perspective(objects):
    """Flip every ORTHO camera among *objects* to PERSP for the writer; return the
    camera objects flipped. Dependency-free copy of
    ``btk.UsdUtils._as_perspective`` (pinned by AST identity); this Blender is
    disposable, so nothing flips back. Collected before anything flips: a
    datablock shared by two objects would otherwise read PERSP for the second."""
    cameras = [
        o
        for o in objects
        if getattr(o, "type", None) == "CAMERA" and o.data.type == "ORTHO"
    ]
    for data in {o.data for o in cameras}:
        data.type = "PERSP"
    return cameras


def collapse_static_xforms(filepath, tolerance=1e-4, distance=1e-5):
    """Hold every prim whose LOCAL transform never changes at one static value
    (its xform ops lose their time samples). Dependency-free copy of
    ``btk.UsdUtils.collapse_static_xforms`` (pinned by AST identity): Blender
    samples the whole transform of any object holding an action, so a
    show/hide-only object ships per-frame noise that mayaUsd keys. Translation
    is judged in metres (*distance*), through the parent's world scale and the
    stage's metersPerUnit; the rotation/scale block by *tolerance*."""
    import os

    if os.path.splitext(str(filepath))[1].lower() == ".usdz":
        return 0
    from pxr import Sdf, Usd, UsdGeom

    layer = Sdf.Layer.FindOrOpen(str(filepath))
    if layer is None:
        raise FileNotFoundError(f"USD layer not found: {filepath}")
    stage = Usd.Stage.Open(layer)
    metres = UsdGeom.GetStageMetersPerUnit(stage) or 1.0
    count = 0
    for prim in stage.Traverse():
        xformable = UsdGeom.Xformable(prim)
        if not xformable:
            continue
        ops = xformable.GetOrderedXformOps()
        times = sorted({t for op in ops for t in op.GetAttr().GetTimeSamples()})
        if not times:
            continue
        first = xformable.GetLocalTransformation(times[0])
        parent = xformable.ComputeParentToWorldTransform(times[0])
        scale = max(parent.GetRow3(i).GetLength() for i in range(3)) or 1.0
        reach = distance / (metres * scale)  # *distance* in local numbers
        if any(
            abs(a - b) > (reach if row == 3 else tolerance)
            for t in times[1:]
            for row, (row_a, row_b) in enumerate(
                zip(xformable.GetLocalTransformation(t), first)
            )
            for a, b in zip(row_a, row_b)
        ):
            continue
        for op in ops:
            value = op.Get(times[0])
            attr = op.GetAttr()
            attr.Clear()
            if value is not None:
                attr.Set(value)
        count += 1
    if count:
        layer.Save()
    return count


def mark_orthographic(filepath, cameras, root_prim_path=""):
    """Author each of *cameras* (ORTHO camera objects, exported as perspective) as
    an orthographic Camera prim; return the count. Dependency-free copy of
    ``btk.UsdUtils.mark_orthographic`` (pinned by AST identity): ``ortho_scale``
    goes in as both apertures, the inverse of Blender's own USD reader, which
    mayaUsd reads as ``orthographicWidth`` = aperture / 10."""
    from pxr import Sdf, Usd, UsdGeom

    layer = Sdf.Layer.FindOrOpen(filepath)
    if layer is None:
        raise FileNotFoundError(f"USD layer not found: {filepath}")
    stage = Usd.Stage.Open(layer)
    count = 0
    for obj in cameras:
        prim = stage.GetPrimAtPath(export_prim_path(obj, root_prim_path))
        if not prim or not prim.IsValid():
            continue
        camera = next(
            (
                UsdGeom.Camera(candidate)
                for candidate in [prim] + list(prim.GetChildren())
                if candidate.IsA(UsdGeom.Camera)
            ),
            None,
        )
        if camera is None:
            continue
        width = float(obj.data.ortho_scale)
        for attr, value in (
            (camera.CreateProjectionAttr(), UsdGeom.Tokens.orthographic),
            (camera.CreateHorizontalApertureAttr(), width),
            (camera.CreateVerticalApertureAttr(), width),
        ):
            attr.Clear()
            attr.Set(value)
        count += 1
    if count:
        layer.Save()
    return count


def fold_single_mesh_xforms(filepath):
    """Fold every Xform whose only child is a Mesh into one Mesh prim carrying the
    Xform's ops -- the shape ``merge_parent_xform=True`` would have written.

    Blender 5.1 DROPS an animated object's Mesh when ``merge_parent_xform`` and
    ``export_animation`` are both on (probe: a keyed cube exports as a bare
    Xform), so an animated export runs unmerged and is folded back here through
    the ``pxr`` Blender bundles. Dependency-free copy of
    ``btk.UsdUtils.fold_single_mesh_xforms``, drift-guarded BEHAVIOURALLY by
    ``test_scene_import.py::test_template_fold_matches_the_engine_s_behavior``.
    """
    from pxr import Sdf, Usd, UsdGeom

    layer = Sdf.Layer.FindOrOpen(filepath)
    stage = Usd.Stage.Open(layer)
    targets = []
    for prim in stage.Traverse():
        if prim.GetTypeName() != "Xform":
            continue
        kids = prim.GetChildren()
        if (
            len(kids) == 1
            and kids[0].GetTypeName() == "Mesh"
            and not UsdGeom.Xformable(kids[0]).GetOrderedXformOps()
        ):
            targets.append((prim.GetPath(), kids[0].GetPath()))
    for xf_path, mesh_path in targets:
        xf_spec = layer.GetPrimAtPath(xf_path)
        for attr in list(xf_spec.attributes):
            if attr.name.startswith("xformOp:") or attr.name == "xformOpOrder":
                Sdf.CopySpec(
                    layer, attr.path, layer, mesh_path.AppendProperty(attr.name)
                )
        parent = xf_path.GetParentPath()
        tmp_name = xf_path.name + "__fold"
        # Rename BEFORE reparenting: a mesh datablock named like its object
        # (``/mover/mover``) would otherwise collide with the Xform it is
        # about to replace ("cannot be an ancestor of itself").
        edit = Sdf.BatchNamespaceEdit()
        edit.Add(Sdf.NamespaceEdit.Rename(mesh_path, tmp_name))
        edit.Add(Sdf.NamespaceEdit.Reparent(xf_path.AppendChild(tmp_name), parent, -1))
        edit.Add(Sdf.NamespaceEdit.Remove(xf_path))
        edit.Add(Sdf.NamespaceEdit.Rename(parent.AppendChild(tmp_name), xf_path.name))
        if not layer.Apply(edit):
            raise RuntimeError("USD fold failed for {}".format(xf_path))
    if targets:
        layer.Save()
    print("USD export: folded {} animated Xform+Mesh pair(s)".format(len(targets)))
    return len(targets)


def _action_fcurves(action, slot=None):
    """The fcurves of *action* -- *slot*'s own when given, else every slot's -- on
    any Blender.

    Dependency-free copy of ``btk.AnimUtils._slot_fcurves`` (pinned by AST
    identity): 4.4+ actions are layered and 5.x drops the flat ``action.fcurves``
    entirely, so keys live in per-slot channelbags. Pass the object's
    ``action_slot``: one action can drive several objects through slots, and a
    slot-blind read hands each of them every other object's curves.
    """
    legacy = getattr(action, "fcurves", None)
    if legacy is not None:
        return list(legacy)
    out = []
    for layer in action.layers:
        for strip in layer.strips:
            if slot is not None:
                cb = strip.channelbag(slot)
                if cb is not None:
                    out.extend(cb.fcurves)
            else:
                out.extend(fc for cb in strip.channelbags for fc in cb.fcurves)
    return out


def collect_visibility(bpy):
    """``{object name: [[frame, visibility], ...]}`` -- the manifest's ``visibility``
    section, in MAYA's convention (``1`` = visible). Shared verbatim by the FBX and
    USD conversion templates.

    Neither Blender exporter carries a show/hide. The FBX one bakes only Lcl
    Translation / Rotation / Scaling: measured on a production module, 54 objects
    carried ``hide_viewport`` keys and every one arrived in Maya static -- 39 of them
    with no animation whatsoever, which is how the loss first read. The USD one
    writes no visibility samples for them either: the same module's USD return leg
    delivered 83 show/hide-only objects static and not one visibility curve
    (2026-09-21). These are the plug and failed-component toggles, i.e. the content
    of the training module.

    The mirror of the send direction, which puts Maya's baked ``.visibility`` in this
    same section for ``btk.MayaSceneImport`` to replay as ``hide_*`` keys: same
    section, same value convention, opposite direction. ``hide_viewport`` is
    preferred over ``hide_render`` because the send direction writes both from one
    Maya plug and it is the one the artist sees.

    What an ancestor already says is left OUT. Maya inherits visibility down the DAG
    and Blender's ``hide_*`` does not, so the send direction BAKES an ancestor's
    show/hide onto every descendant to make the scene look right there. Writing those
    copies back would key in Maya what Maya derives for itself, and the next send
    would bake one level deeper again: measured, the module's animated-object count
    went 65 -> 85 in a single round trip, which is a fixed-point failure that
    compounds. A track identical to the nearest keyed ancestor's is therefore
    dropped -- 44 of this module's 54 -- leaving the ~10 an artist actually authored,
    and the evaluated result is unchanged because Maya re-derives the rest.

    Collected before the export touches the scene -- on the FBX route before
    ``stand_in_dropped_objects``, which renames an object the exporter would drop and
    gives its name to the Empty that ships instead: the keys then travel under the
    name the payload really carries.
    """
    tracks = {}
    for obj in bpy.context.scene.objects:
        data = getattr(obj, "animation_data", None)
        action = getattr(data, "action", None)
        if action is None:
            continue
        slot = getattr(data, "action_slot", None)
        curves = {fc.data_path: fc for fc in _action_fcurves(action, slot)}
        fcurve = curves.get("hide_viewport") or curves.get("hide_render")
        if fcurve is None:
            continue
        keys = sorted(
            # Blender hides on TRUE; Maya's .visibility shows on 1.
            (float(key.co[0]), 0.0 if key.co[1] else 1.0)
            for key in fcurve.keyframe_points
        )
        if keys:
            tracks[obj.name] = keys

    def inherited(obj):
        """The nearest ancestor's track -- what Maya applies to *obj* on its own."""
        parent = obj.parent
        while parent is not None:
            if parent.name in tracks:
                return tracks[parent.name]
            parent = parent.parent
        return None

    visibility = {}
    for obj in bpy.context.scene.objects:
        keys = tracks.get(obj.name)
        if not keys or inherited(obj) == keys:
            continue
        visibility[obj.name] = [[frame, value] for frame, value in keys]
    if visibility:
        print(
            "visibility keys for {} object(s) written to the manifest.".format(
                len(visibility)
            )
        )
    return visibility


def hide_is_animated(obj):
    """True when *obj*'s show/hide is keyed. Its keys travel in the manifest's
    ``visibility`` section (``collect_visibility``), so the static ``invisible``
    stamp must leave it out: the stamp would pin a prim the keys switch, and a child
    whose track the collector drops because an ancestor already says it would stay
    hidden in Maya for good, whatever that ancestor's keys do."""
    data = getattr(obj, "animation_data", None)
    action = getattr(data, "action", None)
    if action is None:
        return False
    return any(
        fc.data_path in ("hide_viewport", "hide_render")
        for fc in _action_fcurves(action, getattr(data, "action_slot", None))
    )


def collect_empties(bpy):
    """``[{name, display_type}, ...]`` for the scene's Empties (node-type sidecar).

    Every Empty arrives in Maya as a SHAPELESS transform off a USD layer, so the
    point markers need their locator shapes back; the display type carries the
    author's intent and a ``maya_node_type`` custom property (round-tripped
    scenes) overrides it. Dependency-free copy of the FBX template's collector,
    held AST-identical to it by ``test_scene_import.py::
    test_template_collect_empties_is_the_fbx_template_s_copy``.
    """
    empties = []
    for obj in bpy.context.scene.objects:
        if obj.type != "EMPTY":
            continue
        entry = {"name": obj.name, "display_type": obj.empty_display_type}
        node_type = obj.get("maya_node_type")
        if node_type:
            entry["maya_node_type"] = str(node_type)
        empties.append(entry)
    return empties


# Tiled-image filename tokens -> the glob that finds their tiles on disk.
# ``<UDIM>`` is Blender's standard (1001-style); ``<UVTILE>`` the u1_v1 style.
_TILE_TOKENS = (("<UDIM>", "[0-9]" * 4), ("<UVTILE>", "u*_v*"))


def _resolved_image_file(bpy, image):
    """Absolute on-disk path of *image*, or None (packed-only / missing / generated).

    UDIM/UVTILE sets resolve to their lowest-numbered existing tile: neither FBX
    nor the manifest's per-file classification has a tiling concept, so one real
    tile (logged as flattened) beats an unresolvable ``<UDIM>`` token that would
    otherwise surface as a misleading "packed or needs relinking" warning.
    """
    if image is None:
        return None
    try:
        path = bpy.path.abspath(image.filepath, library=image.library)
    except Exception:
        return None
    if not path:
        return None
    path = os.path.abspath(path)
    for token, pattern in _TILE_TOKENS:
        if token in path:
            # glob.escape the literal parts only -- the path itself may hold
            # glob-special chars ([ ] * ?); the token survives escaping intact.
            tiles = sorted(glob.glob(glob.escape(path).replace(token, pattern)))
            if tiles:
                print("tiled image flattened to its first tile: " + tiles[0])
                return tiles[0]
            return None
    return path if os.path.isfile(path) else None


def _material_files(bpy, mat):
    """(files, image_node_count) -- every image-texture file feeding *mat*.

    Free-form walk of the whole node tree (node groups included), matching the
    Maya-side history walk: the manifest carries EVERYTHING; classification into
    map types happens Maya-side via the shared filename taxonomy.
    """
    files = []
    node_count = 0

    def walk(tree, seen):
        nonlocal node_count
        if tree is None or tree in seen:
            return
        seen.add(tree)
        for node in tree.nodes:
            if node.bl_idname == "ShaderNodeTexImage":
                if node.image is not None:
                    node_count += 1
                path = _resolved_image_file(bpy, node.image)
                if path and path not in files:
                    files.append(path)
            elif node.bl_idname == "ShaderNodeGroup":
                walk(node.node_tree, seen)

    walk(mat.node_tree if mat.use_nodes else None, set())
    return files, node_count


def collect_texture_manifest(bpy):
    """Manifest entries for every textured material on an exportable object,
    plus the full list of scene-material names (returned as a pair).

    One entry per material (Blender shares material datablocks natively -- the
    Maya-side memoization problem cannot arise here); ``objects`` merges every
    user so the Maya side has an object-level fallback when the FBX importer
    renames materials. Materials with no image nodes are skipped (their flat
    colors ride the FBX fine); materials whose image nodes all failed to resolve
    to disk files are written file-less so the Maya side warns BY NAME.
    """
    entries = []
    by_material = {}
    # EVERY material name on an exportable object, textured or not. The Maya
    # side excludes these exact spellings from its rename-on-clash suffix
    # match: an untextured "Mat2" alongside textured "Mat" must never be
    # claimed as "Mat renamed to Mat2".
    scene_materials = []
    # The ACTIVE scene's objects only -- the FBX exporter exports exactly that
    # set, and bpy.data.objects would drag in other scenes / unlinked objects,
    # producing entries nothing Maya-side can ever match.
    for obj in bpy.context.scene.objects:
        if obj.type != "MESH":
            continue
        for slot in obj.material_slots:
            mat = slot.material
            if mat is None:
                continue
            if mat.name not in scene_materials:
                scene_materials.append(mat.name)
            if mat.name in by_material:
                entry = by_material[mat.name]
                if obj.name not in entry["objects"]:
                    entry["objects"].append(obj.name)
                continue
            files, image_nodes = _material_files(bpy, mat)
            if image_nodes == 0:
                continue
            entry = {
                "name": mat.name,
                "shader_type": "principled_bsdf",
                "fbx_material": mat.name,
                "objects": [obj.name],
                "files": files,
            }
            by_material[mat.name] = entry
            entries.append(entry)
            print(
                "manifest: {} ({} texture file(s) resolved of {} image node(s))".format(
                    mat.name, len(files), image_nodes
                )
            )
    return entries, scene_materials


def _sanitize_prim_name(name):
    """Mirror of Blender's USD prim-name rewrite (probe-verified on 5.1): every
    char outside ``[A-Za-z0-9_]`` becomes ``_``, and a leading digit is PREFIXED
    with ``_`` -- unlike ``TfMakeValidIdentifier``, which would REPLACE it. The
    sidecar must record what the exporter actually writes, so match the DCC,
    not Tf. Keep identical to the blendertk twin.
    """
    if not name:
        return "_"
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name[0].isdigit():
        name = "_" + name
    return name


def collect_instance_groups(bpy):
    """Blender linked duplicates -> ``[[sanitized prim names sharing one mesh], ...]``.

    The mirror of the Maya-side collector. The export is flat (see
    ``use_instancing``), so the sharing relationship travels as data and
    ``_apply_instance_manifest`` rebuilds real Maya instances from it -- without
    this, a .blend whose props are linked duplicates arrives as N independent
    shapes and the scene's memory profile is wrong (the FBX route preserves it
    for free, so USD has to match that to be a usable alternative).

    Names are recorded SANITIZED -- what the exporter writes as prim names --
    so the Maya side matches them 1:1 (``Chair.001`` exports as ``Chair_001``;
    raw names would silently miss). Two objects whose names sanitize to the
    SAME prim name are renamed apart unpredictably by the exporter
    (``a_b``/``a_b_001``, probe-verified), so a collision touching a recorded
    member fails the export loudly rather than shipping a sidecar that cannot
    match.

    Recorded, never inferred: matching by geometry would also fuse
    coincidentally-identical meshes, making an edit to one silently change
    another.

    Each group is SORTED. ``scene.objects`` iterates in insertion order, so the same
    scene converted twice recorded its members in different orders -- which made the
    sidecar unreproducible and, on the FBX route, handed the replay a different
    "first" member each time (measured: one hop listed ``ASSET_001`` first and the
    next ``ASSET_001_001``). The replay picks its own master regardless, but a
    deterministic sidecar is what makes two conversions comparable at all.
    """
    sanitized = {}
    for ob in bpy.context.scene.objects:
        sanitized.setdefault(_sanitize_prim_name(ob.name), []).append(ob.name)

    groups = {}
    for ob in bpy.context.scene.objects:
        if ob.type != "MESH" or ob.data is None:
            continue
        groups.setdefault(ob.data.name, []).append(ob.name)
    recorded = [names for names in groups.values() if len(names) > 1]

    colliding = {}
    for names in recorded:
        for name in names:
            key = _sanitize_prim_name(name)
            if len(sanitized[key]) > 1:
                colliding[key] = sanitized[key]
    if colliding:
        raise RuntimeError(
            "Object names collide after USD prim sanitization -- the exporter "
            "renames them apart unpredictably, so their linked duplicates could "
            "not be matched on the Maya side. Rename to distinct prim-safe "
            "names or pull via FBX: "
            + "; ".join("{} <- {}".format(k, v) for k, v in sorted(colliding.items()))
        )
    return [sorted(_sanitize_prim_name(n) for n in names) for names in recorded]


def scene_settings(bpy):
    """The scene's time setup -- the manifest's ``scene`` section, the one part
    of a scene neither intermediate round-trips whole (FBX carries the fps, USD
    the sampled range). Keys mirror ``btk.scene_settings`` / ``mtk.scene_settings``:
    ``fps``, the playback range the timeline plays (``frame_start``/``frame_end``
    -- the preview range when enabled, else the scene range), the full animation
    range (``anim_start``/``anim_end`` = the scene range) and ``frame_current``.
    Dependency-free copy of ``btk.EnvUtils.scene_settings`` (the send direction's
    in-process reader).
    """
    scene = bpy.context.scene
    render = scene.render
    anim = (scene.frame_start, scene.frame_end)
    playback = (
        (scene.frame_preview_start, scene.frame_preview_end)
        if scene.use_preview_range
        else anim
    )
    return {
        "fps": render.fps / (render.fps_base or 1.0),
        "frame_start": playback[0],
        "frame_end": playback[1],
        "anim_start": anim[0],
        "anim_end": anim[1],
        "frame_current": scene.frame_current,
    }


def write_manifest(
    bpy,
    scene,
    materials=None,
    scene_materials=None,
    scene_data=None,
    rig=None,
    visibility=None,
):
    """Sidecar beside the USD carrying what the flat export cannot: instance
    groups, and the scene's time setup (*scene* -- read BEFORE the export, since
    ``_narrow_frame_range`` rewrites the scene's range to the sampled span; the
    stage itself carries the fps and only that narrowed range).

    ALWAYS written for the USD route (empty groups included), so the Maya side
    can tell "no instances" from "sidecar lost" -- it REQUIRES the file. Raises
    on failure; main() then withholds the USD artifact, so the parent's
    judged-by-artifact contract reports a failed conversion instead of shipping
    a payload that would import silently flattened. *scene_data* is
    ``scene_data_sections``' sections (``shots``, ``records``), merged in.
    *visibility* is ``collect_visibility``'s show/hide keys, which neither
    exporter carries; only a scene that keys one writes the section.
    """
    import json

    groups = collect_instance_groups(bpy)
    data = {
        "version": 2,
        "format": "names",
        "instances": groups,
        "empties": collect_empties(bpy),
        # The FBX route's texture manifest: the native UsdPreviewSurface
        # networks are the baseline, but Blender's exporter only writes
        # Principled-direct images (a packed ORM through SeparateColor,
        # node-group plumbing and AO-multiply export as nothing), and
        # Maya's pipeline wants the SHADER_TYPE rebuild, not
        # usdPreviewSurface nodes -- so Maya replays these on top.
        "materials": materials or [],
        "scene_materials": scene_materials or [],
        "scene": scene,
    }
    # Absent = nothing to say; the consumer gates on presence.
    data.update(scene_data or {})
    if rig:  # rig mode only: the graph, its plan and the verify samples
        data["rig"] = rig
    if visibility:  # only scenes that key a show/hide carry the section
        data["visibility"] = visibility
    with open(OUT_USD + ".manifest.json", "w", encoding="utf-8") as fh:
        json.dump(data, fh)
    print(
        "instance manifest: {} group(s) covering {} objects".format(
            len(groups), sum(len(g) for g in groups)
        )
    )


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def scene_data_sections(bpy, spell):
    """The scene's portable records as manifest sections (``shots``,
    ``records``), or ``{}``.

    Neither carrier has a place for a shot, an emissive group's membership or
    any other tool record, so they cross as data and ``mtk.BlenderSceneImport``
    lands them 1:1. blendertk writes them (``DataNodes.transfer_sections`` over
    ``pythontk.RecordTransfer``), names spelled by *spell* as the carrier will
    write them -- the ONE optional toolkit import in this otherwise
    dependency-free script, guarded like the mayapy twins' mayatk pre-passes:
    without blendertk nothing is carried, and a printed line says so.
    """
    _extend_sys_path()
    try:
        from blendertk.node_utils.data_nodes import DataNodes
    except Exception as error:  # noqa: BLE001 -- degrade, never fail the conversion
        print("scene data: blendertk unavailable ({}); not carried.".format(error))
        return {}
    try:
        return DataNodes.transfer_sections(spell=spell) or {}
    except Exception:  # noqa: BLE001
        print("scene data: could not read the scene's records; not carried:")
        traceback.print_exc()
        return {}


def _transfer_rig(bpy, frames):
    """Rig mode (schema 15.2): extract the RigGraph, plan it against the
    CONSUMER's capability (``RIG_CAPABILITY``, sent into this template) and
    sample the built records' targets so the consumer can verify what it builds.
    Returns the manifest's ``rig`` section, or ``{}`` when blendertk is
    unavailable -- printed, never silent. No source-side bake: both Blender
    exporters sample the EVALUATED scene, so what the plan leaves to the bake
    already arrives as keys. Kept dependency-free and IDENTICAL between the FBX
    and USD templates (guarded)."""
    import json

    if not RIG_CAPABILITY:
        print("rig: no consumer capability was sent; nothing to plan against.")
        return {}
    _extend_sys_path()
    try:
        from blendertk.rig_utils.rig_graph_extract import RigGraphExtractor
        from pythontk import RigCapability, RigGraph, RigPlanner
    except Exception as error:
        print(
            "rig: blendertk unavailable ({}); rig logic is not carried.".format(error)
        )
        return {}
    try:
        data = RigGraphExtractor().extract()
        graph = RigGraph.from_dict(data)
        plan = RigPlanner.plan(
            graph, RigCapability.from_dict(json.loads(RIG_CAPABILITY))
        )
    except Exception:
        print("rig: extraction or planning failed; rig logic is not carried.")
        traceback.print_exc()
        return {}
    coverage = graph.coverage()
    print(
        "rig: {} record(s); {} to build, {} node(s) to bake, {} unaccounted driver(s).".format(
            len(data["records"]),
            len(plan.build),
            len(plan.bake),
            coverage["unaccounted"],
        )
    )
    verify_frames = sorted(
        {
            f
            for rid in plan.build
            for f in (plan.verify.get(rid, {}).get("frames") or [])
        }
    )
    if not verify_frames:
        verify_frames = (
            [frames[0], frames[-1]] if frames else [bpy.context.scene.frame_current]
        )
    targets = sorted({i for rid in plan.build for i in graph.record(rid).target_ids()})
    path_of = {n["id"]: n.get("path") for n in data["nodes"]}
    scene = bpy.context.scene
    current = scene.frame_current
    samples = {}
    # A hidden object is not evaluated (its matrix freezes), and rig internals
    # are routinely hidden: sample inside the reveal-and-mute-hide-keys scope.
    sampled = [_world_object(bpy, path_of.get(i))[0] for i in targets]
    try:
        from blendertk.anim_utils._anim_utils import AnimUtils

        with AnimUtils.evaluable_override([o for o in sampled if o is not None]):
            for frame in verify_frames:
                scene.frame_set(int(round(frame)))
                for node_id in targets:
                    point = _world_point(bpy, path_of.get(node_id))
                    if point is not None:
                        samples.setdefault(node_id, {})[str(frame)] = point
    finally:
        scene.frame_set(current)
    return {
        "graph": data,
        "plan": plan.to_dict(),
        "coverage": coverage,
        "verify_samples": samples,
    }


def _world_object(bpy, path):
    """``(object, bone name)`` for the extractor's node *path* -- an object
    name, or ``armature:bone`` -- or ``(None, "")`` when it is gone."""
    if not path:
        return None, ""
    obj = bpy.data.objects.get(path)
    if obj is not None:
        return obj, ""
    name, _sep, bone = path.rpartition(":")
    return bpy.data.objects.get(name), bone


def _world_point(bpy, path):
    """World position of the extractor's node *path* (an object's origin, or a
    pose bone's head), or ``None`` when it is gone."""
    obj, bone = _world_object(bpy, path)
    if obj is None:
        return None
    matrix = obj.matrix_world
    if bone:
        pose_bone = obj.pose.bones.get(bone) if obj.pose else None
        if pose_bone is None:
            return None
        matrix = matrix @ pose_bone.matrix
    return [float(v) for v in matrix.translation]


def _progress(done, total, text):
    """A ``pythontk.ProgressRelay`` marker line, flushed so the parent's footer sees it
    while the conversion runs. Spelled out: the marker protocol needs no import."""
    print("::progress:: {}/{} {}".format(done, total, text), flush=True)


def _exit(code):
    """Leave with an honest status. ``pythontk.ProcessExit`` when importable (it skips
    DLL detach, where a DCC's teardown can fault and file a crash report), else
    ``os._exit`` -- which still beats Blender's exit-0-after-a-script-error default."""
    sys.stdout.flush()
    sys.stderr.flush()
    try:
        from pythontk.core_utils.process_exit import ProcessExit
    except Exception:  # noqa: BLE001 -- the exit must never raise
        os._exit(code)
    ProcessExit.hard_exit(code)


def main():
    import bpy

    _progress(0, 4, "Opening the scene")
    open_source(bpy)
    scene = scene_settings(bpy)  # the author's ranges, before export narrows them
    # Read first too: the sections describe the artist's scene. Names spelled as
    # the exporter writes the prims (the instance section's own spelling).
    scene_data = scene_data_sections(bpy, _sanitize_prim_name)
    # Before the export too, which clears every hide flag for the writer.
    visibility = collect_visibility(bpy)
    _progress(1, 5, "Collecting materials")
    materials, scene_materials = collect_texture_manifest(bpy)
    rig = {}
    if RIG_MODE == "rig":
        # BEFORE the export: it narrows the scene range to the sampled span.
        _progress(2, 5, "Carrying the rig")
        rig = _transfer_rig(bpy, (scene["frame_start"], scene["frame_end"]))
    _progress(3, 5, "Writing the USD")
    export_usd(bpy)
    _progress(4, 5, "Writing the manifest")
    # AFTER the export: the sidecar describes the scene the USD was written
    # from. A failure in either withholds both (`_withhold`): a USD without its
    # sidecar would import silently flattened.
    write_manifest(
        bpy,
        scene,
        materials,
        scene_materials,
        scene_data=scene_data,
        rig=rig,
        visibility=visibility,
    )
    _progress(5, 5, "Converted")


def _withhold(artifact):
    """Remove *artifact* and its sidecar after a failed run: whatever it left
    behind must never pass as the conversion.

    Success is judged by the artifact, and an exporter can fail AFTER opening its
    file -- Maya's USD exporter writes a layer before it refuses a scene
    (measured: a root-level joint), so the partial payload passed, the non-zero exit was
    tolerated as a teardown crash, and the caller reported a missing sidecar in
    place of the exporter's own message. A payload whose sidecar failed is as
    wrong: it imports without what the sidecar rebuilds."""
    for path in (artifact, artifact + ".manifest.json"):
        try:
            os.remove(path)
        except OSError:
            pass


try:
    main()
except Exception:
    traceback.print_exc()
    _withhold(OUT_USD)
    _exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
_exit(0)
