# Blender-scene -> FBX conversion script (Blender -> Maya pull). Generated by BlenderSceneImport -- do not edit by hand.

"""Open a .blend / glTF headlessly (blender --background) and export it as FBX for a Maya import.

The Blender half of ``mtk.BlenderSceneImport.import_scene`` -- the mirror of blendertk's
``templates/_import_scene.py`` (Maya -> Blender pull). Runs under
``blender --background --factory-startup`` via ``pythontk.run_script_to_artifact``,
which judges success by the exported FBX's existence, NOT the exit code (a
``--python`` script that raises does not change Blender's exit code by default,
so the code is doubly meaningless here -- the ``os._exit`` below makes it honest).

No material translation is needed on this side: Blender's FBX exporter reads the
Principled BSDF directly and carries what the classic FBX material model can hold
(base color / normal / emissive maps). Everything else -- metallic, roughness, AO,
and the packed game-engine maps (Metallic_Smoothness / MSAO / ORM) -- has no FBX
slot, so every textured material's ORIGINAL image files are written to a
``.manifest.json`` sidecar; the Maya side rebuilds those materials natively through
the ``GameShader`` engine (the same ``ptk.MapFactory`` classification the Blender
side of the pair uses). Known limit: packed-into-the-.blend images with no on-disk
file resolve to nothing here and surface as a NAMED warning per material on the
Maya side (mirror of the file-less-entry rule), not as silently gray geometry.

A glTF source (.glb/.gltf) is opened by IMPORT into an emptied factory scene instead
(``open_source``) and, since a container holds ALL its images packed, those images are
written out to TEX_DIR first -- so a .glb reaches the manifest with the same on-disk
files a .blend does, and its packed ORM survives the FBX route. Everything after
``open_source`` is identical for both source kinds.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python: no mayatk/blendertk/pythontk imports (only
# Blender's own bundled modules are guaranteed in the child process).
import glob
import json
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_FBX = r"__OUT_FBX__"
EMBED_TEXTURES = __EMBED_TEXTURES__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
TEX_DIR = r"__TEX_DIR__"

# glTF containers the conversion opens by IMPORT rather than by open_mainfile.
_GLTF_EXTENSIONS = (".glb", ".gltf")

# Blender file_format -> the extension its saved file must carry. A glTF's images
# are named without one ("Image_0"), and image.save() picks the encoder from the
# extension, so guessing wrong writes a PNG called .jpg that Maya then misreads.
_IMAGE_EXTENSIONS = {
    "PNG": ".png",
    "JPEG": ".jpg",
    "JPEG2000": ".jp2",
    "TARGA": ".tga",
    "TARGA_RAW": ".tga",
    "TIFF": ".tif",
    "OPEN_EXR": ".exr",
    "OPEN_EXR_MULTILAYER": ".exr",
    "HDR": ".hdr",
    "BMP": ".bmp",
    "WEBP": ".webp",
}


def _image_filename(image, taken, classified=None):
    """A unique, filesystem-safe filename for *image* inside TEX_DIR.

    *classified* is the map-type-bearing stem from _classified_names when the image
    feeds a recognized PBR socket; it is what makes the file classifiable on the
    Maya side. Falling back to the datablock name is deliberate rather than fatal --
    an unrecognized socket then behaves exactly like an oddly-named .blend texture.

    Datablock names are not filenames (a glTF's are often "Image_0", and Blender
    de-duplicates with a ".001" suffix that reads as an extension), and two
    datablocks can collide once sanitized -- so the extension comes from the
    ENCODER and uniqueness is enforced here rather than trusted.
    """
    if classified:
        # Already a stem by construction -- never splitext it. A Blender material
        # named "Mat.001" (the norm for any duplicate) would otherwise have its
        # whole map suffix read as an extension: "Mat.001_Base_Color" -> stem
        # "Mat", written as "Mat.png", which classifies as NOTHING on the Maya
        # side -- silently undoing the rename this function exists to perform.
        stem, ext = classified, ""
    else:
        stem, ext = os.path.splitext(os.path.basename(image.name or "image"))
    stem = re.sub(r"[^A-Za-z0-9_.-]", "_", stem).strip("._") or "image"
    if ext.lower() not in _IMAGE_EXTENSIONS.values():
        ext = _IMAGE_EXTENSIONS.get(image.file_format, ".png")
    name, n = stem + ext, 1
    while name.lower() in taken:
        name, n = "%s_%d%s" % (stem, n, ext), n + 1
    taken.add(name.lower())
    return name


# Principled inputs whose upstream image identifies the map. Both the pre-4.x and
# 4.x+ emission spellings are listed; only the one this Blender has will resolve.
_PBR_SOCKETS = (
    "Base Color",
    "Metallic",
    "Roughness",
    "Normal",
    "Emission Color",
    "Emission",
    "Alpha",
)

# Read off the "glTF Material Output" node group instead of the Principled BSDF --
# see _classified_names.
_GLTF_OUTPUT_SOCKETS = ("Occlusion",)


def _images_feeding(socket, seen=None):
    """Every image datablock upstream of *socket* (through Separate Color, Normal
    Map, Mix, node groups -- whatever the glTF importer wired in between)."""
    found, seen = [], set() if seen is None else seen
    for link in getattr(socket, "links", ()) or ():
        node = link.from_node
        if node in seen:
            continue
        seen.add(node)
        if node.bl_idname == "ShaderNodeTexImage":
            if node.image is not None and node.image not in found:
                found.append(node.image)
            continue
        for inp in node.inputs:
            for image in _images_feeding(inp, seen):
                if image not in found:
                    found.append(image)
    return found


def _map_suffix(sockets):
    """The canonical map-type name for an image feeding *sockets*, or None.

    This is the whole reason the unpack renames rather than reusing datablock
    names: the Maya side classifies a manifest file by FILENAME (the shared
    ptk.MapFactory taxonomy), and a glTF's images are named "Image_0" -- they
    would classify as nothing and every PBR slot would be left empty, which is
    an untextured material with no warning at all. The socket a texture feeds is
    the authoritative signal, and it is only available HERE, in the node tree.
    """
    if "Base Color" in sockets:
        return "Base_Color"
    # ANY two of occlusion/roughness/metallic sharing one image is an ORM: its
    # canonical layout (R=AO, G=Roughness, B=Metallic) is exactly glTF's packing,
    # so this covers occlusionRoughnessMetallic and the metallicRoughness-only
    # and occlusionRoughness subsets alike, without naming a channel that is
    # there after one that is not.
    if len(sockets & {"Metallic", "Roughness", "Occlusion"}) > 1:
        return "ORM"
    if "Metallic" in sockets:
        return "Metallic"
    if "Roughness" in sockets:
        return "Roughness"
    if "Occlusion" in sockets:
        return "Ambient_Occlusion"
    if "Normal" in sockets:
        return "Normal_OpenGL"  # glTF normals are OpenGL-convention by spec
    if sockets & {"Emission Color", "Emission"}:
        return "Emissive"
    if "Alpha" in sockets:
        return "Opacity"
    return None


def _classified_names(bpy):
    """``{image: "<material>_<Map_Type>"}`` for every image on a recognized socket.

    First claim wins when two materials share an image, and it HAS to: an image
    datablock carries exactly one filepath, so one file is all that can be written
    for it. Materials sharing an image in the same role (the norm) all resolve to
    the same map type either way; the pathological cross-role case (base colour in
    one material, roughness in another) is unrepresentable, not merely unhandled.
    """
    names, roles = {}, {}

    def claim(mat_name, socket, role):
        if socket is None:
            return
        for image in _images_feeding(socket):
            roles.setdefault((mat_name, image), set()).add(role)

    for mat in bpy.data.materials:
        tree = getattr(mat, "node_tree", None)
        if tree is None:
            continue
        for node in tree.nodes:
            if node.bl_idname == "ShaderNodeBsdfPrincipled":
                for socket_name in _PBR_SOCKETS:
                    claim(mat.name, node.inputs.get(socket_name), socket_name)
            elif node.bl_idname == "ShaderNodeGroup":
                # Occlusion never reaches the Principled BSDF: the glTF importer
                # hangs it off a "glTF Material Output" group, so a walk of
                # Principled inputs alone is BLIND to a separate AO texture.
                # Blender's own exporter merges occlusion into the roughness
                # image (verified on 5.1), but Substance / Maya glTF exporters
                # ship a standalone one, and it would arrive unclassified.
                if (getattr(node.node_tree, "name", "") or "").startswith("glTF"):
                    for socket_name in _GLTF_OUTPUT_SOCKETS:
                        claim(mat.name, node.inputs.get(socket_name), socket_name)
    for (mat_name, image), sockets in roles.items():
        suffix = _map_suffix(sockets)
        if suffix and image not in names:
            names[image] = "%s_%s" % (mat_name, suffix)
    return names


def _unpack_images(bpy):
    """Write every PACKED image to TEX_DIR and repoint its datablock at the file.

    Load-bearing for a glTF source: the container holds its images, so without this
    every one of them resolves to no on-disk file -- the FBX route would write a
    file-less texture manifest (a NAMED warning and gray materials on the Maya side)
    and the USD route's KEEP texture mode would reference nothing. A .blend needs
    none of it; its images already point at files.

    Each file is named for the MAP TYPE its socket implies (see _map_suffix), not for
    the datablock -- the Maya-side rebuild classifies by filename, and "Image_0" is
    not a classification. An image feeding no recognized socket keeps its datablock
    name and degrades exactly as an oddly-named .blend texture already does.

    TEX_DIR is a persistent, source-keyed dir the Maya side owns (BlenderSceneImport
    ._texture_dir), deliberately NOT the conversion scratch: the intermediate is
    promoted into a cache slot and outlives that scratch, so textures written beside
    it would be swept out from under the payload referencing them.

    Best-effort per image -- one unwritable datablock degrades to the existing
    file-less-entry warning instead of failing the whole conversion.
    """
    if not TEX_DIR:
        return
    os.makedirs(TEX_DIR, exist_ok=True)
    classified = _classified_names(bpy)
    taken, saved = set(), 0
    for image in bpy.data.images:
        if image.packed_file is None:
            continue
        path = os.path.join(
            TEX_DIR, _image_filename(image, taken, classified.get(image))
        )
        try:
            image.filepath_raw = path
            # Unconditional: this runs only on a conversion cache MISS (a full
            # Blender launch), so skipping a write that "looks done" saves nothing
            # measurable and would silently adopt a truncated file left by a
            # killed or half-failed earlier run.
            image.save()
            saved += 1
            print("  unpacked %r -> %s" % (image.name, os.path.basename(path)))
        except Exception as e:
            print("could not unpack image %r: %s" % (image.name, e))
    print("unpacked %d packed image(s) to %s" % (saved, TEX_DIR))


def _import_gltf(bpy):
    """Import SRC_PATH, tolerant of the importer's home moving between versions.

    ``import_scene.gltf`` is the long-standing spelling; Blender's newer file
    handlers register importers under ``wm.*``, so the ``wm.gltf_import`` fallback
    keeps a rename from breaking the pull -- the same per-version tolerance the
    export call applies to its kwargs.
    """
    errors = []
    for name, op in (
        ("import_scene.gltf", getattr(bpy.ops.import_scene, "gltf", None)),
        ("wm.gltf_import", getattr(bpy.ops.wm, "gltf_import", None)),
    ):
        if op is None:
            continue
        try:
            op(filepath=SRC_PATH)
            return
        except Exception as e:
            errors.append("%s: %s" % (name, e))
    raise RuntimeError(
        "no usable glTF importer in this Blender (%s)"
        % ("; ".join(errors) or "none found")
    )


def open_source(bpy):
    """Load SRC_PATH into the conversion session.

    A .blend REPLACES the session (``open_mainfile``). A glTF is *imported* into it,
    so the factory startup scene is emptied first -- ``--factory-startup`` still
    loads the default cube/camera/light, which would otherwise ride the intermediate
    straight into the user's Maya scene. Nothing downstream can tell the two source
    kinds apart after this.
    """
    if os.path.splitext(SRC_PATH)[1].lower() not in _GLTF_EXTENSIONS:
        bpy.ops.wm.open_mainfile(filepath=SRC_PATH, load_ui=False)
        return
    bpy.ops.wm.read_factory_settings(use_empty=True)
    _import_gltf(bpy)
    _unpack_images(bpy)


# Tiled-image filename tokens -> the glob that finds their tiles on disk.
# ``<UDIM>`` is Blender's standard (1001-style); ``<UVTILE>`` the u1_v1 style.
_TILE_TOKENS = (("<UDIM>", "[0-9]" * 4), ("<UVTILE>", "u*_v*"))


def _resolved_image_file(bpy, image):
    """Absolute on-disk path of *image*, or None (packed-only / missing / generated).

    UDIM/UVTILE sets resolve to their lowest-numbered existing tile: neither FBX
    nor the manifest's per-file classification has a tiling concept, so one real
    tile (logged as flattened) beats an unresolvable ``<UDIM>`` token that would
    otherwise surface as a misleading "packed or needs relinking" warning.
    """
    if image is None:
        return None
    try:
        path = bpy.path.abspath(image.filepath, library=image.library)
    except Exception:
        return None
    if not path:
        return None
    path = os.path.abspath(path)
    for token, pattern in _TILE_TOKENS:
        if token in path:
            # glob.escape the literal parts only -- the path itself may hold
            # glob-special chars ([ ] * ?); the token survives escaping intact.
            tiles = sorted(glob.glob(glob.escape(path).replace(token, pattern)))
            if tiles:
                print("tiled image flattened to its first tile: " + tiles[0])
                return tiles[0]
            return None
    return path if os.path.isfile(path) else None


def _material_files(bpy, mat):
    """(files, image_node_count) -- every image-texture file feeding *mat*.

    Free-form walk of the whole node tree (node groups included), matching the
    Maya-side history walk: the manifest carries EVERYTHING; classification into
    map types happens Maya-side via the shared filename taxonomy.
    """
    files = []
    node_count = 0

    def walk(tree, seen):
        nonlocal node_count
        if tree is None or tree in seen:
            return
        seen.add(tree)
        for node in tree.nodes:
            if node.bl_idname == "ShaderNodeTexImage":
                if node.image is not None:
                    node_count += 1
                path = _resolved_image_file(bpy, node.image)
                if path and path not in files:
                    files.append(path)
            elif node.bl_idname == "ShaderNodeGroup":
                walk(node.node_tree, seen)

    walk(mat.node_tree if mat.use_nodes else None, set())
    return files, node_count


def collect_texture_manifest(bpy):
    """Manifest entries for every textured material on an exportable object,
    plus the full list of scene-material names (returned as a pair).

    One entry per material (Blender shares material datablocks natively -- the
    Maya-side memoization problem cannot arise here); ``objects`` merges every
    user so the Maya side has an object-level fallback when the FBX importer
    renames materials. Materials with no image nodes are skipped (their flat
    colors ride the FBX fine); materials whose image nodes all failed to resolve
    to disk files are written file-less so the Maya side warns BY NAME.
    """
    entries = []
    by_material = {}
    # EVERY material name on an exportable object, textured or not. The Maya
    # side excludes these exact spellings from its rename-on-clash suffix
    # match: an untextured "Mat2" alongside textured "Mat" must never be
    # claimed as "Mat renamed to Mat2".
    scene_materials = []
    # The ACTIVE scene's objects only -- the FBX exporter exports exactly that
    # set, and bpy.data.objects would drag in other scenes / unlinked objects,
    # producing entries nothing Maya-side can ever match.
    for obj in bpy.context.scene.objects:
        if obj.type != "MESH":
            continue
        for slot in obj.material_slots:
            mat = slot.material
            if mat is None:
                continue
            if mat.name not in scene_materials:
                scene_materials.append(mat.name)
            if mat.name in by_material:
                entry = by_material[mat.name]
                if obj.name not in entry["objects"]:
                    entry["objects"].append(obj.name)
                continue
            files, image_nodes = _material_files(bpy, mat)
            if image_nodes == 0:
                continue
            entry = {
                "name": mat.name,
                "shader_type": "principled_bsdf",
                "fbx_material": mat.name,
                "objects": [obj.name],
                "files": files,
            }
            by_material[mat.name] = entry
            entries.append(entry)
            print(
                "manifest: {} ({} texture file(s) resolved of {} image node(s))".format(
                    mat.name, len(files), image_nodes
                )
            )
    return entries, scene_materials


def collect_empties(bpy):
    """``[{name, display_type}, ...]`` for the scene's Empties (node-type sidecar).

    FBX cannot say what an Empty was: every null becomes a Maya locator on
    import, and the children-based repair alone demotes EVERY parent to a
    plain group -- including locators that legitimately parent geometry. The
    display type carries the author's intent (non-default = deliberate
    marker -> stays a locator); a ``maya_node_type`` custom property (stamped
    on round-tripped scenes) overrides both. Mirror of
    ``btk.MayaBridge._manifest_empties`` (the send direction's collector).
    """
    empties = []
    for obj in bpy.context.scene.objects:
        if obj.type != "EMPTY":
            continue
        entry = {"name": obj.name, "display_type": obj.empty_display_type}
        node_type = obj.get("maya_node_type")
        if node_type:
            entry["maya_node_type"] = str(node_type)
        empties.append(entry)
    return empties


def scene_settings(bpy):
    """The scene's time setup -- the manifest's ``scene`` section, the one part
    of a scene neither intermediate round-trips whole (FBX carries the fps, USD
    the sampled range). Keys mirror ``btk.scene_settings`` / ``mtk.scene_settings``:
    ``fps``, the playback range the timeline plays (``frame_start``/``frame_end``
    -- the preview range when enabled, else the scene range), the full animation
    range (``anim_start``/``anim_end`` = the scene range) and ``frame_current``.
    Dependency-free copy of ``btk.EnvUtils.scene_settings`` (the send direction's
    in-process reader).
    """
    scene = bpy.context.scene
    render = scene.render
    anim = (scene.frame_start, scene.frame_end)
    playback = (
        (scene.frame_preview_start, scene.frame_preview_end)
        if scene.use_preview_range
        else anim
    )
    return {
        "fps": render.fps / (render.fps_base or 1.0),
        "frame_start": playback[0],
        "frame_end": playback[1],
        "anim_start": anim[0],
        "anim_end": anim[1],
        "frame_current": scene.frame_current,
    }


def write_texture_manifest(entries, scene_materials, empties, scene, path):
    """Sidecar for what FBX cannot carry, consumed by BlenderSceneImport:
    materials / empties, and ``scene`` = the time setup (fps / ranges / current
    frame -- Maya's FBX importer leaves the scene's clock alone). Always
    written: every scene has a time setup.

    File-less entries are written too: a textured material whose image paths
    never resolved (packed-only, or broken links) must surface as a NAMED
    warning on the Maya side, not as silently gray geometry (the rule the
    Maya->Blender direction learned from a live production report).
    """
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(
            {
                "version": 1,
                "materials": entries,
                "scene_materials": scene_materials,
                "empties": empties,
                "scene": scene,
            },
            fh,
            indent=1,
        )


def export_fbx(bpy):
    """Full-fidelity FBX export with per-flag tolerance across Blender versions.

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in a future exporter is dropped and the call
    retried -- the mirror of the Maya template's per-flag MEL tolerance.
    ``path_mode='ABSOLUTE'`` is the load-bearing default: the FBX lives in the
    temp dir, so relative texture paths would be unresolvable in Maya (the same
    pink-materials failure the Maya side fixed via workspace resolution).
    """
    kwargs = {
        "filepath": OUT_FBX,
        "path_mode": "COPY" if EMBED_TEXTURES else "ABSOLUTE",
        "embed_textures": EMBED_TEXTURES,
        "use_mesh_modifiers": True,
        "use_tspace": True,  # tangents/binormals (needs UVs; warns, never fails)
        "use_custom_props": True,
        "add_leaf_bones": False,  # no Maya-side "_end" joint pollution
        "bake_anim": INCLUDE_ANIMATION,
        # ONE scene-range AnimStack with ABSOLUTE times. Both multi-stack modes are
        # the exporter's defaults, and either writes one start-ZEROED stack per
        # action instead -- measured: a clip keyed at Blender 10-90 landed in Maya
        # at 0-80. The same rule blendertk's FbxUtils.export / Scene Exporter apply.
        "bake_anim_use_nla_strips": False,
        "bake_anim_use_all_actions": False,
    }
    while True:
        try:
            bpy.ops.export_scene.fbx(**kwargs)
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs:
                print("FBX kwarg skipped (unsupported by this exporter): " + key)
                del kwargs[key]
                continue
            raise


def main():
    import bpy

    open_source(bpy)
    manifest_entries, scene_materials = collect_texture_manifest(bpy)
    empties = collect_empties(bpy)
    export_fbx(bpy)
    # Written only after a successful export (a manifest implies its FBX).
    write_texture_manifest(
        manifest_entries,
        scene_materials,
        empties,
        scene_settings(bpy),
        OUT_FBX + ".manifest.json",
    )


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
