# Blender-scene -> FBX conversion script (Blender -> Maya pull). Generated by BlenderSceneImport -- do not edit by hand.

"""Open a .blend headlessly (blender --background) and export it as FBX for a Maya import.

The Blender half of ``mtk.import_blender_scene`` -- the mirror of blendertk's
``templates/_import_scene.py`` (Maya -> Blender pull). Runs under
``blender --background --factory-startup`` via ``pythontk.run_script_to_artifact``,
which judges success by the exported FBX's existence, NOT the exit code (a
``--python`` script that raises does not change Blender's exit code by default,
so the code is doubly meaningless here -- the ``os._exit`` below makes it honest).

No material translation is needed on this side: Blender's FBX exporter reads the
Principled BSDF directly and carries what the classic FBX material model can hold
(base color / normal / emissive maps). Everything else -- metallic, roughness, AO,
and the packed game-engine maps (Metallic_Smoothness / MSAO / ORM) -- has no FBX
slot, so every textured material's ORIGINAL image files are written to a
``.manifest.json`` sidecar; the Maya side rebuilds those materials natively through
the ``GameShader`` engine (the same ``ptk.MapFactory`` classification the Blender
side of the pair uses). Known limit: packed-into-the-.blend images with no on-disk
file resolve to nothing here and surface as a NAMED warning per material on the
Maya side (mirror of the file-less-entry rule), not as silently gray geometry.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to the pull engine).
"""

# Dependency-free Blender Python: no mayatk/blendertk/pythontk imports (only
# Blender's own bundled modules are guaranteed in the child process).
import json
import os
import re
import sys
import traceback

SRC_PATH = r"__SRC_PATH__"
OUT_FBX = r"__OUT_FBX__"
EMBED_TEXTURES = __EMBED_TEXTURES__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def _resolved_image_file(bpy, image):
    """Absolute on-disk path of *image*, or None (packed-only / missing / generated)."""
    if image is None:
        return None
    try:
        path = bpy.path.abspath(image.filepath, library=image.library)
    except Exception:
        return None
    if not path:
        return None
    path = os.path.abspath(path)
    return path if os.path.isfile(path) else None


def _material_files(bpy, mat):
    """(files, image_node_count) -- every image-texture file feeding *mat*.

    Free-form walk of the whole node tree (node groups included), matching the
    Maya-side history walk: the manifest carries EVERYTHING; classification into
    map types happens Maya-side via the shared filename taxonomy.
    """
    files = []
    node_count = 0

    def walk(tree, seen):
        nonlocal node_count
        if tree is None or tree in seen:
            return
        seen.add(tree)
        for node in tree.nodes:
            if node.bl_idname == "ShaderNodeTexImage":
                if node.image is not None:
                    node_count += 1
                path = _resolved_image_file(bpy, node.image)
                if path and path not in files:
                    files.append(path)
            elif node.bl_idname == "ShaderNodeGroup":
                walk(node.node_tree, seen)

    walk(mat.node_tree if mat.use_nodes else None, set())
    return files, node_count


def collect_texture_manifest(bpy):
    """Manifest entries for every textured material on an exportable object,
    plus the full list of scene-material names (returned as a pair).

    One entry per material (Blender shares material datablocks natively -- the
    Maya-side memoization problem cannot arise here); ``objects`` merges every
    user so the Maya side has an object-level fallback when the FBX importer
    renames materials. Materials with no image nodes are skipped (their flat
    colors ride the FBX fine); materials whose image nodes all failed to resolve
    to disk files are written file-less so the Maya side warns BY NAME.
    """
    entries = []
    by_material = {}
    # EVERY material name on an exportable object, textured or not. The Maya
    # side excludes these exact spellings from its rename-on-clash suffix
    # match: an untextured "Mat2" alongside textured "Mat" must never be
    # claimed as "Mat renamed to Mat2".
    scene_materials = []
    # The ACTIVE scene's objects only -- the FBX exporter exports exactly that
    # set, and bpy.data.objects would drag in other scenes / unlinked objects,
    # producing entries nothing Maya-side can ever match.
    for obj in bpy.context.scene.objects:
        if obj.type != "MESH":
            continue
        for slot in obj.material_slots:
            mat = slot.material
            if mat is None:
                continue
            if mat.name not in scene_materials:
                scene_materials.append(mat.name)
            if mat.name in by_material:
                entry = by_material[mat.name]
                if obj.name not in entry["objects"]:
                    entry["objects"].append(obj.name)
                continue
            files, image_nodes = _material_files(bpy, mat)
            if image_nodes == 0:
                continue
            entry = {
                "name": mat.name,
                "shader_type": "principled_bsdf",
                "fbx_material": mat.name,
                "objects": [obj.name],
                "files": files,
            }
            by_material[mat.name] = entry
            entries.append(entry)
            print(
                "manifest: {} ({} texture file(s) resolved of {} image node(s))".format(
                    mat.name, len(files), image_nodes
                )
            )
    return entries, scene_materials


def write_texture_manifest(entries, scene_materials, path):
    """Sidecar for the textures FBX cannot carry, consumed by BlenderSceneImport.

    File-less entries are written too: a textured material whose image paths
    never resolved (packed-only, or broken links) must surface as a NAMED
    warning on the Maya side, not as silently gray geometry (the rule the
    Maya->Blender direction learned from a live production report).
    """
    if not entries:
        return
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(
            {"version": 1, "materials": entries, "scene_materials": scene_materials},
            fh,
            indent=1,
        )


def export_fbx(bpy):
    """Full-fidelity FBX export with per-flag tolerance across Blender versions.

    ``bpy.ops`` rejects the whole call on one unknown keyword (TypeError), so a
    renamed/removed parameter in a future exporter is dropped and the call
    retried -- the mirror of the Maya template's per-flag MEL tolerance.
    ``path_mode='ABSOLUTE'`` is the load-bearing default: the FBX lives in the
    temp dir, so relative texture paths would be unresolvable in Maya (the same
    pink-materials failure the Maya side fixed via workspace resolution).
    """
    kwargs = {
        "filepath": OUT_FBX,
        "path_mode": "COPY" if EMBED_TEXTURES else "ABSOLUTE",
        "embed_textures": EMBED_TEXTURES,
        "use_mesh_modifiers": True,
        "use_tspace": True,  # tangents/binormals (needs UVs; warns, never fails)
        "use_custom_props": True,
        "add_leaf_bones": False,  # no Maya-side "_end" joint pollution
        "bake_anim": INCLUDE_ANIMATION,
    }
    while True:
        try:
            bpy.ops.export_scene.fbx(**kwargs)
            return
        except TypeError as e:
            match = re.search(r'"(\w+)"', str(e))
            key = match.group(1) if match else None
            if key and key in kwargs:
                print("FBX kwarg skipped (unsupported by this exporter): " + key)
                del kwargs[key]
                continue
            raise


def main():
    import bpy

    bpy.ops.wm.open_mainfile(filepath=SRC_PATH, load_ui=False)
    manifest_entries, scene_materials = collect_texture_manifest(bpy)
    export_fbx(bpy)
    # Written only after a successful export (a manifest implies its FBX).
    write_texture_manifest(manifest_entries, scene_materials, OUT_FBX + ".manifest.json")


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked
# by Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
