# Maya selection -> .blend save script (Maya -> Blender). Generated by BlenderBridge -- do not edit by hand.

"""Import the bridged FBX into a headless Blender and save it as a ``.blend``.

The ``save_as`` half of the Maya->Blender hand-off: same FBX payload and same
``.manifest.json`` sidecar the interactive ``import`` template consumes, but delivered to
``blender --background`` so the Maya artist ends up with a real ``.blend`` on disk instead
of an open Blender session. Nothing here re-implements the send -- ``BlenderBridge``
produces the payload exactly once, for both modes.

Runs under ``blender --background --factory-startup --python`` via
:class:`pythontk.ScriptRunDeliverer` (which wraps ``run_script_to_artifact``), so success
is judged by the saved ``.blend``'s existence, NOT the exit code: a ``--python`` script
that raises does not change Blender's exit code by default -- the ``os._exit`` below makes
it honest.

The save starts from an EMPTY factory scene (``read_factory_settings(use_empty=True)``):
the startup cube/camera/light must not land in a file the artist thinks contains only
their selection. Mirror of blendertk's ``templates/_bake_scene.py`` (which writes the same
kind of artifact for the reference cache) and of blendertk's own ``_save_scene.py`` running
the other direction.

Materials: the FBX is not lossy at the format level, but Blender's importer discards
Maya's ``Maya|TEX_*`` bindings by design, so textured materials arrive unshaded (see
``import.py`` for the full finding). The sidecar carries each material's ORIGINAL image
files and is replayed through the ONE existing applier,
``blendertk.MayaSceneImport._apply_texture_manifest`` -- the established
template->paired-engine contract. Without blendertk importable in the child, the FBX's
classic-model materials are kept and a console line says so.

Known limit (shared with the interactive send): with ``EMBED_TEXTURES`` on, images the
manifest does NOT cover stay unpacked in the FBX's temp ``.fbm`` sidecar dir, which is
swept eventually -- ``make_paths_absolute`` below keeps them resolvable until then, and
the manifest is what makes the textured materials permanent.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to ``BlenderBridge.save_as``).
"""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("save_as",)

# Dependency-free Blender Python at module scope: only Blender's own bundled modules are
# guaranteed in the child. blendertk is imported OPTIONALLY, inside the manifest step.
import os
import sys
import traceback

import bpy

FBX_PATH = r"__FBX_PATH__"
OUT_FILE = r"__OUT_FILE__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores
# PYTHONPATH, so without these the manifest replay below can never import.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def apply_texture_manifest(new_objects):
    """Replay the sidecar manifest through blendertk's applier (see module docstring)."""
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    _extend_sys_path()
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport
    except Exception as error:
        print(
            "blendertk unavailable ({}); keeping the FBX-carried materials.".format(
                error
            )
        )
        return
    try:
        # Node-type tags first (cheap, structural): a ``maya_node_type`` custom
        # property on each Empty that was a Maya group/locator, so a later send
        # BACK to Maya restores the correct node type.
        MayaSceneImport._tag_maya_node_types(manifest, new_objects)
    except Exception:
        print("Node-type tagging failed; skipped:")
        traceback.print_exc()
    try:
        MayaSceneImport(log_level="WARNING")._apply_texture_manifest(
            manifest, new_objects
        )
    except Exception:
        print("Texture-manifest rebuild failed; keeping FBX materials:")
        traceback.print_exc()


def main():
    # Empty scene: the factory startup cube/camera/light must not enter the saved file.
    bpy.ops.wm.read_factory_settings(use_empty=True)

    before = set(bpy.data.objects)
    # global_scale 1.0 honors Blender's cm->m unit conversion of the Maya FBX; 100.0
    # cancels it (preserves the raw numeric values) when the user opts out. Same call
    # the interactive import template makes -- one import recipe, two deliveries.
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )
    new = [o for o in bpy.data.objects if o not in before]
    apply_texture_manifest(new)

    # Absolute image paths: the payload FBX lives in TEMP, so anything left relative to
    # it would be unresolvable the moment the .blend is opened from elsewhere.
    try:
        bpy.ops.file.make_paths_absolute()
    except Exception:
        print("make_paths_absolute skipped:")
        traceback.print_exc()

    bpy.ops.wm.save_as_mainfile(
        filepath=OUT_FILE, check_existing=False, relative_remap=False
    )
    print("Saved {} object(s) into {}".format(len(new), OUT_FILE))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked by
# Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
