# Maya selection -> .blend save script (Maya -> Blender). Generated by BlenderBridge -- do not edit by hand.

"""Import the bridged FBX into a headless Blender and save it as a ``.blend``.

The ``save_as`` half of the Maya->Blender hand-off: same FBX payload and same
``.manifest.json`` sidecar the interactive ``import`` template consumes, but delivered to
``blender --background`` so the Maya artist ends up with a real ``.blend`` on disk instead
of an open Blender session. Nothing here re-implements the send -- ``BlenderBridge``
produces the payload exactly once, for both modes.

Runs under ``blender --background --factory-startup --python`` via
:class:`pythontk.ScriptRunDeliverer` (which wraps ``run_script_to_artifact``), so success
is judged by the saved ``.blend``'s existence, NOT the exit code: a ``--python`` script
that raises does not change Blender's exit code by default -- the ``os._exit`` below makes
it honest.

The save starts from an EMPTY factory scene (``read_factory_settings(use_empty=True)``):
the startup cube/camera/light must not land in a file the artist thinks contains only
their selection. Mirror of blendertk's ``templates/_bake_scene.py`` (which writes the same
kind of artifact for the reference cache) and of blendertk's own ``_save_scene.py`` running
the other direction.

Materials: the FBX is not lossy at the format level, but Blender's importer discards
Maya's ``Maya|TEX_*`` bindings by design, so textured materials arrive unshaded (see
``import.py`` for the full finding). The sidecar carries each material's ORIGINAL image
files and is replayed through the ONE existing applier,
``blendertk.MayaSceneImport._apply_texture_manifest`` -- the established
template->paired-engine contract. Without blendertk importable in the child, the FBX's
classic-model materials are kept and a console line says so.

Known limit (shared with the interactive send): with ``EMBED_TEXTURES`` on, images the
manifest does NOT cover stay unpacked in the FBX's temp ``.fbm`` sidecar dir, which is
swept eventually -- ``make_paths_absolute`` below keeps them resolvable until then, and
the manifest is what makes the textured materials permanent.

Underscore-prefixed: hidden from the bridge panel's template list (this is not a
user-pickable send recipe; it belongs to ``BlenderBridge.save_as``).
"""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("save_as",)

# Dependency-free Blender Python at module scope: only Blender's own bundled modules are
# guaranteed in the child. blendertk is imported OPTIONALLY, inside the manifest step.
import os
import sys
import traceback

import bpy

# The payload: FBX or USD, routed on the extension by the consumer (the interactive
# ``import`` template makes the identical call -- a drift test pins the two).
FBX_PATH = r"__PAYLOAD_PATH__"
USD_EXTENSIONS = (".usd", ".usda", ".usdc", ".usdz")
OUT_FILE = r"__OUT_FILE__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores
# PYTHONPATH, so without these the manifest replay below can never import.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


# The send's own FBX import settings, over the consumer's defaults: the Maya->Blender send
# has always kept leaf bones and the authored bone orientation, and the pull direction's
# bone handling is not this recipe's to change.
SEND_FBX_OPTIONS = {
    "use_anim": INCLUDE_ANIMATION,
    "use_image_search": True,
    "use_custom_normals": True,
    # 1.0 honors Blender's cm->m unit conversion of the Maya FBX; 100.0 cancels it
    # (preserves the raw numeric values) when the user opts out of unit scaling.
    "global_scale": 1.0 if APPLY_UNIT_SCALE else 100.0,
    "ignore_leaf_bones": False,
    "automatic_bone_orientation": False,
}


def import_payload():
    """Import the payload (FBX or USD) and apply its manifest; return the new objects.

    Through ``blendertk.MayaSceneImport.import_payload``, the ONE consumer every Maya
    payload goes through -- this template, its save_as / interactive twin, and blendertk's
    own pull (the scene import and the Reference Manager's .blend bake) -- so each manifest
    section (group / locator identity, textures, lights, a USD payload's owned animation
    and stripped materials scope) replays the same way wherever a Maya scene enters
    Blender. Without blendertk on this Blender the bare importer runs and the payload
    carries only what its format does (a console line says so).
    """
    _extend_sys_path()
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport
    except Exception as error:
        print("blendertk unavailable ({}); importing the payload bare.".format(error))
        before = set(bpy.data.objects)
        if FBX_PATH.lower().endswith(USD_EXTENSIONS):
            bpy.ops.wm.usd_import(
                filepath=FBX_PATH, import_visible_only=False, merge_parent_xform=False
            )
        else:
            bpy.ops.import_scene.fbx(filepath=FBX_PATH, **SEND_FBX_OPTIONS)
        return [o for o in bpy.data.objects if o not in before]
    return MayaSceneImport(log_level="WARNING").import_payload(
        FBX_PATH,
        fbx_options=SEND_FBX_OPTIONS,
        usd_options={"apply_unit_conversion_scale": bool(APPLY_UNIT_SCALE)},
        reduce_keys=False,
    )


def main():
    # Empty scene: the factory startup cube/camera/light must not enter the saved file.
    bpy.ops.wm.read_factory_settings(use_empty=True)

    new = import_payload()

    # Absolute image paths: the payload FBX lives in TEMP, so anything left relative to
    # it would be unresolvable the moment the .blend is opened from elsewhere.
    try:
        bpy.ops.file.make_paths_absolute()
    except Exception:
        print("make_paths_absolute skipped:")
        traceback.print_exc()

    bpy.ops.wm.save_as_mainfile(
        filepath=OUT_FILE, check_existing=False, relative_remap=False
    )
    print("Saved {} object(s) into {}".format(len(new), OUT_FILE))


try:
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked by
# Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
