# Maya selection -> Cycles lightmap bake -> back into the Maya scene. Generated by BlenderBridge -- do not edit by hand.

"""Bake the bridged Maya selection's lightmaps in a headless Blender; return them to Maya.

The send-to-bake operation: the same FBX payload and ``.manifest.json`` sidecar every
Blender hand-off uses, delivered to ``blender --background``, which rebuilds the materials,
lights the scene, and runs blendertk's :class:`LightmapBaker` -- generate + pack the
lightmap UVs, bake, denoise, atlas-by-material. What comes back is **scene state, not a
deliverable**: the HDR EXRs (the finished maps only, written into the Maya project's own
texture folder -- everything the bake produces on the way there is staged in a tracked temp
dir) and this script's artifact, a small JSON manifest carrying each object's map + the
exact per-loop UV layout it was baked through, itself written to tracked temp storage since
Maya reads it once and never again. The Maya side writes those UVs onto its meshes and commits the
maps alongside the existing materials -- after which **every** export path ships the bake
with no knowledge of it: FBX -> Unity (the ``lightmap_metadata`` carrier) and GLB -> web
(``ptk.MeshConvert`` reads the same manifest back out of the GLB). The bake targets no
platform; the exporters do. The Maya viewport shows nothing, by design: the commit builds
no file node, so what lands in the scene is the lightmap UV set on channel 1 plus a marker
per transform -- the map itself is inspected on disk or in a viewer.

**Instances are first-class.** Instancing survives the crossing *intact* -- Maya exports
it (``FBXExportInstances``, pinned on by the bridge) and Blender imports linked duplicates
sharing one mesh datablock, both probe-measured. Each instance is baked SEPARATELY (each
stands somewhere different and receives different light) into its own rect of the material
group's atlas, while the mesh keeps ONE shared [0,1] lightmap unwrap. The rect rides the
manifest as the per-instance binding -- Unity's native ``Renderer.lightmapScaleOffset``
model -- and is never folded into the shared UVs, which is the one place per-instance
data cannot survive: a rect written into UVs all copies share is wrong for every copy
but one.

**Why Blender rather than Maya's own LightmapBaker**: Cycles bakes white-card irradiance
natively (``DIFFUSE`` minus the colour pass), needs no Arnold licence, denoises the result,
and runs on the GPU. mayatk's Arnold baker remains the Maya-native path.

**Blender owns the whole lightmap job, UVs included.** A layout generated here exists in
Maya only because it is handed back whole -- per LOOP (face-vertex), which survives the
FBX crossing exactly (probe-verified: quads, tris and n-gons all keep their
per-face-vertex sequence with triangulation off) -- and it travels ONCE per unique mesh
(instances share it), keyed through each object's ``mesh`` reference. The atlas rect
travels separately, per instance.

**Lighting -- two composable sources, both under the artist's control.**

1. ``INCLUDE_LIGHTS`` (default on) brings the **Maya lights inside the sent
   selection** across, so the bake is of the lighting the artist actually built.
   Selection-scoped by design -- a light grouped outside the sent hierarchy does
   not travel, exactly like a mesh outside it. The lights that cross travel as
   manifest DATA rather than as FBX lights -- see :func:`rebuild_scene_lights`, which also
   explains why the light's aim has to travel with it -- and their power is
   rebalanced by ``SCENE_LIGHT_STRENGTH``, because Maya intensity is unitless and no
   exact conversion to watts exists. Relative brightnesses survive; the overall level
   is the dial. The bake summary reports each light's final wattage per light, so
   that dial is tuned from a number rather than a guess.
2. ``ENVIRONMENT_HDR`` (+ ``WORLD_STRENGTH``) -- an equirect world.

Light-fixture geometry is deliberately NOT a third source. Turning fixture meshes
into lights is an authoring act, not a bake option: ``mayatk``'s
``LightUtils.lights_from_geometry`` (tentacle Lighting panel) builds ordinary,
artist-owned Maya area lights from that geometry once, in the scene -- and from then
on they cross as source 1 like every other light. Baking is rendering; it creates
nothing.

Ambient and volume lights have no Cycles equivalent and are skipped rather than
approximated, and a StingrayPBS IBL is not a light object at all -- a scene lit only
by those needs real lights or source 2, and says so in the log rather than baking
silently black. An emissive *map* is deliberately not a light source either: it is an
appearance that makes a fixture read as switched-on, and baking from it would tie the
room's illumination to a texture's exposure. ``EMISSION_STRENGTH`` only keeps that
glow looking right alongside the real lights.

Runs via :class:`pythontk.ScriptRunDeliverer`, so success is judged by the written
manifest, not the exit code -- hence the ``os._exit`` below. blendertk is **required**: a
lightmap bake without the baker is not a degraded result, it is no result.

User-visible (no underscore), so it appears in the bridge panel's template dropdown as
``bake_lightmaps (round_trip)``. The mode names what the operation IS -- a send-to-bake
round trip, the scene comes back lit -- not the mechanics it happens to share with
``save_as`` (run headlessly, blocking, judged by ONE written artifact; both modes ride
the bridge's one blocking spec and the same :class:`pythontk.ScriptRunDeliverer`). The
distinction that matters to the artist is where the artifact GOES: ``save_as`` hands
them a file, this hands the manifest to the bridge's ``_ingest`` hook -- keyed off the
artifact's suffix -- and leaves no deliverable at all. Labelling that ``save_as`` in a
dropdown sends them looking for one.

``round_trip`` covers two artifact shapes, and this is the second: RizomUV's has the
target rewrite the exported payload in place (success = the file CHANGED), while here
the manifest is a NEW file. The deliverer registered for the mode settles that; the mode
itself only promises the result lands back in the host.

It declares its output ``auto`` for the same reason: the artifact is pipeline plumbing,
so the panel derives where it goes instead of asking the artist to name a file they will
never open. Also callable headlessly as :meth:`~mayatk.BlenderBridge.bake_lightmaps`.

(Prose in this file is substituted too -- naming a token in a sentence would replace it
with the rendered value and leave a stray temp path in the generated script's docstring.)
"""

# Bridge metadata -- consumed by BlenderBridge before substitution. The mode string is
# the ecosystem-wide vocabulary from ``pythontk.core_utils.script_template`` (SEND_TO /
# SAVE_AS / ROUND_TRIP); it is read STRICTLY here (ScriptRunDeliverer.strict_modes), so a
# spelling outside that set aborts the run in preflight rather than degrading.
BRIDGE_MODES = ("round_trip",)
# The artifact: the return manifest itself (maps + UV layouts), not a scene or a mesh file.
# The compound suffix is load-bearing, not decoration -- the bridge triggers its reassembly
# step on an artifact NAMED this way, which is what keeps that step template-agnostic
# (BlenderBridge.RETURN_MANIFEST_SUFFIX; a test pins the two equal). The bridge validates
# on the final extension, so ".json" still has to be in its save_extensions.
BRIDGE_OUTPUT_EXT = (".lightmaps.json",)
# The output path is DERIVED (tracked temp storage, named after the scene), never prompted
# for -- the manifest is how the bake gets home, not something an artist names or keeps.
# Only the MAPS are a project artifact; see LIGHTMAP_DIR.
BRIDGE_OUTPUT = ("auto",)
# Seconds before the run is abandoned. The shared default is 600, which is SHORTER than a
# real bake: 7 objects at 512 samples / 1024px measured ~13 min, and samples scale it
# without limit. A bake killed mid-run leaves no artifact and reads as a silent failure,
# so this is deliberately generous -- it is a runaway guard, not a schedule.
BRIDGE_TIMEOUT = ("10800",)

# Dependency-free Blender Python at module scope: only Blender's own bundled modules are
# guaranteed here. blendertk is imported inside main(), after EXTRA_SYS_PATH is applied.
import json
import os
import sys
import traceback

import bpy

# Bridge-injected tokens (NOT registered parameters) arrive as raw strings, so they are
# quoted here. Everything below them IS a registered parameter and arrives already
# rendered as a Python literal by ``Formatters.python_literal`` -- so those tokens must
# stay BARE. Quoting a registered string would yield the literal ``"'separated'"``, and
# every mode comparison in this file would silently fail.
FBX_PATH = r"__FBX_PATH__"
OUT_FILE = r"__OUT_FILE__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores PYTHONPATH,
# so without these nothing below can import.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__

# Quality: a named preset (blendertk's LightmapBaker.preset_store) sets resolution +
# samples; the explicit values below override it when non-zero (API power users).
LIGHTMAP_QUALITY = __LIGHTMAP_QUALITY__
LIGHTMAP_RESOLUTION = __LIGHTMAP_RESOLUTION__
LIGHTMAP_SAMPLES = __LIGHTMAP_SAMPLES__
LIGHTMAP_DENOISE = __LIGHTMAP_DENOISE__
LIGHTMAP_DEVICE = __LIGHTMAP_DEVICE__

ENVIRONMENT_HDR = __ENVIRONMENT_HDR__
WORLD_STRENGTH = __WORLD_STRENGTH__
EMISSION_STRENGTH = __EMISSION_STRENGTH__
# The scene's own Maya lights: sidecarred = __INCLUDE_LIGHTS__ (the Maya side decides
# whether to WRITE the records; this side rebuilds them and rebalances the result).
SCENE_LIGHT_STRENGTH = __SCENE_LIGHT_STRENGTH__

# Where the FINISHED HDR (EXR) lightmaps land. Empty -> next to the manifest. The bridge
# points this at the Maya project's sourceimages so the returned maps live where that
# scene's materials (and its exporters) expect textures. Only finished maps are written
# here: the per-object tiles an atlas consolidates are staged in a tracked temp dir by
# ``LightmapBaker.bake_atlas`` and never touch the project.
LIGHTMAP_DIR = __LIGHTMAP_DIR__

# v2: per-instance ``rect`` bindings + layouts deduped per unique mesh (``meshes`` section).
# An older mayatk refuses a v2 manifest cleanly via its version gate.
RETURN_MANIFEST_VERSION = 2


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def apply_texture_manifest(new_objects):
    """Replay the sidecar through blendertk's applier.

    Not optional here the way it is for a plain import: a lightmap bakes the *materials'*
    response to light, so an unshaded (grey) import would bake a grey room. A missing
    sidecar is still tolerated (a flat-coloured scene bakes fine); a present-but-failing
    one is logged loudly.
    """
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        print("No texture manifest; baking the FBX-carried materials.")
        return
    from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

    try:
        MayaSceneImport._tag_maya_node_types(manifest, new_objects)
    except Exception:
        print("Node-type tagging failed; skipped:")
        traceback.print_exc()
    try:
        MayaSceneImport(log_level="WARNING")._apply_texture_manifest(
            manifest, new_objects
        )
    except Exception:
        print("Texture-manifest rebuild failed; baking FBX materials:")
        traceback.print_exc()


def rebuild_scene_lights():
    """Replay the manifest's light records through blendertk's applier.

    The scene's own Maya lights reach the bake as DATA, not as FBX light objects:
    one FBX light aborts Blender 5.1's importer outright (``lamp.cycles.cast_shadow``,
    removed in Cycles 5.x -- geometry and all), and FBX cannot represent Arnold light
    types at any version. Their TRANSFORMS do cross, as nulls the importer places and
    unit-converts correctly, so a real light is attached to each. The schema lives on
    ``MayaSceneImport._rebuild_lights`` beside the other Maya-manifest appliers, so
    this and the plain import template share one implementation.

    Returns ``{record name: object name}`` -- empty when the send carried no lights.
    """
    manifest = FBX_PATH + ".manifest.json"
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

        built = MayaSceneImport._rebuild_lights(manifest)
        if built and os.path.isfile(manifest):
            with open(manifest, "r", encoding="utf-8") as fh:
                records = (json.load(fh) or {}).get("lights") or []
            missing = {r.get("name") for r in records} - set(built)
            if missing:
                # The transform did not arrive -- usually a scope that excluded it.
                print(
                    "Scene light(s) not rebuilt (no matching object in the import): %s"
                    % ", ".join(sorted(n for n in missing if n))
                )
        return built
    except Exception:
        print("Scene-light rebuild failed; baking without them:")
        traceback.print_exc()
        return {}


def light_scene():
    """Apply the world and rebuild the scene's lights; report what actually lights the bake.

    Both sources are optional and compose. Existing light objects that DID survive the FBX
    are left untouched and simply bake alongside these.

    The returned summary rides home in the manifest. Printing it is not enough: this runs
    in a headless child whose stdout the bridge only surfaces when the run *fails*, so a
    bake that succeeds at being black -- the single most likely way this goes wrong -- says
    nothing at all on the Maya side, and reads as a broken tool rather than an unlit scene.
    """
    from blendertk.light_utils._light_utils import LightUtils

    hdri = ENVIRONMENT_HDR or None
    warnings = []
    print(
        "World:", LightUtils.set_world_environment(hdri=hdri, strength=WORLD_STRENGTH)
    )
    print(
        "Emission %s (appearance only): %s"
        % (EMISSION_STRENGTH, LightUtils.set_emission_strength(EMISSION_STRENGTH))
    )

    # The scene's own lights, rebuilt from the manifest onto the empties the FBX
    # placed (see rebuild_scene_lights for why they travel as data).
    rebuild_scene_lights()

    existing = [o for o in bpy.data.objects if o.type == "LIGHT"]
    scene_light_report = {}
    if existing:
        # Two composable primitives: the rebuild set each light's converted wattage,
        # this rebalances the lot. Applied BEFORE reporting so the printed numbers
        # are the ones actually baked -- Maya intensity is unitless, so the level is
        # only meaningful as a measured result, and this is what the artist tunes
        # SCENE_LIGHT_STRENGTH against.
        scene_light_report = LightUtils.scale_light_energy(
            SCENE_LIGHT_STRENGTH, existing
        )
        print(
            "Scene lights (x%s): %s"
            % (
                SCENE_LIGHT_STRENGTH,
                ", ".join(
                    "%s=%.4gW" % (n, w) for n, w in sorted(scene_light_report.items())
                ),
            )
        )
        if not any(scene_light_report.values()):
            warnings.append(
                "The %d scene light(s) all ended at zero power. Raise Scene Light "
                "Strength, or light the bake with an Environment HDRI."
                % len(existing)
            )
    elif __INCLUDE_LIGHTS__:
        # Asked for, but none arrived: worth saying, because the causes look
        # identical from here and only one of them is a mistake.
        print(
            "No scene lights to rebuild. Ambient and volume lights have no Cycles "
            "equivalent and are skipped; a StingrayPBS IBL is not a light object at "
            "all. Point / spot / directional / area (incl. aiAreaLight) do cross."
        )

    if not existing and not hdri:
        # The failure this whole section exists to prevent, called out before minutes of
        # baking rather than discovered afterwards.
        warnings.append(
            "No scene lights and no HDRI -- the bake will be BLACK. Turn on Include "
            "Lights and make sure the lights are INSIDE the sent selection -- only "
            "lights under the exported hierarchy travel, and Maya's default viewport "
            "lighting is not one. Or set an Environment HDRI, or author lights from "
            "the fixture geometry first -- mayatk's LightUtils.lights_from_geometry "
            "(tentacle Lighting panel) -- and send them with the bake."
        )
    for text in warnings:
        print("WARNING: %s" % text)
    return {
        "hdri": os.path.basename(hdri) if hdri else "",
        "world_strength": WORLD_STRENGTH,
        "imported_lights": len(existing),
        "scene_light_strength": SCENE_LIGHT_STRENGTH,
        # Per light, not a count: the Maya->Cycles unit translation is the thing most
        # likely to need tuning, and it cannot be judged from a total.
        "scene_light_power": scene_light_report,
        "warnings": warnings,
    }


def make_baker():
    """A LightmapBaker at the requested quality tier, with explicit overrides on top."""
    from blendertk.light_utils.lightmap_baker.lightmap_baker import LightmapBaker

    overrides = {}
    if LIGHTMAP_RESOLUTION:
        overrides["resolution"] = LIGHTMAP_RESOLUTION
    if LIGHTMAP_SAMPLES:
        overrides["samples"] = LIGHTMAP_SAMPLES
    baker = LightmapBaker.from_preset(
        LIGHTMAP_QUALITY,
        denoise=LIGHTMAP_DENOISE,
        device=LIGHTMAP_DEVICE or None,
        **overrides,
    )
    print(
        "Baker: %s @ %dpx / %d samples (denoise=%s, device=%s)"
        % (
            LIGHTMAP_QUALITY,
            baker.resolution,
            baker.samples,
            baker.denoise,
            baker.device,
        )
    )
    return baker


def write_return_manifest(packed, lighting):
    """Write the artifact Maya reads to reassemble this bake into its own scene.

    ``packed`` is ``{object_name: (exr_path, rect_or_None)}``. Carries, per object, the
    HDR EXR path and its per-instance atlas ``rect`` (omitted when identity/absent), plus
    ONE lightmap UV layout per unique mesh datablock (the ``meshes`` section) that each
    object references by ``mesh`` -- instances share a layout, so shipping it per copy
    would multiply the manifest for no data. EXRs, never web PNGs: the host's lightmap
    pipeline is float end to end, and platform encodes happen at each exporter, not here.

    Keyed by the name Blender holds -- the FBX short name, possibly with a ``.001``
    collision suffix -- the same convention every other replay in this bridge matches on,
    resolved back to Maya nodes on the far side.
    """
    from blendertk.uv_utils._uv_utils import UvUtils

    objs = {n: bpy.data.objects[n] for n in packed if n in bpy.data.objects}
    reps = (
        {}
    )  # datablock name -> one representative object (any; layouts are identical)
    for name in sorted(objs):
        reps.setdefault(objs[name].data.name, name)
    layouts = UvUtils.export_uv_layout([objs[n] for n in reps.values()])
    meshes = {
        data_name: layouts[rep_name]
        for data_name, rep_name in reps.items()
        if rep_name in layouts
    }

    identity = [1.0, 1.0, 0.0, 0.0]
    objects = {}
    for name, (path, rect) in sorted(packed.items()):
        obj = objs.get(name)
        if obj is None or obj.data.name not in meshes:
            continue
        entry = {"map": os.path.abspath(path), "mesh": obj.data.name}
        if rect is not None and [float(v) for v in rect] != identity:
            entry["rect"] = [float(v) for v in rect]
        objects[name] = entry

    missing = sorted(set(packed) - set(objects))
    if missing:
        # Without its layout a map cannot be wired in Maya, so say which and why rather
        # than letting the far side silently commit a subset of the selection.
        print(
            "WARNING: no lightmap UV layout captured for %d object(s): %s"
            % (len(missing), ", ".join(missing[:5]))
        )
    payload = {
        "version": RETURN_MANIFEST_VERSION,
        # A constant since the fused/unlit level was removed, but still WRITTEN: it is
        # the wire format every downstream reader keys on (the committed marker, the
        # GLB's lightmap_metadata, ptk.MeshConvert), and dropping the field would make
        # this manifest unreadable to them for no gain.
        "mode": "separated",
        # What actually lit this bake, reported back so the host can say so. A black bake
        # is a *successful* run of an unlit scene, indistinguishable on the Maya side from
        # a broken tool unless the bake says which sources it had.
        "lighting": lighting,
        "meshes": meshes,
        "objects": objects,
    }
    os.makedirs(os.path.dirname(OUT_FILE) or ".", exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    print(
        "Return manifest: %s (%d object(s), %d unique mesh(es))"
        % (OUT_FILE, len(objects), len(meshes))
    )


def main():
    bpy.ops.wm.read_factory_settings(use_empty=True)

    before = set(bpy.data.objects)
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=False,  # a lightmap is static; animation only slows the import
        # Off deliberately. The textures either ride the FBX as embedded media or are
        # rebuilt from the sidecar manifest below, which names their real paths -- so the
        # only thing a search adds is a recursive walk of the project's texture tree for
        # every unresolved image, which on a production sourceimages folder costs more
        # than the bake it precedes.
        use_image_search=False,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )
    new = [o for o in bpy.data.objects if o not in before]
    meshes = [o for o in new if o.type == "MESH"]
    print("Imported %d object(s), %d mesh(es)." % (len(new), len(meshes)))
    if not meshes:
        raise RuntimeError("No meshes imported; nothing to bake.")

    apply_texture_manifest(new)
    lighting = light_scene()
    baker = make_baker()

    out_dir = LIGHTMAP_DIR or os.path.dirname(OUT_FILE) or "."
    # Atlas-by-material: a material carries ONE lightmap in any engine, so per-object
    # maps would force a material copy per object downstream. The shared unwrap stays
    # untouched; each object's rect rides the manifest as its per-instance binding.
    # bake_atlas plans the layout first and bakes each object at the footprint it will
    # occupy -- and keeps the per-object tiles in its own temp dir, so only the
    # finished maps reach ``out_dir``.
    packed = baker.bake_atlas(meshes, output_dir=out_dir, suffix="_Lightmap")
    if not packed:
        raise RuntimeError("Bake produced no lightmaps; no manifest written.")

    print("Baked %d lightmap(s) -> %s" % (len(packed), out_dir))
    write_return_manifest(packed, lighting)


try:
    _extend_sys_path()
    try:
        import blendertk  # noqa: F401  -- required, unlike the other templates
    except Exception:
        traceback.print_exc()
        raise RuntimeError(
            "blendertk is not importable in this Blender; a lightmap bake cannot "
            "proceed. Refusing to write an empty manifest."
        )
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked by
# Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
