# Maya selection -> lightmapped WebXR GLB. Generated by BlenderBridge -- do not edit by hand.

"""Bake the bridged Maya selection's lightmaps in a headless Blender and write a WebXR GLB.

The Maya artist's one-step route to a lightmapped web deliverable: the same FBX payload and
``.manifest.json`` sidecar every Blender hand-off uses, delivered to
``blender --background`` which rebuilds the materials, lights the scene, bakes Cycles
lightmaps, and exports a browser-ready ``.glb``. No Blender window, no manual bake setup,
and no second export pipeline -- ``BlenderBridge`` produces the payload exactly once.

**Why Blender rather than Maya's own LightmapBaker**: Cycles bakes white-card irradiance
natively (``DIFFUSE`` minus the colour pass), needs no Arnold licence, denoises the result,
and runs on the GPU. mayatk's Arnold baker remains the Maya-native path; this is the web one.

**It is a round trip, not a one-way export.** Two artifacts come out of the single bake:
the ``.glb`` for the browser, and a ``.lightmaps.json`` sidecar carrying, per object, the
HDR EXR **and the lightmap UV layout it was baked through**. The Maya side writes that
layout onto its own meshes (``mtk.UvUtils.apply_uv_layout``) and then wires the maps in
**alongside the existing maps** (``mtk.LightmapBaker.commit_lightmap``) -- full PBR material
and UV0 untouched, the lightmap on UV1, revertible via the same ``revert_lightmap`` the
Maya-native bakes use.

Blender owns the lightmap job **end to end** -- UV generation, packing, baking, atlasing --
and hands back the finished layout. Maya does no lightmap prep: the bridge sends the assets,
Blender does the work, and the result is reassembled on return. Because the atlas repack is
applied to those UVs before they are captured, no separate atlas rect has to travel.

That reassembly is a straight per-loop array write, not a spatial transfer, because a
Maya -> FBX -> Blender crossing preserves per-face-vertex order exactly (probe-verified
across quads, tris and n-gons with FBX triangulation off). ``apply_uv_layout`` re-checks
each mesh's topology fingerprint anyway and skips any mesh edited since the hand-off.

**Lighting.** A Maya scene lit by StingrayPBS IBL exports **no lights at all** -- the
cubemaps are not FBX-portable and Blender cannot use them as a world -- so a bake of the
raw import is pure black. Two composable sources fix that, and both are real lighting:

* ``ENVIRONMENT_HDR`` -- an equirect HDRI as the world, standing in for the IBL cubemaps.
* ``FIXTURE_LIGHTS`` -- real Cycles **area lights** built from the light-fixture meshes by
  :meth:`blendertk.LightUtils.lights_from_geometry`, matched to each fixture's size,
  position and facing.

An emissive *map* is deliberately NOT a light source here: it is an appearance that makes a
fixture read as switched-on, and baking from it would tie the room's illumination to a
texture's exposure and leave the artist nothing to aim or re-colour. ``EMISSION_STRENGTH``
therefore only keeps that glow looking right alongside the real lights.

Runs via :class:`pythontk.ScriptRunDeliverer`, so success is judged by the written GLB, not
the exit code -- hence the ``os._exit`` below.

Unlike the other templates' best-effort material replay, blendertk is **required** here: a
lightmap bake without the baker is not a degraded result, it is no result, so its absence
exits 1 with no artifact rather than writing an unlit GLB the artist would have to discover
was wrong.

User-visible (no underscore), so it appears in the bridge panel's template dropdown as
``bake_lightmaps (save_as)``. Because it declares ``save_as`` it writes an **artifact**
rather than launching an interactive Blender: the panel asks where to put the ``.glb`` and
routes it through :meth:`~pythontk.ScriptLaunchBridge.save_as`, which is what fills in the
output path below. Also callable headlessly as
:meth:`~mayatk.BlenderBridge.bake_lightmaps`.

(Prose in this file is substituted too -- naming a token in a sentence would replace it
with the rendered value and leave a stray temp path in the generated script's docstring.)
"""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("save_as",)
# The artifact this writes, so the panel's save dialog offers the right format instead of
# inferring one from the template's name.
BRIDGE_OUTPUT_EXT = (".glb",)
# Seconds before the run is abandoned. The shared default is 600, which is SHORTER than a
# real bake: 7 objects at 512 samples / 1024px measured ~13 min, and samples scale it
# without limit. A bake killed mid-run leaves no artifact and reads as a silent failure,
# so this is deliberately generous -- it is a runaway guard, not a schedule.
BRIDGE_TIMEOUT = ("10800",)

# Dependency-free Blender Python at module scope: only Blender's own bundled modules are
# guaranteed here. blendertk is imported inside main(), after EXTRA_SYS_PATH is applied.
import json
import os
import sys
import traceback

import bpy

# Bridge-injected tokens (NOT registered parameters) arrive as raw strings, so they are
# quoted here. Everything below them IS a registered parameter and arrives already
# rendered as a Python literal by ``Formatters.python_literal`` -- so those tokens must
# stay BARE. Quoting a registered string would yield the literal ``"'separated'"``, and
# every mode comparison in this file would silently fail.
FBX_PATH = r"__FBX_PATH__"
OUT_FILE = r"__OUT_FILE__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores PYTHONPATH,
# so without these nothing below can import.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__

LIGHTMAP_RESOLUTION = __LIGHTMAP_RESOLUTION__
LIGHTMAP_SAMPLES = __LIGHTMAP_SAMPLES__
LIGHTMAP_MODE = __LIGHTMAP_MODE__
LIGHTMAP_DENOISE = __LIGHTMAP_DENOISE__
LIGHTMAP_DEVICE = __LIGHTMAP_DEVICE__

ENVIRONMENT_HDR = __ENVIRONMENT_HDR__
WORLD_STRENGTH = __WORLD_STRENGTH__
FIXTURE_LIGHTS = __FIXTURE_LIGHTS__
FIXTURE_PATTERN = __FIXTURE_PATTERN__
FIXTURE_WATTS = __FIXTURE_WATTS__
EMISSION_STRENGTH = __EMISSION_STRENGTH__

TEXTURE_MAX_SIZE = __TEXTURE_MAX_SIZE__
IMAGE_FORMAT = __IMAGE_FORMAT__
# Where the HDR (EXR) lightmaps land. Empty -> next to the GLB. The bridge points this
# at the Maya project's sourceimages so the round-tripped maps live where the Maya
# materials can reference them, instead of wherever the artist happened to save the GLB.
LIGHTMAP_DIR = __LIGHTMAP_DIR__


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def apply_texture_manifest(new_objects):
    """Replay the sidecar through blendertk's applier.

    Not optional here the way it is for a plain import: a lightmap bakes the *materials*'
    response to light, so an unshaded (grey) import would bake a grey room. A missing
    sidecar is still tolerated (a flat-coloured scene bakes fine); a present-but-failing
    one is logged loudly.
    """
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        print("No texture manifest; baking the FBX-carried materials.")
        return
    from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

    try:
        MayaSceneImport._tag_maya_node_types(manifest, new_objects)
    except Exception:
        print("Node-type tagging failed; skipped:")
        traceback.print_exc()
    try:
        MayaSceneImport(log_level="WARNING")._apply_texture_manifest(
            manifest, new_objects
        )
    except Exception:
        print("Texture-manifest rebuild failed; baking FBX materials:")
        traceback.print_exc()


def light_scene(web, meshes):
    """Apply the world and the fixture lights; return a manifest-friendly summary.

    Both sources are optional and compose. Existing light objects that DID survive the FBX
    are left untouched and simply bake alongside these.
    """
    summary = {"hdri": None, "world_strength": WORLD_STRENGTH, "fixture_lights": 0}

    from blendertk.light_utils._light_utils import LightUtils

    hdri = ENVIRONMENT_HDR or None
    print("World:", web.set_world_environment(hdri=hdri, strength=WORLD_STRENGTH))
    summary["hdri"] = os.path.basename(hdri) if hdri else None

    print(
        "Emission %s (appearance only): %s"
        % (EMISSION_STRENGTH, web.set_emission_strength(EMISSION_STRENGTH))
    )

    existing = [o for o in bpy.data.objects if o.type == "LIGHT"]
    if existing:
        print("Scene carries %d imported light(s); baking with them." % len(existing))
    summary["imported_lights"] = len(existing)

    if FIXTURE_LIGHTS:
        pattern = (FIXTURE_PATTERN or "").strip().lower()
        fixtures = [
            o for o in meshes if not pattern or pattern in o.name.lower()
        ]
        if fixtures:
            # diffuse_only: a baked specular highlight is locked to the baking viewpoint
            # and reads as a smudge from every other angle in a headset.
            created = LightUtils.lights_from_geometry(
                fixtures, power=FIXTURE_WATTS, diffuse_only=True
            )
            summary["fixture_lights"] = len(created)
            print("Fixture lights (%sW): %s" % (FIXTURE_WATTS, created))
        else:
            print("FIXTURE_LIGHTS on but no mesh matched %r." % FIXTURE_PATTERN)

    if not existing and not summary["fixture_lights"] and not hdri:
        # The failure this whole section exists to prevent, called out before minutes of
        # baking rather than discovered in the viewer afterwards.
        print(
            "WARNING: no HDRI, no fixture lights and no imported lights -- "
            "the bake will be black. Set ENVIRONMENT_HDR or FIXTURE_LIGHTS."
        )
    return summary


RETURN_MANIFEST_SUFFIX = ".lightmaps.json"
RETURN_MANIFEST_VERSION = 1


def write_return_manifest(result):
    """Write the sidecar Maya reads to reassemble this bake into its own scene.

    Carries, per object, the HDR EXR **and the lightmap UV layout it was baked through**.
    Blender owns the whole lightmap job -- it generates the UVs, packs them, bakes, and
    atlases -- so the layout here is the finished one, with the atlas placement already
    folded in. Maya writes it onto its own meshes rather than authoring a second, different
    layout the texels would not match; that is why no atlas rect needs to travel.

    EXRs, not the GLB's PNGs: those are percentile-normalized Non-Color web intermediates,
    while Maya's lightmap pipeline is float EXR end to end.

    Keyed by the name Blender holds -- the FBX short name, possibly with a ``.001``
    collision suffix -- the same convention every other replay in this bridge matches on,
    resolved back to Maya nodes on the far side.
    """
    from blendertk.uv_utils._uv_utils import UvUtils

    lightmaps = result.get("lightmaps") or {}
    layouts = UvUtils.export_uv_layout(
        [bpy.data.objects[n] for n in lightmaps if n in bpy.data.objects]
    )
    missing = sorted(set(lightmaps) - set(layouts))
    if missing:
        # Without its layout a map cannot be wired in Maya, so say which and why rather
        # than letting the far side silently commit a subset of the selection.
        print(
            "WARNING: no lightmap UV layout captured for %d object(s): %s"
            % (len(missing), ", ".join(missing[:5]))
        )
    payload = {
        "version": RETURN_MANIFEST_VERSION,
        "mode": result.get("mode") or LIGHTMAP_MODE,
        "objects": {
            name: {"map": os.path.abspath(path), "uv_layout": layouts[name]}
            for name, path in sorted(lightmaps.items())
            if name in layouts
        },
    }
    path = OUT_FILE + RETURN_MANIFEST_SUFFIX
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    print("Return manifest: %s (%d object(s))" % (path, len(payload["objects"])))
    return path


def main():
    bpy.ops.wm.read_factory_settings(use_empty=True)

    before = set(bpy.data.objects)
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=False,  # a lightmap is static; animation only slows the import
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )
    new = [o for o in bpy.data.objects if o not in before]
    meshes = [o for o in new if o.type == "MESH"]
    print("Imported %d object(s), %d mesh(es)." % (len(new), len(meshes)))
    if not meshes:
        raise RuntimeError("No meshes imported; nothing to bake.")

    apply_texture_manifest(new)

    from blendertk.light_utils.lightmap_baker.web_export import LightmapWebExport

    web = LightmapWebExport(
        resolution=LIGHTMAP_RESOLUTION,
        samples=LIGHTMAP_SAMPLES,
        denoise=LIGHTMAP_DENOISE,
        device=LIGHTMAP_DEVICE or None,
    )
    web.logger.setLevel("INFO")

    lighting = light_scene(web, meshes)
    lighting["mode"] = LIGHTMAP_MODE
    lighting["samples"] = LIGHTMAP_SAMPLES

    result = web.bake_and_export(
        OUT_FILE,
        objects=meshes,
        output_dir=os.path.dirname(OUT_FILE) or ".",
        lightmap_dir=LIGHTMAP_DIR or None,
        mode=LIGHTMAP_MODE,
        lighting=lighting,
        texture_max_size=TEXTURE_MAX_SIZE or None,
        image_format=IMAGE_FORMAT,
    )
    if not result.get("glb"):
        raise RuntimeError("Bake produced no lightmaps; no GLB written.")

    print(
        "Baked %d lightmap(s) into %d atlas(es) -> %s"
        % (len(result["maps"]), result["atlases"], result["glb"])
    )
    write_return_manifest(result)


try:
    _extend_sys_path()
    try:
        import blendertk  # noqa: F401  -- required, unlike the other templates
    except Exception:
        traceback.print_exc()
        raise RuntimeError(
            "blendertk is not importable in this Blender; a lightmap bake cannot "
            "proceed. Refusing to write an unlit GLB."
        )
    main()
except Exception:
    traceback.print_exc()
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(1)
# Success is judged by the artifact; exit hard so a raise above can't be masked by
# Blender's default exit-0-after-script-error behavior.
sys.stdout.flush()
os._exit(0)
