# Blender import script (Maya -> Blender bridge). Generated by BlenderBridge -- do not edit by hand.

"""Import the bridged FBX into Blender, with optional clean-slate and frame-on-import behaviors.

The single Blender-side recipe for the bridge. Two booleans pick the variant the artist wants
(this replaces what used to be three near-identical templates):

- ``CLEAR_SCENE`` -- delete the existing scene objects first (clean-slate / replace-scene hand-off).
- ``FRAME_VIEW``  -- after import, select the new objects, frame them in the viewport, and switch to
  material-preview shading.

With both off this is a plain additive import into the current scene; both on clears then frames."""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Maya-side before launch (read by BlenderBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ triangulate=__TRIANGULATE__
import bpy

FBX_PATH = r"__FBX_PATH__"
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
CLEAR_SCENE = __CLEAR_SCENE__
FRAME_VIEW = __FRAME_VIEW__


def main():
    if CLEAR_SCENE:
        bpy.ops.object.select_all(action="SELECT")
        bpy.ops.object.delete()

    before = set(bpy.data.objects)
    # global_scale 1.0 honors Blender's cm->m unit conversion of the Maya FBX; 100.0 cancels it
    # (preserves the raw numeric values) when the user opts out of unit scaling.
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )

    if not FRAME_VIEW:
        return

    new = [o for o in bpy.data.objects if o not in before]
    bpy.ops.object.select_all(action="DESELECT")
    for o in new:
        try:
            o.select_set(True)
        except (RuntimeError, ReferenceError):
            pass
    if new:
        bpy.context.view_layer.objects.active = new[0]

    screen = getattr(bpy.context, "screen", None)
    for area in (screen.areas if screen else []):
        if area.type != "VIEW_3D":
            continue
        for region in area.regions:
            if region.type == "WINDOW":
                with bpy.context.temp_override(area=area, region=region):
                    bpy.ops.view3d.view_selected()
        for space in area.spaces:
            if space.type == "VIEW_3D":
                space.shading.type = "MATERIAL"
        break


main()
