# Blender import + frame script (Maya -> Blender bridge). Generated by BlenderBridge -- do not edit.

"""Import the bridged FBX, select the new objects, frame them in the viewport, and switch to
material-preview shading -- drops the artist into a ready-to-look-at scene."""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Maya-side before launch (read by BlenderBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ triangulate=__TRIANGULATE__
import bpy

FBX_PATH = r"__FBX_PATH__"
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
FRAME_VIEW = __FRAME_VIEW__


def main():
    before = set(bpy.data.objects)
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )
    new = [o for o in bpy.data.objects if o not in before]

    bpy.ops.object.select_all(action="DESELECT")
    for o in new:
        try:
            o.select_set(True)
        except (RuntimeError, ReferenceError):
            pass
    if new:
        bpy.context.view_layer.objects.active = new[0]

    if FRAME_VIEW:
        screen = getattr(bpy.context, "screen", None)
        for area in (screen.areas if screen else []):
            if area.type != "VIEW_3D":
                continue
            for region in area.regions:
                if region.type == "WINDOW":
                    with bpy.context.temp_override(area=area, region=region):
                        bpy.ops.view3d.view_selected()
            for space in area.spaces:
                if space.type == "VIEW_3D":
                    space.shading.type = "MATERIAL"
            break


main()
