# Blender import script (Maya -> Blender bridge). Generated by BlenderBridge -- do not edit by hand.

"""Import the bridged FBX into Blender, with optional clean-slate and frame-on-import behaviors.

The single Blender-side recipe for the bridge. Two booleans pick the variant the artist wants
(this replaces what used to be three near-identical templates):

- ``CLEAR_SCENE`` -- delete the existing scene objects first (clean-slate / replace-scene hand-off).
- ``FRAME_VIEW``  -- after import, select the new objects, frame them in the viewport, and switch to
  material-preview shading.

With both off this is a plain additive import into the current scene; both on clears then frames.

Post-import repair (best-effort -- a repair must never cost the user the import):

- **Native material rebuild.** The FBX itself is not lossy: Maya writes StingrayPBS texture
  bindings as ``Maya|TEX_color_map`` / ``Maya|TEX_normal_map`` through
  ``FbxImplementation``/``FbxBindingTable``. Blender's importer reads those bindings and
  discards them by design (``WARNING: material link b'Maya|TEX_color_map' ignored``), wiring
  only the native Lambert/Phong slots -- so nothing survives into Python and a real
  production selection lands unshaded. ``BlenderBridge`` writes the same ``.manifest.json`` sidecar the
  pull direction uses (each material's ORIGINAL image files) and this script replays it through
  the ONE existing applier, ``blendertk.MayaSceneImport._apply_texture_manifest`` (the
  established template->paired-engine contract; see both ``_bake_scene.py`` templates and the
  mirrored ``blendertk`` send template). Without blendertk on the target Blender the FBX's
  classic-model materials are kept, with a console line saying so.
- **Groups arrive invisible, locators visible.** Both travel as identical FBX nulls; the
  manifest's ``transforms`` says which was which. Each Empty is tagged ``maya_node_type``
  (so a send BACK restores the right node type) and a group is shrunk to Blender's
  minimum display size, since a Maya group draws nothing (``tag_node_types``).
"""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Maya-side before launch (read by BlenderBridge; echoed here so the panel
# exposes them): scope=__SCOPE__ materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ triangulate=__TRIANGULATE__ lights=__INCLUDE_LIGHTS__
#
# ``lights`` is echoed for the same reason as the rest: it changes what the FBX carries,
# so it needs a visible row. On, this recipe brings the scene's Maya lights across (a
# scene transfer normally wants them); off ships geometry alone for a pure asset
# hand-off where Blender does its own lighting.
import os
import sys
import traceback

import bpy

FBX_PATH = r"__FBX_PATH__"
# Roots for blendertk + pythontk, resolved in the parent Maya. Blender ignores
# PYTHONPATH, so without these the manifest replay below can never import.
EXTRA_SYS_PATH = __EXTRA_SYS_PATH__
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__
CLEAR_SCENE = __CLEAR_SCENE__
FRAME_VIEW = __FRAME_VIEW__


def _extend_sys_path():
    """Make blendertk/pythontk importable here (Blender ignores PYTHONPATH)."""
    for entry in reversed(EXTRA_SYS_PATH or []):
        if entry and entry not in sys.path:
            sys.path.insert(0, entry)


def apply_texture_manifest(new_objects):
    """Replay the sidecar manifest through blendertk's applier (see module docstring)."""
    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    _extend_sys_path()
    try:
        from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport
    except Exception as error:
        print(
            "blendertk unavailable ({}); keeping the FBX-carried materials.".format(
                error
            )
        )
        return
    try:
        MayaSceneImport(log_level="WARNING")._apply_texture_manifest(
            manifest, new_objects
        )
    except Exception:
        print("Texture-manifest rebuild failed; keeping FBX materials:")
        traceback.print_exc()


# Display size for an Empty that was a Maya GROUP: a group draws nothing in Maya,
# and Blender has no "no display" Empty type, so it is shrunk to the property's
# hard minimum (sub-pixel; still selectable / transformable, origin dot when
# selected). Locators keep the importer's size -- Maya draws those. Dependency-free
# copy of ``blendertk...maya_bridge._scene_import.MAYA_GROUP_EMPTY_DISPLAY_SIZE``
# (the engine method every other Maya->Blender path routes through) -- kept in
# step by hand.
GROUP_EMPTY_DISPLAY_SIZE = 0.0001


def tag_node_types(new_objects):
    """Stamp ``maya_node_type`` custom props from the manifest's ``transforms``
    and give each Empty its Maya node type's look.

    Maya groups and locators both travel as identical FBX nulls and arrive as
    look-alike Empties. The manifest records which was which; the custom
    property carries that through the .blend so a later send BACK to Maya
    restores each Empty as the correct node type instead of guessing from the
    children heuristic. A group is also shrunk to ``GROUP_EMPTY_DISPLAY_SIZE``
    so it reads as Maya's invisible group transform, not a full-size axes cross;
    a locator keeps its display. Best-effort: no failure mode that could cost
    the import. Dependency-free copy of
    ``blendertk.MayaSceneImport._tag_maya_node_types`` -- kept in step by hand.
    """
    import json

    manifest = FBX_PATH + ".manifest.json"
    if not os.path.isfile(manifest):
        return
    try:
        with open(manifest, "r") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return
    types = data.get("transforms") if isinstance(data, dict) else None
    if not types:
        return
    for obj in new_objects:
        if obj.type != "EMPTY":
            continue
        # Tolerate Blender's rename-on-collision suffix ("grp1.001").
        node_type = types.get(obj.name) or types.get(obj.name.rsplit(".", 1)[0])
        if node_type:
            node_type = str(node_type)
            obj["maya_node_type"] = node_type
            if node_type == "group":
                obj.empty_display_size = GROUP_EMPTY_DISPLAY_SIZE


def rebuild_scene_lights():
    """Replay the manifest's light records through blendertk's applier.

    Maya's lights reach Blender as DATA beside the FBX, never inside it (one FBX
    light aborts Blender 5.1's importer outright, and FBX cannot represent Arnold
    light types at all) -- see ``MayaSceneImport._rebuild_lights``, which owns the
    schema alongside the other Maya-manifest appliers so this template and the
    bake round trip share one implementation.
    """
    from blendertk.env_utils.maya_bridge._scene_import import MayaSceneImport

    try:
        built = MayaSceneImport._rebuild_lights(FBX_PATH + ".manifest.json")
        if built:
            print("Rebuilt %d scene light(s): %s" % (len(built), sorted(built.values())))
    except Exception:
        print("Scene-light rebuild failed; the rest of the import is unaffected:")
        traceback.print_exc()


def main():
    if CLEAR_SCENE:
        bpy.ops.object.select_all(action="SELECT")
        bpy.ops.object.delete()

    before = set(bpy.data.objects)
    # global_scale 1.0 honors Blender's cm->m unit conversion of the Maya FBX; 100.0 cancels it
    # (preserves the raw numeric values) when the user opts out of unit scaling.
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )

    # Computed (and the manifest replayed) regardless of FRAME_VIEW: the
    # material rebuild is not a viewport nicety.
    new = [o for o in bpy.data.objects if o not in before]
    tag_node_types(new)
    apply_texture_manifest(new)
    # After the material replay: the rebuild swaps light empties for real lights, so
    # running it first would hand the applier objects that no longer exist.
    rebuild_scene_lights()

    if not FRAME_VIEW:
        return

    bpy.ops.object.select_all(action="DESELECT")
    for o in new:
        try:
            o.select_set(True)
        except (RuntimeError, ReferenceError):
            pass
    if new:
        bpy.context.view_layer.objects.active = new[0]

    screen = getattr(bpy.context, "screen", None)
    for area in (screen.areas if screen else []):
        if area.type != "VIEW_3D":
            continue
        for region in area.regions:
            if region.type == "WINDOW":
                with bpy.context.temp_override(area=area, region=region):
                    bpy.ops.view3d.view_selected()
        for space in area.spaces:
            if space.type == "VIEW_3D":
                space.shading.type = "MATERIAL"
        break


main()
