# Blender import script (Maya -> Blender bridge). Generated by BlenderBridge -- do not edit by hand.

"""Import the bridged FBX into the current Blender scene."""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Maya-side before launch (read by BlenderBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ triangulate=__TRIANGULATE__
import bpy

FBX_PATH = r"__FBX_PATH__"
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def main():
    # global_scale 1.0 honors Blender's cm->m unit conversion of the Maya FBX; 100.0 cancels it
    # (preserves the raw numeric values) when the user opts out of unit scaling.
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )


main()
