# Blender replace-scene import (Maya -> Blender bridge). Generated by BlenderBridge -- do not edit.

"""Delete the current scene's objects, then import the bridged FBX -- a clean-slate hand-off when
the selection is meant to replace what's in Blender rather than add to it."""

# Bridge metadata -- consumed by BlenderBridge before substitution.
BRIDGE_MODES = ("send_to",)

# Export settings applied Maya-side before launch (read by BlenderBridge; echoed here so the panel
# exposes them): materials=__INCLUDE_MATERIALS__ embed_textures=__EMBED_TEXTURES__ triangulate=__TRIANGULATE__
import bpy

FBX_PATH = r"__FBX_PATH__"
APPLY_UNIT_SCALE = __APPLY_UNIT_SCALE__
INCLUDE_ANIMATION = __INCLUDE_ANIMATION__


def main():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()
    bpy.ops.import_scene.fbx(
        filepath=FBX_PATH,
        use_anim=INCLUDE_ANIMATION,
        use_image_search=True,
        use_custom_normals=True,
        global_scale=1.0 if APPLY_UNIT_SCALE else 100.0,
    )


main()
