# Marmoset Toolbag baking setup script.
# Generated by MarmosetEngine -- do not edit by hand.

"""Bake source detail + surface maps onto the target meshes.

Preferred pairing: the scene's Bake Source set exports as a separate
companion FBX; this script imports the two files independently, so
classification is explicit and survives identical mesh names on both
sides. Fallback: single FBX + '_source'/'_target' name-suffix pairing
(a suffixed parent group tags everything under it).

Bakes geometry maps (Normal / AO / Curvature / ...) and surface-transfer
maps (Albedo / Roughness / Metalness / Emissive) read from the source
meshes' wired materials, one texture set per material, into production
image files (PNG/TGA/PSD) in the Output Dir."""

# Bridge metadata -- consumed by MarmosetEngine before substitution. The mode strings are
# the ecosystem-wide vocabulary from ``pythontk.core_utils.script_template``, not a
# per-bridge dialect.
#   send_to    = open Toolbag with the baker set up; user clicks Bake themselves.
#   round_trip = bake headless and let the host re-collect the resulting maps.
BRIDGE_MODES = ("send_to", "round_trip")

# Host-side knobs (read by the bridge slots before launch; echoed here so the
# panel exposes the widgets): scope=__SCOPE__ assign=__ASSIGN_MATERIAL__
# bake_source=__BAKE_SOURCE_SET__ auto_maps=__AUTO_MAPS__
#
# AUTO_MAPS is resolved BEFORE substitution: the engine reads the material
# manifest and rewrites the MAP_* tokens below from the channels the source
# materials actually have textures in, so this script always sees a concrete
# roster (and the derived bit depth matches it).

import json
import os
import sys

try:
    import mset
except ImportError:
    mset = None

MODEL_FILE = r"__MODEL_PATH__"
SOURCE_MODEL_FILE = r"__SOURCE_MODEL_PATH__"
PAIRS_FILE = r"__PAIRS_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
OUTPUT_DIR = r"__OUTPUT_DIR__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

# Pick up shared Toolbag-side helpers from the engine package dir.
sys.path.insert(0, r"__TOOLBAG_HELPERS_DIR__")
from _toolbag_helpers import ToolbagHelpers

# Bake output (parameters.py). PADDING/BITS are managed values -- derived
# host-side by TemplateParams.derive_bake_values (padding from the map size
# via pythontk's UV-padding primitive, bit depth from the per-map output
# templates), never exposed as widgets.
BAKE_SIZE = __BAKE_SIZE__
BAKE_SAMPLES = __BAKE_SAMPLES__
BAKE_PADDING = __BAKE_PADDING__
BAKE_BITS = __BAKE_BITS__
OUTPUT_FORMAT = __OUTPUT_FORMAT__

# Map toggles.
MAP_NORMAL = __MAP_NORMAL__
MAP_AO = __MAP_AO__
MAP_CURVATURE = __MAP_CURVATURE__
MAP_THICKNESS = __MAP_THICKNESS__
MAP_POSITION = __MAP_POSITION__
MAP_MATID = __MAP_MATID__
MAP_ALBEDO = __MAP_ALBEDO__
MAP_ROUGHNESS = __MAP_ROUGHNESS__
MAP_METALNESS = __MAP_METALNESS__
MAP_EMISSIVE = __MAP_EMISSIVE__

# Source/target suffix pairing (single-file fallback).
HIGH_SUFFIX = __HIGH_SUFFIX__
LOW_SUFFIX = __LOW_SUFFIX__
SUFFIX_INCLUDE_CHILDREN = __SUFFIX_INCLUDE_CHILDREN__
CAGE_OFFSET = __CAGE_OFFSET__
AUTO_CAGE = __AUTO_CAGE__
IGNORE_BACKFACES = __IGNORE_BACKFACES__

# Host-measured geometry for the auto cage:
#   CAGE_STANDOFFS      {mesh name: how far that source mesh's FURTHEST point
#                       stands off the target surface}, in host units. A real
#                       closest-point measurement, which is the one thing a
#                       bounding box cannot supply (see _bounds_cage_reach).
#   CAGE_HOST_DIAGONAL  the host's own target bounding-box diagonal, which is
#                       what converts those distances into Toolbag's units.
# Both are empty/zero when the host could not measure or did not run (the
# standalone panel has no scene); _bounds_cage_reach then stands in.
CAGE_STANDOFFS = __CAGE_STANDOFFS__
CAGE_HOST_DIAGONAL = __CAGE_HOST_DIAGONAL__

# Toolbag's cage offset spans the ray's FULL traversal, so the distance it
# actually reaches past the target surface is HALF the value. Measured on
# Toolbag 5.02 against a flat target with a slab source: a source whose
# furthest point sits D from the target first registers just above 2*D --
# D=25 captured at 52 and missed at 50, D=55 at 112 / missed 110, D=80 at 162
# / missed 160. Getting this factor wrong is silent: the bake simply omits the
# detail, with a cage value that looks reasonable next to the measurement.
CAGE_REACH_FACTOR = 2.0

# Headroom on a measured standoff. The host samples source VERTICES; the cage
# has to clear the surface running between them, and dense sources are sampled
# at a stride rather than exhaustively.
AUTO_CAGE_MARGIN = 1.25

# Fractions of the target's bounding-box diagonal. The two floors are
# deliberately different, because they carry different amounts of the answer:
#   FLOOR        -- measured path. The standoff IS the answer here, so this
#                   only stops a source sitting flush on its target from
#                   asking for a zero-length ray. Keeping it small is the
#                   point: inflating a cage past what was measured is how a
#                   group of small props starts projecting onto each other.
#   BOUNDS_FLOOR -- fallback path, where the overhang term sees nothing at all
#                   for a source inside the target's box and this is the whole
#                   estimate. Sized from the OFFICE_ENV room bake, whose light
#                   fixtures needed a reach of 8.84 against a 1180.8 diagonal.
#   CEILING      -- caps the BOUNDS-ONLY estimate, which cannot tell a
#                   genuinely distant source from a bad guess. A measured
#                   standoff is never clamped -- it is a fact about the
#                   geometry, and silently clipping it is how detail goes
#                   missing with nothing to say so; it is warned about instead.
AUTO_CAGE_FLOOR = 0.002
AUTO_CAGE_BOUNDS_FLOOR = 0.01
AUTO_CAGE_CEILING = 0.25

# Multiplier on the bounds-only overhang -- see _bounds_cage_reach, where the
# corners it measures are the only part of the source an AABB ever sees.
AUTO_CAGE_GAP_MARGIN = 1.5


# Enabled bake maps: Toolbag display name (``baker.getMap`` key; verified
# against Toolbag 5.02 -- e.g. tangent normals are "Normals", plural) mapped
# to the output filename suffix we want. Suffixes follow the pythontk
# MapFactory taxonomy so the Maya-side material wiring resolves each map's
# type from its filename alone.
_ENABLED_MAPS = {}
if MAP_NORMAL:
    _ENABLED_MAPS["Normals"] = "Normal_OpenGL"
if MAP_AO:
    _ENABLED_MAPS["Ambient Occlusion"] = "AO"
if MAP_CURVATURE:
    _ENABLED_MAPS["Curvature"] = "Curvature"
if MAP_THICKNESS:
    _ENABLED_MAPS["Thickness"] = "Thickness"
if MAP_POSITION:
    _ENABLED_MAPS["Position"] = "Position"
if MAP_MATID:
    _ENABLED_MAPS["Material ID"] = "MatID"
if MAP_ALBEDO:
    _ENABLED_MAPS["Albedo"] = "Base_Color"
if MAP_ROUGHNESS:
    _ENABLED_MAPS["Roughness"] = "Roughness"
if MAP_METALNESS:
    _ENABLED_MAPS["Metalness"] = "Metallic"
if MAP_EMISSIVE:
    _ENABLED_MAPS["Emissive"] = "Emissive"


def _output_stem():
    """Output path stem: Toolbag derives per-map filenames as
    <stem>_<texture set>_<suffix>.<ext>.

    The stem is a constant, NOT the scene/model name: the texture set (= the
    material) is the identity the maps should carry, and the roundtrip host
    strips the '<stem>_' prefix on relocation so production files land as
    <material>_<suffix>.<ext>. The literal below mirrors
    TemplateParams.BAKE_OUTPUT_STEM (host-side single source of truth --
    this script runs inside Toolbag and cannot import it).
    """
    ext = (OUTPUT_FORMAT or "png").lstrip(".").lower()
    return os.path.join(OUTPUT_DIR, "bake.%s" % ext)


def _set(obj, attr, value):
    """Best-effort setattr with a log line naming any attribute that drifted."""
    try:
        setattr(obj, attr, value)
        return True
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log(
            "  [bake] %s=%r failed: %s: %s" % (attr, value, type(exc).__name__, exc)
        )
        return False


def _apply_import_prefs():
    """Pin the import preferences the bake depends on; return a restore callable.

    Two user preferences can silently break the surface-transfer bake:

    * "import FBX without materials" -- no materials means nothing to wire,
      so albedo/roughness/metalness bake flat.
    * "import models as references" -- reference wrappers re-instantiate
      when their meshes are reparented into the baker's containers, which
      resets the imported materials and wipes any wiring already applied.

    Attribute names are probed defensively -- a Toolbag build without them
    just logs and imports as configured.
    """
    try:
        prefs = mset.getPreferences()
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("[bake] getPreferences failed: %s" % exc)
        return lambda: None
    wanted = {
        "importFbxWithMaterials": True,
        "importWithMaterials": True,
        "importModelsAsReferences": False,
    }
    restores = []
    for attr, value in wanted.items():
        if not hasattr(prefs, attr):
            continue
        original = getattr(prefs, attr)
        if original != value:
            try:
                setattr(prefs, attr, value)
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("[bake] could not set %s: %s" % (attr, exc))
                continue
            restores.append((attr, original))
            ToolbagHelpers.log(
                "[bake] Pinned %s=%s for this run (was %s)." % (attr, value, original)
            )

    def _restore():
        for attr, original in restores:
            try:
                setattr(prefs, attr, original)
            except Exception:  # noqa: BLE001
                pass

    return _restore


def _base_name(name):
    """Mesh leaf name with FBX '.001' duplicate suffixes and source/target tags stripped."""
    stem = name.rsplit(".", 1)[0] if "." in name else name
    for suffix in (HIGH_SUFFIX, LOW_SUFFIX):
        if suffix and stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    return stem.lower()


def _configure_baker(baker):
    _set(baker, "outputPath", _output_stem())
    _set(baker, "outputWidth", BAKE_SIZE)
    _set(baker, "outputHeight", BAKE_SIZE)
    _set(baker, "outputSamples", BAKE_SAMPLES)
    _set(baker, "outputBits", BAKE_BITS)
    _set(baker, "edgePaddingSize", float(BAKE_PADDING))
    _set(baker, "ignoreBackfaces", IGNORE_BACKFACES)

    # Deterministic map roster: the user's Toolbag remembers per-map enables
    # and custom suffixes across sessions, so start from all-off and enable
    # exactly what the panel asked for, with our canonical suffixes.
    try:
        for m in baker.getAllMaps() or []:
            m.enabled = False
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("[bake] Could not reset map roster: %s" % exc)
    for display_name, suffix in _ENABLED_MAPS.items():
        try:
            m = baker.getMap(display_name)
            m.enabled = True
            m.suffix = suffix
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log(
                "  [bake] map %r unavailable: %s" % (display_name, exc)
            )
    ToolbagHelpers.log(
        "[bake] Maps enabled: %s" % ", ".join(sorted(_ENABLED_MAPS))
    )

    # No cage settings here: BakerObject carries none (verified against
    # Toolbag 5.02 -- the cage offsets live on each group's BakerTargetObject,
    # applied in _add_pair_group).


def _union_bounds(objects):
    """World-space AABB over *objects* as ``(min_xyz, max_xyz)``, or None.

    ``getBounds()`` returns ``[min_xyz, max_xyz]`` -- and only MESH objects
    report one: the baker's High/Low containers answer None even with meshes
    parented in (Toolbag 5.02), so the union has to be taken over the meshes
    themselves rather than asked of their parent.
    """
    lo = [None, None, None]
    hi = [None, None, None]
    for o in objects or []:
        try:
            bounds = o.getBounds()
        except Exception:  # noqa: BLE001
            bounds = None
        if not bounds or len(bounds) != 2:
            continue
        for i in range(3):
            lo[i] = bounds[0][i] if lo[i] is None else min(lo[i], bounds[0][i])
            hi[i] = bounds[1][i] if hi[i] is None else max(hi[i], bounds[1][i])
    if lo[0] is None:
        return None
    return lo, hi


def _diagonal(bounds):
    """Length of *bounds*' diagonal, or 0.0 for no/degenerate bounds."""
    if bounds is None:
        return 0.0
    (lo, hi) = bounds
    return sum((hi[i] - lo[i]) ** 2 for i in range(3)) ** 0.5


def _unit_scale(targets):
    """Host distance -> Toolbag distance, read off the target's own size.

    The host measures standoffs in ITS scene units; Toolbag reports bounds in
    its own. Dividing the two measurements of the SAME target geometry converts
    between them without either side having to know the other's unit setting --
    and it is 1.0 whenever the FBX round-trip preserves scale, which is the
    normal case (verified against Toolbag 5.02: a 200cm Maya quad imports as
    200 Toolbag units).
    """
    if not CAGE_HOST_DIAGONAL:
        return 1.0
    here = _diagonal(_union_bounds(targets))
    if here <= 0.0:
        return 1.0
    scale = here / CAGE_HOST_DIAGONAL
    if abs(scale - 1.0) > 0.01:
        ToolbagHelpers.log(
            "[bake] Target imported at %.4gx the host's scale; host-measured "
            "cage standoffs scaled to match." % scale
        )
    return scale


def _measured_standoff(name, sources, scale):
    """Furthest *sources* stand off the target, in TOOLBAG units, or None.

    Reads the host's closest-point measurements, keyed the same way the bake
    groups are (:func:`_base_name`), so FBX's ``.001`` duplicate suffixes and
    the source/target name tags don't break the match.
    """
    if not CAGE_STANDOFFS:
        return None
    lookup = {}
    for mesh, distance in CAGE_STANDOFFS.items():
        key = _base_name(mesh)
        lookup[key] = max(float(distance), lookup.get(key, 0.0))

    keys = [_base_name(getattr(o, "name", "")) for o in sources]
    known = [lookup[k] for k in keys if k in lookup]
    if not known:
        return None
    missing = [k for k in keys if k not in lookup]
    if missing:
        # Partial data still beats the bounds fallback, but the cage is then
        # sized off only the meshes we could match -- say so rather than let
        # an unmeasured source quietly set the ceiling on what gets baked.
        ToolbagHelpers.log(
            "  [bake] group %r: %d of %d source mesh(es) are missing from the "
            "host's cage measurements (%s); the cage is sized from the rest."
            % (name, len(missing), len(keys), ", ".join(sorted(set(missing))[:6]))
        )
    return max(known) * scale


def _bounds_cage_reach(sources, targets, diagonal):
    """Fallback reach from bounding boxes alone, when the host measured nothing.

    Two terms, and it matters which does the work:

    * The **overhang** -- how far the source's bounding box sticks out past
      the target's on any axis, times a margin for the detail between those
      corners. This sees only source geometry OUTSIDE the target's box. It is
      blind to a source standing off an INTERIOR surface (a light fixture
      under a ceiling, a door inset in its opening): that geometry is inside
      the target's box, so its overhang reads zero.
    * The **floor** -- a fraction of the target's own diagonal, which is all
      that covers the interior case, and what makes the value track the
      scene's scale rather than the units it happens to be in.

    A bounding box cannot express "how far this mesh stands off that surface",
    which is why the host measures it directly (Maya/Blender both have a
    closest-point acceleration structure) and this path is only the stand-in
    for a caller that has no scene to measure.
    """
    gap = 0.0
    target_bounds = _union_bounds(targets)
    source_bounds = _union_bounds(sources)
    if target_bounds is not None and source_bounds is not None:
        (tmin, tmax) = target_bounds
        (smin, smax) = source_bounds
        for i in range(3):
            gap = max(gap, tmin[i] - smin[i], smax[i] - tmax[i])
    return min(
        max(gap * AUTO_CAGE_GAP_MARGIN, diagonal * AUTO_CAGE_BOUNDS_FLOOR),
        diagonal * AUTO_CAGE_CEILING,
    )


def _auto_cage_offset(name, sources, targets, scale):
    """``(offset, how it was arrived at)`` for this group, or ``(None, why not)``.

    The offset is the REACH the geometry needs, times
    :data:`CAGE_REACH_FACTOR` -- Toolbag's value is a full-traversal distance,
    so it has to be double the distance actually being cleared.

    Deliberately NOT Toolbag's own ``BakerTargetObject.estimateOffset()``:
    that call hard-crashes toolbag.exe under ``-run`` (verified on 5.02, with
    and without geometry in the group -- the process dies with no traceback,
    taking the whole bake with it).
    """
    diagonal = _diagonal(_union_bounds(targets))
    if diagonal <= 0.0:
        return None, "the bake target reports no bounds"

    standoff = _measured_standoff(name, sources, scale)
    if standoff is not None:
        reach = max(standoff * AUTO_CAGE_MARGIN, diagonal * AUTO_CAGE_FLOOR)
        offset = reach * CAGE_REACH_FACTOR
        if offset > diagonal * AUTO_CAGE_CEILING:
            ToolbagHelpers.log(
                "  [bake] WARNING: group %r needs a cage of %g to reach source "
                "geometry standing %g off the target -- that is %.0f%% of the "
                "target's own size, and a cage that deep can project "
                "neighbouring detail onto the wrong place. Check whether that "
                "source belongs in this bake."
                % (name, offset, standoff, 100.0 * offset / diagonal)
            )
        return offset, "measured standoff %g" % standoff

    reach = _bounds_cage_reach(sources, targets, diagonal)
    return reach * CAGE_REACH_FACTOR, "bounds estimate -- nothing measured host-side"


def _apply_cage(target_parent, name, sources, targets, scale):
    """Set the group's cage offset -- auto-sized when asked for, else the typed one.

    ``maxOffset`` is the real attribute name on ``BakerTargetObject`` (verified
    against Toolbag 5.02). ``minOffset`` is left alone because it does NOT
    bound the inward ray: probed headless on 5.02 with a flat target and a
    source slab 25 units BEHIND it (and a second one 5 behind), maxOffset=2,
    sweeping minOffset over -1e6, -60 .. -3, 0, 3 .. 51, +1e6 -- the first
    front-facing surface behind the target registered at EVERY value. The
    ray travels inward until it hits something; the only thing that stops a
    source behind the target from being baked onto it is not being in the
    same bake group.
    """
    offset = CAGE_OFFSET
    auto_offset, how = _auto_cage_offset(name, sources, targets, scale)
    if AUTO_CAGE:
        if auto_offset is None:
            ToolbagHelpers.log(
                "  [bake] group %r: %s; using the typed cage offset %g."
                % (name, how, CAGE_OFFSET)
            )
        else:
            offset = auto_offset
            ToolbagHelpers.log(
                "  [bake] group %r: auto cage offset %g (%s)." % (name, offset, how)
            )
    elif auto_offset is not None and CAGE_OFFSET < auto_offset:
        # A manual offset is a distance in SCENE UNITS, and one below what the
        # geometry needs cannot reach source detail that stands off the surface
        # (a light fixture under a ceiling, a door in its opening) -- that
        # detail is then absent from the maps with nothing to say so.
        ToolbagHelpers.log(
            "  [bake] WARNING: group %r cage offset %g is too small for this "
            "geometry -- source detail will not be baked. Auto would use %g "
            "(%s)." % (name, CAGE_OFFSET, auto_offset, how)
        )
    else:
        # Say what was used even when nothing is wrong: a bake log that is
        # silent about the cage cannot be diagnosed after the fact (the
        # 2026-08-18 TURRETS_WIRES log had no cage line at all).
        ToolbagHelpers.log(
            "  [bake] group %r: cage offset %g (typed%s)."
            % (
                name,
                CAGE_OFFSET,
                "" if auto_offset is None else "; auto would use %g" % auto_offset,
            )
        )
    if hasattr(target_parent, "maxOffset"):
        _set(target_parent, "maxOffset", offset)
    else:
        # The attribute moved or went away in this Toolbag build: say so, or
        # the bake runs with Toolbag's default cage and looks like the offset
        # simply had no effect.
        ToolbagHelpers.log(
            "  [bake] group %r: no 'maxOffset' on the bake target (%s); the "
            "cage offset was NOT applied."
            % (name, type(target_parent).__name__)
        )


def _bake_group_targets(group):
    """Return the (source, target) child containers of a bake group.

    Toolbag names the containers 'High' and 'Low' -- its API vocabulary,
    kept verbatim here; everywhere else this script says source/target.
    """
    source = target = None
    try:
        for child in group.getChildren() or []:
            cname = getattr(child, "name", "")
            if cname == "High":
                source = child
            elif cname == "Low":
                target = child
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("  [bake] couldn't enumerate group children: %s" % exc)
    return source, target


def _add_pair_group(baker, name, sources, targets, scale=1.0):
    """Create one bake group and parent *sources*/*targets* into its containers."""
    group = baker.addGroup(name)
    source_parent, target_parent = _bake_group_targets(group)
    if source_parent is None or target_parent is None:
        ToolbagHelpers.log(
            "  [bake] group %r children unexpected; skipping." % name
        )
        return 0
    _apply_cage(target_parent, name, sources, targets, scale)
    wired = 0
    for o in targets:
        try:
            o.parent = target_parent
            wired += 1
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("  [bake] could not parent target %r: %s" % (o.name, exc))
    for o in sources:
        try:
            o.parent = source_parent
            wired += 1
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("  [bake] could not parent source %r: %s" % (o.name, exc))
    return wired


def _group_by_base_name(objects):
    """``{base name: [objects]}`` over *objects*, keyed by :func:`_base_name`."""
    out = {}
    for o in objects:
        out.setdefault(_base_name(getattr(o, "name", "")), []).append(o)
    return out


def _build_groups(baker, sources, targets):
    """One bake group per matching leaf name; leftovers share a 'Rest' group.

    Name-matched groups isolate each source/target pair's rays -- with the
    whole set in one group, nearby props project onto each other. Unmatched
    meshes still pair with each other in a shared group.

    **Isolation is all-or-nothing**, and that is the point of the pre-check
    below. A bake group only bakes what it CONTAINS: source meshes in a group
    with no target project onto nothing, and target meshes in a group with no
    source bake empty maps. So whenever the leftovers can't pair with each
    other -- the classic case being a target whose name happens to match one
    source mesh, which claims its own group and strands every other source in
    a target-less 'Rest' (detail simply missing from the bake, with no cage
    value able to bring it back) -- name matching is abandoned for the whole
    set and everything bakes as ONE group. Losing ray isolation is a quality
    trade-off; stranding geometry is a wrong result.
    """
    # Measured once over the WHOLE target: it converts the host's standoff
    # distances into Toolbag units, and the host measured them against the
    # whole target too, so a per-group diagonal would be the wrong ruler.
    scale = _unit_scale(targets)

    by_name_source = _group_by_base_name(sources)
    by_name_target = _group_by_base_name(targets)

    matched = set(by_name_target) & set(by_name_source)
    rest_sources = [
        o for base, objs in by_name_source.items() if base not in matched for o in objs
    ]
    rest_targets = [
        o for base, objs in by_name_target.items() if base not in matched for o in objs
    ]

    # Leftovers on one side only: they have nothing to pair with, so isolating
    # the matched names would drop them out of the bake entirely.
    if bool(rest_sources) != bool(rest_targets):
        stranded = rest_sources or rest_targets
        ToolbagHelpers.log(
            "[bake] %d %s mesh(es) have no name-matched counterpart (%s); "
            "baking every mesh as ONE group so nothing is left out of the "
            "bake. Give the pairs matching names to restore per-pair ray "
            "isolation."
            % (
                len(stranded),
                "source" if rest_sources else "target",
                ", ".join(
                    sorted({_base_name(getattr(o, "name", "")) for o in stranded})
                ),
            )
        )
        _add_pair_group(baker, "All", sources, targets, scale)
        return

    for base in sorted(matched):
        _add_pair_group(
            baker, base or "pair", by_name_source[base], by_name_target[base], scale
        )

    if rest_sources or rest_targets:
        ToolbagHelpers.log(
            "[bake] %d unpaired mesh(es) -> shared 'Rest' group "
            "(source=%d target=%d)." % (len(rest_sources) + len(rest_targets), len(rest_sources), len(rest_targets))
        )
        _add_pair_group(baker, "Rest", rest_sources, rest_targets, scale)
    ToolbagHelpers.log("[bake] Built %d name-matched bake group(s)." % len(matched))


def _enable_texture_sets(baker):
    """Switch to per-material texture sets so each material bakes its own maps.

    A single shared set would stack every material's UV layout into one
    image. ``tileMode`` gates the texture-set API; the enum value for
    "Multiple Texture Sets" is probed since only 0 (single) is documented.
    On total failure the original mode is restored so the baker isn't left
    in whatever mode the last failed probe set.
    """
    original_mode = getattr(baker, "tileMode", 0)
    for tile_mode in (1, 2):
        try:
            baker.tileMode = tile_mode
            count = baker.getTextureSetCount()
        except Exception:  # noqa: BLE001
            continue
        names = []
        for i in range(count):
            try:
                names.append(baker.getTextureSetName(i))
                baker.setTextureSetWidth(i, BAKE_SIZE)
                baker.setTextureSetHeight(i, BAKE_SIZE)
                baker.setTextureSetEnabled(i, True)
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("  [bake] texture set %d: %s" % (i, exc))
        # ``str()`` per name: a Toolbag build that returns a non-string here
        # must not take down the whole bake setup on a log line.
        ToolbagHelpers.log(
            "[bake] tileMode=%d -> %d texture set(s): %s"
            % (tile_mode, count, ", ".join(str(n) for n in names))
        )
        return count
    _set(baker, "tileMode", original_mode)
    ToolbagHelpers.log(
        "[bake] Texture sets unavailable; baking a single shared set."
    )
    return 0


def main():
    ToolbagHelpers.begin_log(MANIFEST_FILE or MODEL_FILE)
    if not os.path.isfile(MODEL_FILE):
        ToolbagHelpers.log("ERROR: Model file not found: %s" % MODEL_FILE)
        return

    restore_prefs = _apply_import_prefs()
    try:
        imported = mset.importModel(MODEL_FILE)
        if imported is None:
            ToolbagHelpers.log("ERROR: importModel returned None.")
            return
        # In the two-file flow these are exactly the target meshes; in
        # the single-file fallback the batch holds BOTH sides and is split
        # below.
        model_meshes = ToolbagHelpers.collect_mesh_objects(imported)

        source_meshes = []
        if SOURCE_MODEL_FILE and os.path.isfile(SOURCE_MODEL_FILE):
            imported_source = mset.importModel(SOURCE_MODEL_FILE)
            source_meshes = ToolbagHelpers.collect_mesh_objects(imported_source)
    finally:
        restore_prefs()

    if source_meshes:
        # Two-file flow: the import batches ARE the classification.
        sources, targets = source_meshes, model_meshes
        ToolbagHelpers.log(
            "[bake] Two-file import: %d target / %d source mesh(es)."
            % (len(targets), len(sources))
        )
    else:
        # Single-file fallback: sidecar first, then name-suffix chain walk.
        pre_classified = {}
        if PAIRS_FILE and os.path.isfile(PAIRS_FILE):
            try:
                with open(PAIRS_FILE, "r", encoding="utf-8") as fh:
                    pre_classified = json.load(fh) or {}
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("[bake] Failed to read pairs sidecar: %s" % exc)
        sources, targets, others = ToolbagHelpers.split_source_target(
            model_meshes,
            HIGH_SUFFIX,
            LOW_SUFFIX,
            pre_classified=pre_classified,
            include_children=SUFFIX_INCLUDE_CHILDREN,
        )
        ToolbagHelpers.log(
            "[bake] Suffix pairing: source=%d target=%d other=%d"
            % (len(sources), len(targets), len(others))
        )
        if not sources:
            ToolbagHelpers.log(
                "[bake] WARNING: no bake source resolved. Define the scene's "
                "Bake Source set in the bridge panel or use the "
                "name-suffix convention."
            )

    baker = mset.BakerObject()
    _configure_baker(baker)
    _build_groups(baker, sources, targets)
    _enable_texture_sets(baker)

    # Wire the Maya materials (with staged/unpacked textures) onto the
    # imported Toolbag materials -- the surface-transfer maps (Albedo /
    # Roughness / Metalness / Emissive) sample exactly these. Deliberately
    # LAST, after the baker groups exist: wiring applied before the meshes
    # are reparented can be reset by model re-instantiation. Color maps stay
    # sRGB-flagged: the bake writes sRGB-encoded output from the linear
    # sample (verified: flat linear 0.5 bakes to 188), so an sRGB-sampled
    # source round-trips as an identity copy of the texel values.
    if MANIFEST_FILE and os.path.isfile(MANIFEST_FILE):
        ToolbagHelpers.wire_materials_from_manifest(MANIFEST_FILE)

    if SHOULD_QUIT:
        # Headless run: bake before quitting so the bake actually happens.
        # Bake BEFORE any save: saveScene re-serializes the just-wired
        # texture bindings into a state that samples with an extra sRGB
        # conversion (verified on Toolbag 5.02 -- wiring -> save -> bake
        # shifted every color transfer, while wiring -> bake is an identity
        # copy of the source texels).
        ToolbagHelpers.log("Running bake ...")
        try:
            baker.bake()
            ToolbagHelpers.log("Bake finished.")
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("Bake failed: %s" % exc)

    if SAVE_PATH:
        ToolbagHelpers.log("Saving bake scene: %s" % SAVE_PATH)
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        ToolbagHelpers.log("Quitting Toolbag ...")
        mset.quit()


if __name__ == "__main__":
    main()
