# Marmoset Toolbag baking setup script.
# Generated by mayatk.mat_utils.marmoset_bridge.MarmosetBridge -- do not edit by hand.

# Bridge metadata -- consumed by MarmosetBridge before substitution.
#   send_to   = open Toolbag with the baker set up; user clicks Bake themselves.
#   roundtrip = bake headless and let Maya re-import the resulting maps.
BRIDGE_MODES = ("send_to", "roundtrip")

import os

try:
    import mset
except ImportError:
    mset = None

FBX_FILE = r"__FBX_PATH__"
OUTPUT_DIR = r"__OUTPUT_DIR__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

# Bake output (parameters.py).
BAKE_WIDTH = __BAKE_WIDTH__
BAKE_HEIGHT = __BAKE_HEIGHT__
BAKE_SAMPLES = __BAKE_SAMPLES__
BAKE_PADDING = __BAKE_PADDING__
BAKE_BITS = __BAKE_BITS__
BAKE_OUTPUT_DIR = __BAKE_OUTPUT_DIR__

# Map toggles.
MAP_NORMAL = __MAP_NORMAL__
MAP_AO = __MAP_AO__
MAP_CURVATURE = __MAP_CURVATURE__
MAP_THICKNESS = __MAP_THICKNESS__
MAP_POSITION = __MAP_POSITION__
MAP_MATID = __MAP_MATID__

# High/low pairing.
HIGH_SUFFIX = __HIGH_SUFFIX__
LOW_SUFFIX = __LOW_SUFFIX__
CAGE_OFFSET = __CAGE_OFFSET__
IGNORE_BACKFACES = __IGNORE_BACKFACES__


# Toolbag's getBakeMap() takes the user-facing display name.
_MAP_DISPLAY_NAMES = {
    "MAP_NORMAL": "Normal",
    "MAP_AO": "Ambient Occlusion",
    "MAP_CURVATURE": "Curvature",
    "MAP_THICKNESS": "Thickness",
    "MAP_POSITION": "Position",
    "MAP_MATID": "Material ID",
}


def _output_dir():
    """Where baked maps go -- explicit override wins, else FBX folder."""
    return BAKE_OUTPUT_DIR or OUTPUT_DIR


def _output_path():
    """Base output path; Toolbag appends ``_<MapName>`` and the extension."""
    # Extension chosen so Toolbag's autoselect honors BAKE_BITS:
    # 8-bit -> .tga, 16-bit -> .tif.
    ext = ".tif" if BAKE_BITS >= 16 else ".tga"
    return os.path.join(_output_dir(), "bake" + ext)


def _toggle_map(baker, key, enabled):
    """Enable/disable a bake map by display name. Silent no-op if missing."""
    name = _MAP_DISPLAY_NAMES.get(key)
    if not name:
        return
    try:
        m = baker.getBakeMap(name)
    except Exception as e:
        print(f"  [bake] no map '{name}': {e}")
        return
    if m is not None:
        m.enabled = bool(enabled)


def _split_high_low(objects):
    """Group imported objects into (high, low, ungrouped) by suffix."""
    highs, lows, others = [], [], []
    for o in objects:
        name = getattr(o, "name", "") or ""
        # FBX importers occasionally suffix duplicates with ``.001`` -- strip
        # so the high/low suffix check is still valid.
        stem = name.rsplit(".", 1)[0] if "." in name else name
        if HIGH_SUFFIX and stem.endswith(HIGH_SUFFIX):
            highs.append(o)
        elif LOW_SUFFIX and stem.endswith(LOW_SUFFIX):
            lows.append(o)
        else:
            others.append(o)
    return highs, lows, others


def main():
    if not os.path.isfile(FBX_FILE):
        print("ERROR: FBX file not found.")
        return

    imported = mset.importModel(FBX_FILE) or []
    print(f"[bake] Imported {len(imported)} object(s).")

    baker = mset.BakerObject()
    baker.outputWidth = BAKE_WIDTH
    baker.outputHeight = BAKE_HEIGHT
    baker.outputSamples = BAKE_SAMPLES
    baker.edgePadding = BAKE_PADDING
    baker.outputBits = BAKE_BITS
    baker.outputPath = _output_path()
    baker.ignoreBackfaces = IGNORE_BACKFACES

    # Newer Toolbag versions name this differently; not all expose it.
    for attr in ("maxOffset", "maxOffsetDistance"):
        if hasattr(baker, attr):
            try:
                setattr(baker, attr, CAGE_OFFSET)
                break
            except Exception:
                pass

    for key, enabled in (
        ("MAP_NORMAL", MAP_NORMAL),
        ("MAP_AO", MAP_AO),
        ("MAP_CURVATURE", MAP_CURVATURE),
        ("MAP_THICKNESS", MAP_THICKNESS),
        ("MAP_POSITION", MAP_POSITION),
        ("MAP_MATID", MAP_MATID),
    ):
        _toggle_map(baker, key, enabled)

    highs, lows, others = _split_high_low(imported)
    print(f"[bake] high={len(highs)} low={len(lows)} other={len(others)}")

    # BakerGroupObject pairs high-poly source meshes with low-poly targets so
    # the baker can ray-cast from low->high. Only assign if we found at least
    # one matching pair via the suffix convention.
    if highs or lows:
        try:
            group = baker.addGroup("MayaBridge")
            for o in lows:
                group.addLow(o)
            for o in highs:
                group.addHigh(o)
            print(f"[bake] Paired {len(highs)} high / {len(lows)} low into group.")
        except Exception as e:
            print(f"[bake] Could not auto-pair high/low (drag manually): {e}")

    if SAVE_PATH:
        print(f"Saving bake scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        # Headless run: bake before quitting so the bake actually happens.
        print("Running bake ...")
        try:
            baker.bake()
        except Exception as e:
            print(f"Bake failed: {e}")
        print("Quitting Toolbag ...")
        mset.quit()


if __name__ == "__main__":
    main()
