# Marmoset Toolbag baking setup script.
# Generated by MarmosetEngine -- do not edit by hand.

"""Bake source detail + surface maps onto the target meshes.

Preferred pairing: the scene's Bake Source set exports as a separate
companion FBX; this script imports the two files independently, so
classification is explicit and survives identical mesh names on both
sides. Fallback: single FBX + '_source'/'_target' name-suffix pairing
(a suffixed parent group tags everything under it).

Bakes geometry maps (Normal / AO / Curvature / ...) and surface-transfer
maps (Albedo / Roughness / Metalness / Emissive) read from the source
meshes' wired materials, one texture set per material, into production
image files (PNG/TGA/PSD) in the Output Dir."""

# Bridge metadata -- consumed by MarmosetEngine before substitution.
#   send_to   = open Toolbag with the baker set up; user clicks Bake themselves.
#   roundtrip = bake headless and let the host re-collect the resulting maps.
BRIDGE_MODES = ("send_to", "roundtrip")

# Host-side knobs (read by the bridge slots before launch; echoed here so the
# panel exposes the widgets): scope=__SCOPE__ assign=__ASSIGN_MATERIAL__
# bake_source=__BAKE_SOURCE_SET__

import json
import os
import sys

try:
    import mset
except ImportError:
    mset = None

MODEL_FILE = r"__MODEL_PATH__"
SOURCE_MODEL_FILE = r"__SOURCE_MODEL_PATH__"
PAIRS_FILE = r"__PAIRS_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
OUTPUT_DIR = r"__OUTPUT_DIR__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

# Pick up shared Toolbag-side helpers from the engine package dir.
sys.path.insert(0, r"__TOOLBAG_HELPERS_DIR__")
from _toolbag_helpers import ToolbagHelpers

# Bake output (parameters.py). PADDING/BITS are managed values -- derived
# host-side by TemplateParams.derive_bake_values (padding from the map size
# via pythontk's UV-padding primitive, bit depth from the per-map output
# templates), never exposed as widgets.
BAKE_SIZE = __BAKE_SIZE__
BAKE_SAMPLES = __BAKE_SAMPLES__
BAKE_PADDING = __BAKE_PADDING__
BAKE_BITS = __BAKE_BITS__
OUTPUT_FORMAT = __OUTPUT_FORMAT__

# Map toggles.
MAP_NORMAL = __MAP_NORMAL__
MAP_AO = __MAP_AO__
MAP_CURVATURE = __MAP_CURVATURE__
MAP_THICKNESS = __MAP_THICKNESS__
MAP_POSITION = __MAP_POSITION__
MAP_MATID = __MAP_MATID__
MAP_ALBEDO = __MAP_ALBEDO__
MAP_ROUGHNESS = __MAP_ROUGHNESS__
MAP_METALNESS = __MAP_METALNESS__
MAP_EMISSIVE = __MAP_EMISSIVE__

# Source/target suffix pairing (single-file fallback).
HIGH_SUFFIX = __HIGH_SUFFIX__
LOW_SUFFIX = __LOW_SUFFIX__
SUFFIX_INCLUDE_CHILDREN = __SUFFIX_INCLUDE_CHILDREN__
CAGE_OFFSET = __CAGE_OFFSET__
IGNORE_BACKFACES = __IGNORE_BACKFACES__


# Enabled bake maps: Toolbag display name (``baker.getMap`` key; verified
# against Toolbag 5.02 -- e.g. tangent normals are "Normals", plural) mapped
# to the output filename suffix we want. Suffixes follow the pythontk
# MapFactory taxonomy so the Maya-side material wiring resolves each map's
# type from its filename alone.
_ENABLED_MAPS = {}
if MAP_NORMAL:
    _ENABLED_MAPS["Normals"] = "Normal_OpenGL"
if MAP_AO:
    _ENABLED_MAPS["Ambient Occlusion"] = "AO"
if MAP_CURVATURE:
    _ENABLED_MAPS["Curvature"] = "Curvature"
if MAP_THICKNESS:
    _ENABLED_MAPS["Thickness"] = "Thickness"
if MAP_POSITION:
    _ENABLED_MAPS["Position"] = "Position"
if MAP_MATID:
    _ENABLED_MAPS["Material ID"] = "MatID"
if MAP_ALBEDO:
    _ENABLED_MAPS["Albedo"] = "Base_Color"
if MAP_ROUGHNESS:
    _ENABLED_MAPS["Roughness"] = "Roughness"
if MAP_METALNESS:
    _ENABLED_MAPS["Metalness"] = "Metallic"
if MAP_EMISSIVE:
    _ENABLED_MAPS["Emissive"] = "Emissive"


def _output_stem():
    """Output path stem: Toolbag derives per-map filenames as
    <stem>_<texture set>_<suffix>.<ext>.

    The stem is a constant, NOT the scene/model name: the texture set (= the
    material) is the identity the maps should carry, and the roundtrip host
    strips the '<stem>_' prefix on relocation so production files land as
    <material>_<suffix>.<ext>. The literal below mirrors
    TemplateParams.BAKE_OUTPUT_STEM (host-side single source of truth --
    this script runs inside Toolbag and cannot import it).
    """
    ext = (OUTPUT_FORMAT or "png").lstrip(".").lower()
    return os.path.join(OUTPUT_DIR, "bake.%s" % ext)


def _set(obj, attr, value):
    """Best-effort setattr with a log line naming any attribute that drifted."""
    try:
        setattr(obj, attr, value)
        return True
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log(
            "  [bake] %s=%r failed: %s: %s" % (attr, value, type(exc).__name__, exc)
        )
        return False


def _apply_import_prefs():
    """Pin the import preferences the bake depends on; return a restore callable.

    Two user preferences can silently break the surface-transfer bake:

    * "import FBX without materials" -- no materials means nothing to wire,
      so albedo/roughness/metalness bake flat.
    * "import models as references" -- reference wrappers re-instantiate
      when their meshes are reparented into the baker's containers, which
      resets the imported materials and wipes any wiring already applied.

    Attribute names are probed defensively -- a Toolbag build without them
    just logs and imports as configured.
    """
    try:
        prefs = mset.getPreferences()
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("[bake] getPreferences failed: %s" % exc)
        return lambda: None
    wanted = {
        "importFbxWithMaterials": True,
        "importWithMaterials": True,
        "importModelsAsReferences": False,
    }
    restores = []
    for attr, value in wanted.items():
        if not hasattr(prefs, attr):
            continue
        original = getattr(prefs, attr)
        if original != value:
            try:
                setattr(prefs, attr, value)
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("[bake] could not set %s: %s" % (attr, exc))
                continue
            restores.append((attr, original))
            ToolbagHelpers.log(
                "[bake] Pinned %s=%s for this run (was %s)." % (attr, value, original)
            )

    def _restore():
        for attr, original in restores:
            try:
                setattr(prefs, attr, original)
            except Exception:  # noqa: BLE001
                pass

    return _restore


def _base_name(name):
    """Mesh leaf name with FBX '.001' duplicate suffixes and source/target tags stripped."""
    stem = name.rsplit(".", 1)[0] if "." in name else name
    for suffix in (HIGH_SUFFIX, LOW_SUFFIX):
        if suffix and stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    return stem.lower()


def _configure_baker(baker):
    _set(baker, "outputPath", _output_stem())
    _set(baker, "outputWidth", BAKE_SIZE)
    _set(baker, "outputHeight", BAKE_SIZE)
    _set(baker, "outputSamples", BAKE_SAMPLES)
    _set(baker, "outputBits", BAKE_BITS)
    _set(baker, "edgePaddingSize", float(BAKE_PADDING))
    _set(baker, "ignoreBackfaces", IGNORE_BACKFACES)

    # Deterministic map roster: the user's Toolbag remembers per-map enables
    # and custom suffixes across sessions, so start from all-off and enable
    # exactly what the panel asked for, with our canonical suffixes.
    try:
        for m in baker.getAllMaps() or []:
            m.enabled = False
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("[bake] Could not reset map roster: %s" % exc)
    for display_name, suffix in _ENABLED_MAPS.items():
        try:
            m = baker.getMap(display_name)
            m.enabled = True
            m.suffix = suffix
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log(
                "  [bake] map %r unavailable: %s" % (display_name, exc)
            )
    ToolbagHelpers.log(
        "[bake] Maps enabled: %s" % ", ".join(sorted(_ENABLED_MAPS))
    )

    # Cage offset: the attribute moved across Toolbag versions; try the
    # known names on the baker itself (per-target offsets are handled when
    # groups are built).
    for attr in ("maxOffset", "maxOffsetDistance"):
        if hasattr(baker, attr):
            if _set(baker, attr, CAGE_OFFSET):
                break


def _bake_group_targets(group):
    """Return the (source, target) child containers of a bake group.

    Toolbag names the containers 'High' and 'Low' -- its API vocabulary,
    kept verbatim here; everywhere else this script says source/target.
    """
    source = target = None
    try:
        for child in group.getChildren() or []:
            cname = getattr(child, "name", "")
            if cname == "High":
                source = child
            elif cname == "Low":
                target = child
    except Exception as exc:  # noqa: BLE001
        ToolbagHelpers.log("  [bake] couldn't enumerate group children: %s" % exc)
    return source, target


def _add_pair_group(baker, name, sources, targets):
    """Create one bake group and parent *sources*/*targets* into its containers."""
    group = baker.addGroup(name)
    source_parent, target_parent = _bake_group_targets(group)
    if source_parent is None or target_parent is None:
        ToolbagHelpers.log(
            "  [bake] group %r children unexpected; skipping." % name
        )
        return 0
    # Cage/offset options live on the target ('Low') container.
    for attr in ("maxOffset", "maxOffsetDistance", "cageOffset"):
        if hasattr(target_parent, attr):
            _set(target_parent, attr, CAGE_OFFSET)
            break
    wired = 0
    for o in targets:
        try:
            o.parent = target_parent
            wired += 1
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("  [bake] could not parent target %r: %s" % (o.name, exc))
    for o in sources:
        try:
            o.parent = source_parent
            wired += 1
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("  [bake] could not parent source %r: %s" % (o.name, exc))
    return wired


def _build_groups(baker, sources, targets):
    """One bake group per matching leaf name; leftovers share a 'Rest' group.

    Name-matched groups isolate each source/target pair's rays -- with the
    whole set in one group, nearby props project onto each other. Unmatched
    meshes still bake, just without that isolation.
    """
    by_name_source = {}
    for o in sources:
        by_name_source.setdefault(_base_name(getattr(o, "name", "")), []).append(o)

    paired = 0
    rest_sources = []
    rest_targets = []
    used_source_names = set()
    by_name_target = {}
    for o in targets:
        by_name_target.setdefault(_base_name(getattr(o, "name", "")), []).append(o)

    for base, target_meshes in sorted(by_name_target.items()):
        source_meshes = by_name_source.get(base)
        if source_meshes:
            used_source_names.add(base)
            _add_pair_group(baker, base or "pair", source_meshes, target_meshes)
            paired += 1
        else:
            rest_targets.extend(target_meshes)
    for base, source_meshes in by_name_source.items():
        if base not in used_source_names:
            rest_sources.extend(source_meshes)

    if rest_sources or rest_targets:
        ToolbagHelpers.log(
            "[bake] %d unpaired mesh(es) -> shared 'Rest' group "
            "(source=%d target=%d)." % (len(rest_sources) + len(rest_targets), len(rest_sources), len(rest_targets))
        )
        _add_pair_group(baker, "Rest", rest_sources, rest_targets)
    ToolbagHelpers.log("[bake] Built %d name-matched bake group(s)." % paired)


def _enable_texture_sets(baker):
    """Switch to per-material texture sets so each material bakes its own maps.

    A single shared set would stack every material's UV layout into one
    image. ``tileMode`` gates the texture-set API; the enum value for
    "Multiple Texture Sets" is probed since only 0 (single) is documented.
    On total failure the original mode is restored so the baker isn't left
    in whatever mode the last failed probe set.
    """
    original_mode = getattr(baker, "tileMode", 0)
    for tile_mode in (1, 2):
        try:
            baker.tileMode = tile_mode
            count = baker.getTextureSetCount()
        except Exception:  # noqa: BLE001
            continue
        names = []
        for i in range(count):
            try:
                names.append(baker.getTextureSetName(i))
                baker.setTextureSetWidth(i, BAKE_SIZE)
                baker.setTextureSetHeight(i, BAKE_SIZE)
                baker.setTextureSetEnabled(i, True)
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("  [bake] texture set %d: %s" % (i, exc))
        # ``str()`` per name: a Toolbag build that returns a non-string here
        # must not take down the whole bake setup on a log line.
        ToolbagHelpers.log(
            "[bake] tileMode=%d -> %d texture set(s): %s"
            % (tile_mode, count, ", ".join(str(n) for n in names))
        )
        return count
    _set(baker, "tileMode", original_mode)
    ToolbagHelpers.log(
        "[bake] Texture sets unavailable; baking a single shared set."
    )
    return 0


def main():
    ToolbagHelpers.begin_log(MANIFEST_FILE or MODEL_FILE)
    if not os.path.isfile(MODEL_FILE):
        ToolbagHelpers.log("ERROR: Model file not found: %s" % MODEL_FILE)
        return

    restore_prefs = _apply_import_prefs()
    try:
        imported = mset.importModel(MODEL_FILE)
        if imported is None:
            ToolbagHelpers.log("ERROR: importModel returned None.")
            return
        # In the two-file flow these are exactly the target meshes; in
        # the single-file fallback the batch holds BOTH sides and is split
        # below.
        model_meshes = ToolbagHelpers.collect_mesh_objects(imported)

        source_meshes = []
        if SOURCE_MODEL_FILE and os.path.isfile(SOURCE_MODEL_FILE):
            imported_source = mset.importModel(SOURCE_MODEL_FILE)
            source_meshes = ToolbagHelpers.collect_mesh_objects(imported_source)
    finally:
        restore_prefs()

    if source_meshes:
        # Two-file flow: the import batches ARE the classification.
        sources, targets = source_meshes, model_meshes
        ToolbagHelpers.log(
            "[bake] Two-file import: %d target / %d source mesh(es)."
            % (len(targets), len(sources))
        )
    else:
        # Single-file fallback: sidecar first, then name-suffix chain walk.
        pre_classified = {}
        if PAIRS_FILE and os.path.isfile(PAIRS_FILE):
            try:
                with open(PAIRS_FILE, "r", encoding="utf-8") as fh:
                    pre_classified = json.load(fh) or {}
            except Exception as exc:  # noqa: BLE001
                ToolbagHelpers.log("[bake] Failed to read pairs sidecar: %s" % exc)
        sources, targets, others = ToolbagHelpers.split_source_target(
            model_meshes,
            HIGH_SUFFIX,
            LOW_SUFFIX,
            pre_classified=pre_classified,
            include_children=SUFFIX_INCLUDE_CHILDREN,
        )
        ToolbagHelpers.log(
            "[bake] Suffix pairing: source=%d target=%d other=%d"
            % (len(sources), len(targets), len(others))
        )
        if not sources:
            ToolbagHelpers.log(
                "[bake] WARNING: no bake source resolved. Define the scene's "
                "Bake Source set in the bridge panel or use the "
                "name-suffix convention."
            )

    baker = mset.BakerObject()
    _configure_baker(baker)
    _build_groups(baker, sources, targets)
    _enable_texture_sets(baker)

    # Wire the Maya materials (with staged/unpacked textures) onto the
    # imported Toolbag materials -- the surface-transfer maps (Albedo /
    # Roughness / Metalness / Emissive) sample exactly these. Deliberately
    # LAST, after the baker groups exist: wiring applied before the meshes
    # are reparented can be reset by model re-instantiation. Color maps stay
    # sRGB-flagged: the bake writes sRGB-encoded output from the linear
    # sample (verified: flat linear 0.5 bakes to 188), so an sRGB-sampled
    # source round-trips as an identity copy of the texel values.
    if MANIFEST_FILE and os.path.isfile(MANIFEST_FILE):
        ToolbagHelpers.wire_materials_from_manifest(MANIFEST_FILE)

    if SHOULD_QUIT:
        # Headless run: bake before quitting so the bake actually happens.
        # Bake BEFORE any save: saveScene re-serializes the just-wired
        # texture bindings into a state that samples with an extra sRGB
        # conversion (verified on Toolbag 5.02 -- wiring -> save -> bake
        # shifted every color transfer, while wiring -> bake is an identity
        # copy of the source texels).
        ToolbagHelpers.log("Running bake ...")
        try:
            baker.bake()
            ToolbagHelpers.log("Bake finished.")
        except Exception as exc:  # noqa: BLE001
            ToolbagHelpers.log("Bake failed: %s" % exc)

    if SAVE_PATH:
        ToolbagHelpers.log("Saving bake scene: %s" % SAVE_PATH)
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        ToolbagHelpers.log("Quitting Toolbag ...")
        mset.quit()


if __name__ == "__main__":
    main()
