# Marmoset Toolbag import & material-setup script.
# Generated by MarmosetEngine -- do not edit by hand.

"""Open the model in Toolbag and wire materials from the manifest.

Imports the model, then reads the JSON material manifest (if any) to
recreate each source shader on the Toolbag side (base color / normal /
roughness texture slots populated from disk paths recorded at export
time). With no manifest, it simply imports the model."""

# Bridge metadata -- consumed by MarmosetEngine before substitution.
BRIDGE_MODES = ("send_to",)

import os
import sys

try:
    import mset
except ImportError:
    mset = None

MODEL_FILE = r"__MODEL_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

# Pick up shared Toolbag-side helpers from the engine package dir.
sys.path.insert(0, r"__TOOLBAG_HELPERS_DIR__")
from _toolbag_helpers import wire_materials_from_manifest, begin_log, log


def main():
    log_path = begin_log(MANIFEST_FILE)
    log(f"[->Toolbag] Model:    {MODEL_FILE}")
    log(f"[->Toolbag] Manifest: {MANIFEST_FILE}")
    if log_path:
        log(f"[->Toolbag] Log:      {log_path}")

    if not os.path.isfile(MODEL_FILE):
        log("ERROR: Model file not found.")
        return

    mset.importModel(MODEL_FILE)
    wire_materials_from_manifest(MANIFEST_FILE, verbose=True)

    if SAVE_PATH:
        print(f"Saving scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        print("Quitting Toolbag...")
        mset.quit()


if __name__ == "__main__":
    main()
