# Marmoset Toolbag look-dev script: import + apply Sky + wire materials + frame.
# Generated by MarmosetEngine -- do not edit by hand.

"""Open the model in Toolbag, apply a Sky preset, and frame the model.

Imports the model, applies the chosen Marmoset Sky for instant lighting
context, wires materials from the manifest (if any), and auto-frames the
selection in the viewport so the user drops into a ready-to-render
look-dev scene."""

# Bridge metadata -- consumed by MarmosetEngine before substitution.
BRIDGE_MODES = ("send_to",)

# Host-side export scope (read by the bridge slots before launch; echoed here so the panel
# exposes the Scope combo): scope=__SCOPE__

import os
import sys

try:
    import mset
except ImportError:
    mset = None

MODEL_FILE = r"__MODEL_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

SKY_PRESET = __SKY_PRESET__
FRAME_SELECTION = __FRAME_SELECTION__

# Pick up shared Toolbag-side helpers from the engine package dir.
sys.path.insert(0, r"__TOOLBAG_HELPERS_DIR__")
from _toolbag_helpers import ToolbagHelpers


def main():
    log_path = ToolbagHelpers.begin_log(MANIFEST_FILE)
    ToolbagHelpers.log(f"[->Toolbag] Model:    {MODEL_FILE}")
    ToolbagHelpers.log(f"[->Toolbag] Manifest: {MANIFEST_FILE}")
    if log_path:
        ToolbagHelpers.log(f"[->Toolbag] Log:      {log_path}")

    if not os.path.isfile(MODEL_FILE):
        ToolbagHelpers.log("ERROR: Model file not found.")
        return

    mset.importModel(MODEL_FILE)

    # Sky first, then wire. The previous order (wire -> sky) was reported
    # to leave Toolbag with no textures hooked up; the file log written by
    # begin_log() now records exactly what happened so the next run is
    # debuggable even though send_to mode has no stdout the user can see.
    if SKY_PRESET:
        ToolbagHelpers.apply_sky_preset(SKY_PRESET)

    ToolbagHelpers.wire_materials_from_manifest(MANIFEST_FILE, verbose=True)

    if FRAME_SELECTION:
        ToolbagHelpers.frame_in_viewport()

    if SAVE_PATH:
        print(f"Saving lookdev scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        print("Quitting Toolbag...")
        mset.quit()


if __name__ == "__main__":
    main()
