# Marmoset Toolbag look-dev script: import + wire materials + apply Sky + frame.
# Generated by mayatk.mat_utils.marmoset_bridge.MarmosetBridge -- do not edit by hand.

# Bridge metadata -- consumed by MarmosetBridge before substitution.
BRIDGE_MODES = ("send_to",)

import json
import os

try:
    import mset
except ImportError:
    mset = None

FBX_FILE = r"__FBX_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

SKY_PRESET = __SKY_PRESET__
FRAME_SELECTION = __FRAME_SELECTION__


SLOT_MAP = {
    "baseColor": ("albedo", "Albedo Map"),
    "normal": ("surface", "Normal Map"),
    "roughness": ("microsurface", "Microsurface Map"),
    "metallic": ("reflectivity", "Metalness Map"),
    "ambientOcclusion": ("occlusion", "Occlusion Map"),
    "emission": ("emissive", "Emissive Map"),
    "opacity": ("transparency", "Transparency Map"),
}


def _find_material(name, scene_mats):
    for m in scene_mats:
        if m.name == name:
            return m
    for m in scene_mats:
        if m.name.startswith(name) or name in m.name:
            return m
    return None


def _wire_materials():
    if not os.path.isfile(MANIFEST_FILE):
        return
    with open(MANIFEST_FILE, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    mat_map = data.get("materials", {})
    if not mat_map:
        return

    scene_mats = [
        o for o in mset.getAllObjects() if isinstance(o, mset.MaterialObject)
    ]
    for mat_name, slots in mat_map.items():
        tb_mat = _find_material(mat_name, scene_mats)
        if tb_mat is None:
            continue
        for slot_key, tex_path in slots.items():
            mapping = SLOT_MAP.get(slot_key)
            if not mapping:
                continue
            module_attr, field_name = mapping
            try:
                sub = getattr(tb_mat, module_attr, None)
                if sub is None:
                    continue
                sub.getField(field_name).set(tex_path)
            except Exception:
                pass


def _apply_sky():
    """Load a ``.tbsky`` preset onto the scene's existing SkyObject."""
    if not SKY_PRESET:
        return
    try:
        skies = [o for o in mset.getAllObjects() if isinstance(o, mset.SkyObject)]
        if not skies:
            return
        # API method is loadPreset, not importPreset.
        skies[0].loadPreset(SKY_PRESET)
    except Exception as e:
        print(f"[lookdev] Sky preset load failed: {e}")


def _frame():
    """Frame the imported scene in the viewport, if Toolbag exposes a hook.

    Toolbag 4/5 doesn't have a documented Python "frame scene" call, so we
    try the menu route first and fall back to selecting + framing via the
    main camera. Both are best-effort -- failure is harmless.
    """
    if not FRAME_SELECTION:
        return
    try:
        # Bound menu item exists in every Toolbag with the standard layout.
        mset.callMenuItem("View/Frame Selection")
        return
    except Exception:
        pass
    try:
        for o in mset.getAllObjects():
            if hasattr(o, "frameInView"):
                o.frameInView()
                return
    except Exception:
        pass


def main():
    if not os.path.isfile(FBX_FILE):
        print("ERROR: FBX file not found.")
        return

    mset.importModel(FBX_FILE)
    _wire_materials()
    _apply_sky()
    _frame()

    if SAVE_PATH:
        print(f"Saving lookdev scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        print("Quitting Toolbag...")
        mset.quit()


if __name__ == "__main__":
    main()
