# Marmoset Toolbag look-dev script: import + apply Sky + wire materials + frame.
# Generated by mayatk.mat_utils.marmoset_bridge.MarmosetBridge -- do not edit by hand.

# Bridge metadata -- consumed by MarmosetBridge before substitution.
BRIDGE_MODES = ("send_to",)

import os
import sys

try:
    import mset
except ImportError:
    mset = None

FBX_FILE = r"__FBX_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
SAVE_PATH = r"__SAVE_PATH__"
SHOULD_QUIT = __SHOULD_QUIT__

SKY_PRESET = __SKY_PRESET__
FRAME_SELECTION = __FRAME_SELECTION__

# Pick up shared Toolbag-side helpers from the marmoset_bridge package dir.
sys.path.insert(0, r"__TOOLBAG_HELPERS_DIR__")
from _toolbag_helpers import (
    wire_materials_from_manifest,
    apply_sky_preset,
    frame_in_viewport,
    begin_log,
    log,
)


def main():
    log_path = begin_log(MANIFEST_FILE)
    log(f"[Maya->Toolbag] FBX:      {FBX_FILE}")
    log(f"[Maya->Toolbag] Manifest: {MANIFEST_FILE}")
    if log_path:
        log(f"[Maya->Toolbag] Log:      {log_path}")

    if not os.path.isfile(FBX_FILE):
        log("ERROR: FBX file not found.")
        return

    mset.importModel(FBX_FILE)

    # Sky first, then wire. The previous order (wire -> sky) was reported
    # to leave Toolbag with no textures hooked up; the file log written by
    # begin_log() now records exactly what happened so the next run is
    # debuggable even though send_to mode has no stdout the user can see.
    if SKY_PRESET:
        apply_sky_preset(SKY_PRESET)

    wire_materials_from_manifest(MANIFEST_FILE, verbose=True)

    if FRAME_SELECTION:
        frame_in_viewport()

    if SAVE_PATH:
        print(f"Saving lookdev scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        print("Quitting Toolbag...")
        mset.quit()


if __name__ == "__main__":
    main()
