# coding=utf-8
"""Schema for a *behavior* template file, defined as a dataclass.

:class:`BehaviorSpec` is the single source of truth for the shape of a behavior
``.yaml`` (the keying recipes applied to shot objects — fades, audio clips, …).
Like the CSV :class:`~...mapping._spec.MappingSpec`, it validates a loaded file,
generates a copy-me skeleton, and powers the generated ``BEHAVIOR_FORMAT.md`` —
all from one definition.  This is the second consumer of the shared
:class:`~pythontk.TemplateSet` machinery, so behavior and mapping templates are
discovered, validated, and documented the *same* way instead of via two
parallel loaders.

This module is Maya-free (pure schema), so it imports and validates without the
DCC runtime even though its sibling :mod:`._behaviors` applies keys via ``cmds``.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Dict, List

from pythontk import SchemaSpec, spec_field

# Verification strategies understood by ``verify_behavior`` (see _behaviors.py).
KNOWN_VERIFY_MODES = ("exact", "values_in_range", "audio_clip")


def validate_duration(value: Any) -> List[str]:
    """``duration`` is a frame count or the literal ``"from_source"``."""
    if value is None or value == "from_source":
        return []
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return []
    return [f'must be a number or "from_source", got {value!r}']


def validate_verify(value: Any) -> List[str]:
    if not isinstance(value, dict):
        return ["expected a mapping with a 'mode' key"]
    mode = value.get("mode")
    if mode is not None and mode not in KNOWN_VERIFY_MODES:
        return [f"mode {mode!r} is not one of {list(KNOWN_VERIFY_MODES)}"]
    return []


def validate_attributes(value: Any) -> List[str]:
    """``attributes`` = {attr: {in?/out?: {offset,duration,values,anchor,tangent}}}."""
    if not isinstance(value, dict):
        return ["expected a mapping of {attribute: {in/out: key-block}}"]
    errs: List[str] = []
    for attr, phases in value.items():
        if not isinstance(phases, dict):
            errs.append(f"{attr!r} must map phase ('in'/'out') to a key block")
            continue
        for phase, block in phases.items():
            if phase not in ("in", "out"):
                errs.append(f"{attr}.{phase}: phase must be 'in' or 'out'")
            if not isinstance(block, dict):
                errs.append(f"{attr}.{phase}: must be a mapping")
                continue
            vals = block.get("values")
            if vals is not None and not isinstance(vals, list):
                errs.append(f"{attr}.{phase}.values: must be a list of numbers")
    return errs


@dataclass
class BehaviorSpec(SchemaSpec):
    """Schema for one behavior template (see ``BEHAVIOR_FORMAT.md``)."""

    description: str = spec_field(
        help="One-line description of what the behavior does.",
        example="Fade objects in at shot start via visibility.",
        default="",
    )
    kind: List[str] = spec_field(
        help='Object kinds this applies to (e.g. ["scene"] or ["audio"]).',
        example=["scene"],
        default_factory=lambda: ["scene"],
    )
    duration: Any = spec_field(
        help='Length in frames, or "from_source" to size to an audio clip.',
        validate=validate_duration,
        default=None,
    )
    attributes: Dict[str, Any] = spec_field(
        help="Keyframe blocks per attribute, split into in/out phases.",
        validate=validate_attributes,
        example={
            "visibility": {
                "in": {
                    "anchor": "start",
                    "offset": 0,
                    "duration": 15,
                    "values": [0.0, 1.0],
                    "tangent": "linear",
                }
            }
        },
        default=None,
    )
    verify: Dict[str, Any] = spec_field(
        help="How verification checks the authored keys.",
        validate=validate_verify,
        example={"mode": "values_in_range"},
        default=None,
    )


def format_markdown() -> str:
    """Generate the full ``BEHAVIOR_FORMAT.md`` reference from the schema SSoT."""
    skeleton = json.dumps(BehaviorSpec.skeleton(), indent=2)
    modes = ", ".join(f"`{m}`" for m in KNOWN_VERIFY_MODES)
    return f"""<!-- GENERATED by behaviors/_spec.py:format_markdown() — do not edit by hand. -->
# Shot Manifest — Behavior Template Format

A *behavior* is a `.yaml` file describing a keying recipe (a fade, an audio
clip, …) that the Shot Manifest applies to objects over a shot's time range.
Behavior names are referenced from a mapping's `default_behaviors` and from a
step's detected behaviors.

## Adding your own

Built-in behaviors ship read-only. **Your own** live in your writable templates
folder under `user_config_root()/mayatk/shot_manifest_behaviors/`; a user file
shadows a built-in of the same name. They are discovered automatically and
available everywhere a behavior name is accepted. YAML is used (not JSON) so you
can comment your templates inline.

{BehaviorSpec.to_markdown(title="Top-level keys")}

Each `attributes.<attr>.<phase>` block holds: `anchor` (`start` | `end` | a
float 0–1), `offset` (frames), `duration` (frames), `values` (list keyframed
across the block), and `tangent` (e.g. `linear`, `step`).

Verification (`verify.mode`) is one of: {modes}.

## Skeleton (a scene fade)

```yaml
{skeleton}
```

(The skeleton is shown as JSON for compactness — YAML accepts the same data, and
your own files may use YAML comments.)
"""
