# Marmoset Toolbag baking setup script.
# Generated by mayatk.mat_utils.marmoset.MarmosetBridge
import json
import os

try:
    import mset
except ImportError:
    mset = None

FBX_FILE = r"__FBX_PATH__"
MANIFEST_FILE = r"__MANIFEST_PATH__"
SAVE_PATH = r"__SAVE_PATH__"
try:
    SHOULD_QUIT = __SHOULD_QUIT__
except NameError:
    SHOULD_QUIT = False


def main():
    if not os.path.isfile(FBX_FILE):
        print("ERROR: FBX file not found.")
        return

    # 1. Import model
    # mset.importModel returns the list of objects imported
    imported_objects = mset.importModel(FBX_FILE)

    # 2. Setup Baker
    baker = mset.BakerObject()
    baker.name = "Bake Project"

    # Basic Quick Loader logic: assign imported objects to baker
    # (Assuming Quick Loader functionality or manual assignment via specific groups if they exist)
    # For a simple setup, we might just leave them in the scene,
    # but let's try to add them to the baker if possible,
    # or just create the baker so the user can drag/drop.

    # Strategy: Group Low/High based on naming?
    # For this template, we simply create the baker.
    # Advanced: Iterate imported_objects and sort into baker.getBakerGroup()

    # 3. Apply settings from manifest if needed (e.g. materials for ID maps)
    # (Skipping manifest material wiring for bake setup unless specifically requested)

    # 4. Save & (Optionally) Quit
    if SAVE_PATH and not SAVE_PATH.startswith("__"):
        print(f"Saving bake scene: {SAVE_PATH}")
        mset.saveScene(SAVE_PATH)

    if SHOULD_QUIT:
        # In a real bake scenario, we might run baker.bake() here before quitting.
        # baker.bake()
        print("Quitting Toolbag...")
        mset.quit()


if __name__ == "__main__":
    import mset

    main()
