# !/usr/bin/python
# coding=utf-8
"""A live Viewport 2.0 preview of a horizon rig: the artist drags the light
and sees the outline morph, exactly as Unity and the WebXR viewer will show it.

Both DCC rig types show the same silhouette texture in the viewport -- the
horizon map rides in the emission slot at weight 0 as a data carrier that only
the engines interpret. This module is R7 (*the DCC shows the artist something
true*) for the horizon type: a hardware shader on the plane that evaluates the
map per fragment from the live source, contact and ground.

The evaluation is not written here. It is ``pythontk/geo_utils/shadow_horizon.glsl``
-- the one text every engine and both DCCs run -- assembled at run time through
:meth:`pythontk.ShadowHorizon.shader_source` behind a Maya host prologue: the
uniform block, the ``.ogsfx`` / ``.fx`` scaffolding, and ``SH_Fetch``, the
texel hook that owns Maya's texture-row convention. Maya is a Python process
when it needs the shader, so it carries no mirror.

**Display state, never rig content.** The preview swaps only the plane's
shading-group *membership*: the real ``standardSurface`` network stays intact
and connected, so every accessor that walks it (the silhouette's file node,
the opacity chain, the rebuild's shader sniff) keeps resolving through the
stored snapshot. Nothing about it is exported -- the ``"shadow"`` export
preparer detaches every preview before an FBX is written and republishes the
metadata afterwards -- and a scene reopened with a preview on rebinds the
effect from the file beside the horizon PNG.

**Two devices, one body.** Viewport 2.0 runs DirectX 11 or OpenGL Core Profile
per the user's preference (``MAYA_VP2_DEVICE_OVERRIDE`` per process). A
``dx11Shader`` node compiles the ``.fx`` spelling, a ``GLSLShader`` node the
``.ogsfx``; their uniforms bind identically, so the Python is shared and only
the language, the node type and the file extension differ. Legacy OpenGL
(Pixel Shader 4) cannot compile the effect and is refused with the message
that says so. Both bind the map promoted to 16 bits (``TEXTURE_SUFFIX``): the
OpenGL path sRGB-decodes any 8-bit texture a ``GLSLShader`` samples, whatever
the file node says, and a 16-bit texture has no sRGB format to decode.
"""

from __future__ import annotations

import json
import os
import re
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

try:
    import maya.cmds as cmds
except ImportError as error:
    print(__file__, error)
import pythontk as ptk

from mayatk.core_utils._core_utils import CoreUtils
from mayatk.env_utils._env_utils import EnvUtils
from mayatk.mat_utils._mat_utils import MatUtils

__all__ = ["ShadowPreview"]


# The host prologues. ``{body}`` takes ``ShadowHorizon.shader_source(language)``
# verbatim; everything else is Maya's: semantics, annotations, the texel hook.
#
# SH_Fetch's row convention, MEASURED (shadow_preview_device_check.py, both
# devices): a texel fetch at row 0 reads the PNG's TOP row -- Maya's loader
# does not flip the image for texelFetch / Load the way its UV convention
# (V = 0 at the bottom) might suggest. So a tile's row 0 (the PNG's top row,
# the frame's b0 edge) maps straight through, with no flip; the bottom-up
# branch stays so the next measurement can refute this one in a single line.
# Unity's Load, by contrast, needs the flip.

_OGSFX = """#version 410
// GENERATED by mayatk.rig_utils.shadow_preview -- rewritten on every attach
// from pythontk/geo_utils/shadow_horizon.glsl. Not a source file: edit that.

uniform mat4 gWVPXf : WorldViewProjection < string UIWidget = "None"; >;
uniform mat4 gWorldXf : World < string UIWidget = "None"; >;

// The contact frame in WORLD space, and the source -- driven live by DG nodes.
uniform vec3 gOrigin < string UIName = "Contact Origin (world)"; > = {{0.0, 0.0, 0.0}};
uniform vec3 gAxisA < string UIName = "Frame A (world)"; > = {{1.0, 0.0, 0.0}};
uniform vec3 gAxisB < string UIName = "Frame B (world)"; > = {{0.0, 0.0, 1.0}};
uniform vec3 gAxisUp < string UIName = "Frame Up (world)"; > = {{0.0, 1.0, 0.0}};
uniform vec3 gSource < string UIName = "Source (world)"; > = {{0.0, 5.0, 0.0}};
uniform float gSourceW < string UIName = "Source: 1 = position, 0 = shine direction"; > = 1.0;
uniform float gSourceDiameter < string UIName = "Source Diameter"; > = 0.0;
uniform float gSourceAngle < string UIName = "Source Angle (rad)"; > = 0.0;
uniform float gGround < string UIName = "Ground (frame height)"; > = 0.0;
// The map's layout -- set once per plane from the record's horizon block.
// Annotated like every other tweakable: the plugins expose an unannotated
// uniform as an attribute, but whether its VALUE reaches the shader is
// what shadow_preview_device_check.py measures per device.
uniform float gSize < string UIName = "Footprint Pixels"; > = 128.0;
uniform float gSpans < string UIName = "Spans per Column"; > = 2.0;
uniform float gLevels < string UIName = "Pyramid Levels"; > = 7.0;
uniform float gBoundsA0 < string UIName = "Footprint a0"; > = -1.0;
uniform float gBoundsA1 < string UIName = "Footprint a1"; > = 1.0;
uniform float gBoundsB0 < string UIName = "Footprint b0"; > = -1.0;
uniform float gBoundsB1 < string UIName = "Footprint b1"; > = 1.0;
uniform float gHeightScale < string UIName = "Height Scale"; > = 1.0;
uniform float gRectSX < string UIName = "Rect Scale X"; > = 1.0;
uniform float gRectSY < string UIName = "Rect Scale Y"; > = 1.0;
uniform float gRectOX < string UIName = "Rect Offset X"; > = 0.0;
uniform float gRectOY < string UIName = "Rect Offset Y"; > = 0.0;
uniform float gOpacity < string UIName = "Opacity"; > = 1.0;
uniform float gIntensity < string UIName = "Intensity"; > = 1.0;

// Bound to the map's 16-bit promotion (TEXTURE_SUFFIX), never the 8-bit map:
// on this path VP2 sRGB-decodes any 8-bit texture -- Raw colour space, colour
// management and MayaGammaCorrection change nothing (measured) -- and a
// 16-bit texture has no sRGB format to decode.
uniform texture2D gHorizonTex <
    string ResourceName = "";
    string UIName = "Horizon Map";
    string ResourceType = "2D";
    string UIWidget = "FilePicker";
>;
// Explicit, mip-free sampler state, and NOT optional: OpenGL's default
// minification filter is mipmapped, and a texture VP2 uploads without mips is
// then INCOMPLETE -- it samples as zeros and textureSize reports 0 x 0
// (measured: the floating layer vanished, then the whole map). NEAREST also
// says what the shader means: the map is data and is never filtered.
uniform sampler2D gHorizonSamp = sampler_state {{
    Texture = <gHorizonTex>;
    TEXTURE_MIN_FILTER = NEAREST;
    TEXTURE_MAG_FILTER = NEAREST;
    TEXTURE_WRAP_S = CLAMP_TO_EDGE;
    TEXTURE_WRAP_T = CLAMP_TO_EDGE;
}};

attribute vs_input {{
    vec3 in_position : POSITION;
}}

attribute vs_to_ps {{
    vec3 ps_world;
}}

attribute ps_output {{
    vec4 colourOut : COLOR0;
}}

GLSLShader VS
{{
    void main()
    {{
        ps_world = (gWorldXf * vec4(in_position, 1.0)).xyz;
        gl_Position = gWVPXf * vec4(in_position, 1.0);
    }}
}}

GLSLShader PS
{{
#define SH_ROWS_FROM_BOTTOM {rows_from_bottom}

// The shared body's texel hook: the map's tiles sit side by side, each S
// texels square, row 0 of a tile the PNG's top row (the frame's b0 edge),
// while the texture's row 0 is whichever edge Maya's loader put there.
vec4 SH_Fetch(int tile, int xi, int yi)
{{
    ivec2 size = textureSize(gHorizonSamp, 0);
    int S = int(gSize + 0.5);
    int px = int(gRectOX * float(size.x) + 0.5) + tile * S + xi;
#if SH_ROWS_FROM_BOTTOM
    int py = int(gRectOY * float(size.y) + 0.5) + (S - 1 - yi);
#else
    int py = int((1.0 - gRectOY - gRectSY) * float(size.y) + 0.5) + yi;
#endif
    return texelFetch(gHorizonSamp, ivec2(px, py), 0);
}}

{body}
    void main()
    {{
        ShField g = ShMakeField(
            int(gSize + 0.5), int(gSpans + 0.5), int(gLevels + 0.5),
            vec4(gBoundsA0, gBoundsA1, gBoundsB0, gBoundsB1), gHeightScale, gGround);
        float a = ShAlpha(g, ps_world, gOrigin, gAxisA, gAxisB, gAxisUp,
                          vec4(gSource, gSourceW), vec2(gSourceDiameter, gSourceAngle));
        colourOut = vec4(0.0, 0.0, 0.0, a * gOpacity * gIntensity);
    }}
}}

technique Main
<
    string Transparency = "Transparent";
>
{{
    pass p0
    {{
        VertexShader (in vs_input, out vs_to_ps) = VS;
        PixelShader (in vs_to_ps, out ps_output) = PS;
    }}
}}
"""

_FX = """// GENERATED by mayatk.rig_utils.shadow_preview -- rewritten on every attach
// from pythontk/geo_utils/shadow_horizon.glsl. Not a source file: edit that.

float4x4 gWVPXf : WorldViewProjection;
float4x4 gWorldXf : World;

// The contact frame in WORLD space, and the source -- driven live by DG nodes.
float3 gOrigin < string UIName = "Contact Origin (world)"; > = {{0.0f, 0.0f, 0.0f}};
float3 gAxisA < string UIName = "Frame A (world)"; > = {{1.0f, 0.0f, 0.0f}};
float3 gAxisB < string UIName = "Frame B (world)"; > = {{0.0f, 0.0f, 1.0f}};
float3 gAxisUp < string UIName = "Frame Up (world)"; > = {{0.0f, 1.0f, 0.0f}};
float3 gSource < string UIName = "Source (world)"; > = {{0.0f, 5.0f, 0.0f}};
float gSourceW < string UIName = "Source: 1 = position, 0 = shine direction"; > = 1.0f;
float gSourceDiameter < string UIName = "Source Diameter"; > = 0.0f;
float gSourceAngle < string UIName = "Source Angle (rad)"; > = 0.0f;
float gGround < string UIName = "Ground (frame height)"; > = 0.0f;
// The map's layout -- set once per plane from the record's horizon block.
// Annotated like every other tweakable: the plugins expose an unannotated
// uniform as an attribute, but whether its VALUE reaches the shader is
// what shadow_preview_device_check.py measures per device.
float gSize < string UIName = "Footprint Pixels"; > = 128.0f;
float gSpans < string UIName = "Spans per Column"; > = 2.0f;
float gLevels < string UIName = "Pyramid Levels"; > = 7.0f;
float gBoundsA0 < string UIName = "Footprint a0"; > = -1.0f;
float gBoundsA1 < string UIName = "Footprint a1"; > = 1.0f;
float gBoundsB0 < string UIName = "Footprint b0"; > = -1.0f;
float gBoundsB1 < string UIName = "Footprint b1"; > = 1.0f;
float gHeightScale < string UIName = "Height Scale"; > = 1.0f;
float gRectSX < string UIName = "Rect Scale X"; > = 1.0f;
float gRectSY < string UIName = "Rect Scale Y"; > = 1.0f;
float gRectOX < string UIName = "Rect Offset X"; > = 0.0f;
float gRectOY < string UIName = "Rect Offset Y"; > = 0.0f;
float gOpacity < string UIName = "Opacity"; > = 1.0f;
float gIntensity < string UIName = "Intensity"; > = 1.0f;

Texture2D gHorizonTex
<
    string ResourceName = "";
    string UIName = "Horizon Map";
    string ResourceType = "2D";
>;

struct VS_INPUT
{{
    float3 Pos : POSITION;
}};

struct VS_TO_PS
{{
    float4 HPos  : SV_Position;
    float3 World : TEXCOORD0;
}};

VS_TO_PS VS(VS_INPUT In)
{{
    VS_TO_PS Out;
    Out.HPos = mul(float4(In.Pos, 1.0f), gWVPXf);
    Out.World = mul(float4(In.Pos, 1.0f), gWorldXf).xyz;
    return Out;
}}

#define SH_ROWS_FROM_BOTTOM {rows_from_bottom}

// The shared body's texel hook: the map's tiles sit side by side, each S
// texels square, row 0 of a tile the PNG's top row (the frame's b0 edge),
// while the texture's row 0 is whichever edge Maya's loader put there.
float4 SH_Fetch(int tile, int xi, int yi)
{{
    uint w, h;
    gHorizonTex.GetDimensions(w, h);
    int S = (int)round(gSize);
    int px = (int)round(gRectOX * (float)w) + tile * S + xi;
#if SH_ROWS_FROM_BOTTOM
    int py = (int)round(gRectOY * (float)h) + (S - 1 - yi);
#else
    int py = (int)round((1.0f - gRectOY - gRectSY) * (float)h) + yi;
#endif
    return gHorizonTex.Load(int3(px, py, 0));
}}

{body}
float4 PS(VS_TO_PS In) : SV_Target
{{
    ShField g = ShMakeField(
        (int)round(gSize), (int)round(gSpans), (int)round(gLevels),
        float4(gBoundsA0, gBoundsA1, gBoundsB0, gBoundsB1), gHeightScale, gGround);
    float a = ShAlpha(g, In.World, gOrigin, gAxisA, gAxisB, gAxisUp,
                      float4(gSource, gSourceW), float2(gSourceDiameter, gSourceAngle));
    return float4(0.0f, 0.0f, 0.0f, a * gOpacity * gIntensity);
}}

technique11 Main
<
    string Transparency = "Transparent";
>
{{
    pass p0
    {{
        SetVertexShader(CompileShader(vs_5_0, VS()));
        SetPixelShader(CompileShader(ps_5_0, PS()));
    }}
}}
"""


class _ShadowPreviewInternal:
    """The DCC-free half: device classification and effect-text assembly."""

    #: Per shader language: the effect extension, the VP2 plugin and its node.
    LANGUAGES: Dict[str, Tuple[str, str, str]] = {
        "glsl": (".ogsfx", "glslShader", "GLSLShader"),
        "hlsl": (".fx", "dx11Shader", "dx11Shader"),
    }
    #: Which language each viewport device compiles. Legacy OpenGL (Pixel
    #: Shader 4) is absent on purpose: the effect needs an integer texel
    #: fetch and bit tests, and the device fails it silently (measured:
    #: ``techniques == []`` with no error).
    LANGUAGE_BY_DEVICE: Dict[str, str] = {"dx11": "hlsl", "glcore": "glsl"}
    #: The effect's file stem, beside the horizon PNG. One file per folder per
    #: language: every plane's effect is the same text, only its uniforms
    #: differ, and a file the scene can find again on reopen is what lets a
    #: saved preview come back instead of rendering a broken shader.
    EFFECT_STEM = "shadow_horizon_preview"
    #: The texture the preview binds: the map promoted to 16 bits, beside it.
    #: VP2's OpenGL path sRGB-decodes any 8-bit texture a ``GLSLShader``
    #: samples -- whatever the file node's colour space, colour management on
    #: or off, ``MayaGammaCorrection`` either way (measured: R came back as
    #: the piecewise sRGB decode of its byte, A untouched, and the floating
    #: layer's ``[G, R]`` band fell under every source elevation). sRGB is an
    #: 8-bit-only texture format, so 16 bits sidestep it; both devices bind
    #: the same file so one texture path is what both device checks verify.
    TEXTURE_SUFFIX = "_preview16.png"
    #: A texel fetch at row 0 reads the PNG's top row on both devices
    #: (measured; see the prologues). Unity's Load is the other way round.
    ROWS_FROM_BOTTOM = False

    @staticmethod
    def classify_device(info: Iterable[str]) -> Optional[str]:
        """``"dx11"``, ``"glcore"``, ``"gl"`` (legacy) or None, from the lines
        ``cmds.ogs(deviceInformation=True)`` reports.

        Read from the live device rather than the ``vp2RenderingEngine``
        preference: ``MAYA_VP2_DEVICE_OVERRIDE`` switches the device per
        process and leaves the preference behind, so the preference is wrong
        exactly when a test is looking.
        """
        text = " ".join(str(line) for line in (info or []))
        if not text.strip():
            return None
        if re.search(r"direct\s*x|direct\s*3\s*d|\bd3d", text, re.IGNORECASE):
            return "dx11"
        if "opengl" not in text.lower():
            return None
        pixel = re.search(r"pixel\D{0,20}(\d+)", text, re.IGNORECASE)
        if pixel and int(pixel.group(1)) >= 5:
            return "glcore"
        return "gl"

    @classmethod
    def effect_text(cls, language: str) -> str:
        """The complete effect for *language*: Maya's prologue around the
        shared body."""
        template = {"glsl": _OGSFX, "hlsl": _FX}[language]
        body = ptk.ShadowHorizon.shader_source(language)
        return template.format(
            body=body, rows_from_bottom=1 if cls.ROWS_FROM_BOTTOM else 0
        )

    @classmethod
    def refusal(cls, device: Optional[str]) -> str:
        """Why a preview cannot be shown on *device* (empty when it can)."""
        if device in cls.LANGUAGE_BY_DEVICE:
            return ""
        if device == "gl":
            return (
                "The horizon preview needs Viewport 2.0 on DirectX 11 or OpenGL "
                "Core Profile; this session runs legacy OpenGL, which cannot "
                "compile it. Preferences > Display > Viewport 2.0 > Rendering "
                "engine, then restart Maya."
            )
        return (
            "The horizon preview needs a Viewport 2.0 device (DirectX 11 or "
            "OpenGL Core Profile); none is available in this session."
        )


class ShadowPreview(_ShadowPreviewInternal, ptk.LoggingMixin):
    """Attach / detach the live horizon preview on shadow planes (module doc)."""

    #: Message attr on the plane that owns the preview shader node.
    SHADER_ATTR = "horizonPreviewShader"
    #: JSON snapshot of the plane's real shading assignment while a preview
    #: stands in for it (``MatUtils.get_shading_assignments``).
    RESTORE_ATTR = "horizonPreviewRestore"
    #: Name infix of every node a preview builds: ``<plane>_hzpv_<role>``.
    INFIX = "_hzpv_"
    #: Node types a preview builds around its shader node. Teardown walks the
    #: shader's connections and keeps only these -- the plane, the contact and
    #: the light are connected too and must survive -- rather than sweeping by
    #: name, which a duplicate leaf name in another hierarchy would defeat
    #: (the rig's ``_live_rig_nodes`` resolves by connection for the same
    #: reason).
    NODE_TYPES = (
        "file",
        "place2dTexture",
        "decomposeMatrix",
        "vectorProduct",
        "plusMinusAverage",
        "shadingEngine",
    )

    # ------------------------------------------------------------ availability
    @classmethod
    def device(cls) -> Optional[str]:
        """The live Viewport 2.0 device, or None headless.

        Batch is asked first: mayapy still answers ``ogs -deviceInformation``
        with a real adapter (measured: an Intel iGPU at OpenGL 4.6, Pixel 4),
        which would read as legacy OpenGL and send a headless caller to the
        preferences -- when there is simply no viewport to preview in.
        """
        try:
            if cmds.about(batch=True):
                return None
            return cls.classify_device(cmds.ogs(query=True, deviceInformation=True))
        except Exception:  # noqa: BLE001 -- no viewport at all is "no device"
            return None

    @classmethod
    def language(cls) -> Tuple[Optional[str], str]:
        """``(language, refusal)``: the shader language this session can
        compile, or None with the message that says why not."""
        device = cls.device()
        return cls.LANGUAGE_BY_DEVICE.get(device), cls.refusal(device)

    # ------------------------------------------------------------------- state
    @classmethod
    def shader_node(cls, plane) -> Optional[str]:
        """The plane's preview shader node, or None."""
        if not cmds.attributeQuery(cls.SHADER_ATTR, node=plane, exists=True):
            return None
        nodes = cmds.listConnections(f"{plane}.{cls.SHADER_ATTR}", source=True) or []
        return nodes[0] if nodes else None

    @classmethod
    def is_attached(cls, plane) -> bool:
        return cls.shader_node(plane) is not None

    @classmethod
    def attached_planes(cls) -> List[str]:
        """Every plane in the scene wearing a preview."""
        return sorted(
            {
                p.split(".")[0]
                for p in cmds.ls(f"*.{cls.SHADER_ATTR}", recursive=True) or []
                if cls.is_attached(p.split(".")[0])
            }
        )

    @classmethod
    def restore_snapshot(cls, plane) -> Dict[str, Optional[List[int]]]:
        """The real shading assignment a preview stands in for (``{}`` when
        none is attached). What the rig's accessors read while the plane's
        live membership is the preview's."""
        if not cmds.attributeQuery(cls.RESTORE_ATTR, node=plane, exists=True):
            return {}
        raw = cmds.getAttr(f"{plane}.{cls.RESTORE_ATTR}") or ""
        try:
            return json.loads(raw) if raw else {}
        except ValueError:
            return {}

    # ------------------------------------------------------------ attach/detach
    @classmethod
    def attach(cls, plane, *, language: Optional[str] = None) -> str:
        """Show the live preview on *plane* (a horizon rig's plane).

        Idempotent: an attached plane is re-attached, which rebinds a rebaked
        map. Returns the shader node.

        Raises:
            ValueError: *plane* is not a horizon plane, has no map, or the
                session's viewport cannot compile the effect.
        """
        from mayatk.rig_utils.shadow_rig import ShadowRig

        if ShadowRig.plane_type(plane) != "horizon":
            raise ValueError(f"{plane}: not a horizon rig plane.")
        png = ShadowRig._plane_horizon_path(plane)
        if not png or not os.path.exists(png):
            raise ValueError(f"{plane}: its horizon map is missing ({png!r}).")
        if language is None:
            language, refusal = cls.language()
            if language is None:
                raise ValueError(refusal)
        extension, plugin, node_type = cls.LANGUAGES[language]
        EnvUtils.load_plugin(plugin)

        if cls.is_attached(plane):
            cls.detach(plane)
        effect = cls._write_effect(os.path.dirname(png), language)
        snapshot = MatUtils.get_shading_assignments(plane)

        base = CoreUtils.leaf_name(plane)
        fx = cmds.shadingNode(node_type, asShader=True, name=f"{base}{cls.INFIX}fx")
        cmds.setAttr(f"{fx}.shader", effect, type="string")
        techniques = cmds.getAttr(f"{fx}.techniques") or []
        if not techniques:
            cmds.delete(fx)
            raise ValueError(
                f"{plane}: the {extension} effect did not compile on this device "
                f"(see the Script Editor)."
            )
        # Compile on the device BEFORE binding. DirectX parses the effect at
        # the `.shader` set; OpenGL parses it again at the first draw and that
        # second pass RESETS every uniform attribute to the effect's default
        # (measured on the previous map: a tile-width uniform read 128 after
        # binding and its default 256 after the first refresh, which addressed
        # the whole texture wrongly).
        cmds.refresh(force=True)
        try:
            cls._bind(plane, fx, png)
            # The swap: membership only. The real network is untouched and
            # the snapshot lets the rig's accessors keep reading it.
            sg = MatUtils.create_shading_group(fx, name=f"{base}{cls.INFIX}SG")
            cls._ensure_string_attr(plane, cls.RESTORE_ATTR, json.dumps(snapshot))
            if not cmds.attributeQuery(cls.SHADER_ATTR, node=plane, exists=True):
                cmds.addAttr(plane, ln=cls.SHADER_ATTR, at="message")
            cmds.connectAttr(f"{fx}.message", f"{plane}.{cls.SHADER_ATTR}", force=True)
            cmds.sets(plane, edit=True, forceElement=sg)
        except Exception:
            # Never leave half a preview behind: every node built so far
            # hangs off the shader, the plane gets its material and its
            # attributes back, and the error still reaches the caller.
            cls._teardown(plane, fx, snapshot)
            raise
        cls._register_export_preparer()
        cls.logger.info(f"{plane}: horizon preview on ({language}, {techniques[0]}).")
        return fx

    @classmethod
    def detach(cls, plane) -> bool:
        """Restore the plane's real material and delete the preview's nodes.
        Returns whether anything was attached."""
        fx = cls.shader_node(plane)
        snapshot = cls.restore_snapshot(plane)
        attached = fx is not None or bool(snapshot)
        cls._teardown(plane, fx, snapshot)
        if attached:
            cls.logger.info(f"{plane}: horizon preview off.")
        return attached

    @classmethod
    def _preview_nodes(cls, fx: str) -> List[str]:
        """The shader node and everything a preview built around it, found
        through its connections (see :attr:`NODE_TYPES`)."""
        nodes = {fx}
        for node in cmds.listConnections(fx, source=True, destination=True) or []:
            if cmds.nodeType(node) in cls.NODE_TYPES:
                nodes.add(node)
        # The file node's own placement node hangs one hop further out.
        for node in list(nodes):
            if cmds.nodeType(node) == "file":
                nodes.update(
                    cmds.listConnections(
                        node, source=True, destination=False, type="place2dTexture"
                    )
                    or []
                )
        return sorted(nodes)

    @classmethod
    def _teardown(cls, plane, fx: Optional[str], snapshot) -> None:
        """Restore the plane's real material and remove every preview node
        and attribute -- the one path both ``detach`` and a failed ``attach``
        take, so neither can leave a different kind of remainder."""
        if snapshot:
            MatUtils.apply_shading_assignments(plane, snapshot)
        if fx and cmds.objExists(fx):
            cmds.delete(cls._preview_nodes(fx))
        for attr in (cls.SHADER_ATTR, cls.RESTORE_ATTR):
            if cmds.attributeQuery(attr, node=plane, exists=True):
                cmds.deleteAttr(f"{plane}.{attr}")

    @classmethod
    def toggle(cls, planes: Sequence[str], on: bool) -> Tuple[List[str], List[str]]:
        """Attach (*on*) or detach the preview on *planes*; returns
        ``(done, failed)`` where *failed* carries ``"<plane>: <reason>"``."""
        done, failed = [], []
        for plane in planes:
            try:
                if on:
                    cls.attach(plane)
                else:
                    cls.detach(plane)
                done.append(plane)
            except Exception as error:  # noqa: BLE001 -- one plane never blocks the rest
                failed.append(f"{plane}: {error}")
        return done, failed

    @classmethod
    def detach_all(cls) -> List[str]:
        """Detach every preview in the scene; returns the planes it left."""
        planes = cls.attached_planes()
        for plane in planes:
            cls.detach(plane)
        return planes

    # ----------------------------------------------------------------- export
    @classmethod
    def prepare_for_export(cls) -> None:
        """The ``"shadow"`` export preparer: no preview reaches an FBX, and
        the metadata is republished after the real materials are back.

        Registered under the producer's own name so it replaces, and therefore
        must call, ``ShadowRig.refresh_export_metadata`` -- an unknown name
        would sort AFTER every known producer and detach only once the
        record had already been published with the preview attached.
        """
        from mayatk.rig_utils.shadow_rig import ShadowRig

        cls.detach_all()
        ShadowRig.refresh_export_metadata()

    @classmethod
    def _register_export_preparer(cls) -> None:
        from mayatk.env_utils.fbx_utils import FbxUtils

        FbxUtils.register_export_preparer("shadow", cls.prepare_for_export)

    # --------------------------------------------------------------- building
    @classmethod
    def _write_effect(cls, folder: str, language: str) -> str:
        """The effect file for *language* in *folder*, current with the SSoT.
        Rewritten only when its text differs, so an untouched file keeps its
        mtime and VP2 does not recompile every attached plane."""
        extension = cls.LANGUAGES[language][0]
        path = os.path.join(folder, cls.EFFECT_STEM + extension).replace("\\", "/")
        text = cls.effect_text(language)
        current = None
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as fh:
                current = fh.read()
        if current != text:
            os.makedirs(folder, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
        return path

    @classmethod
    def _write_texture(cls, png: str) -> str:
        """The map *png* promoted to 16 bits, beside it (:attr:`TEXTURE_SUFFIX`).
        Rewritten only when missing or older than the map, so an untouched
        file keeps its mtime and VP2 keeps its upload."""
        path = os.path.splitext(png)[0] + cls.TEXTURE_SUFFIX
        if not (
            os.path.exists(path) and os.path.getmtime(path) >= os.path.getmtime(png)
        ):
            image = ptk.ImgUtils.load_image(png).convert("RGBA")
            ptk.ImgUtils.save_image(image, path, bit_depth=16)
        return path

    @classmethod
    def _bind(cls, plane, fx: str, png: str) -> None:
        """Wire the effect's uniforms: the map through a Raw file node, the
        frame and source through DG nodes off the contact's and source's world
        matrices (live, no per-frame Python), the layout as constants."""
        from mayatk.rig_utils.shadow_rig import ShadowRig

        base = CoreUtils.leaf_name(plane)
        record = ShadowRig.export_record(plane)
        horizon = record.get("horizon") or {}
        contact = ShadowRig._plane_contact(plane)
        _, source = ShadowRig._rig_links(plane)
        if not (contact and cmds.objExists(contact)):
            raise ValueError(f"{plane}: its contact locator is gone.")

        # The map, promoted to 16 bits (TEXTURE_SUFFIX: the OpenGL path would
        # sRGB-decode the 8-bit file whatever is set here) and bound Raw: it is
        # data (cotangents and occupancy bits). texelFetch reads level 0
        # unfiltered, so no filtering state is needed on the file node.
        file_node, _ = MatUtils.create_file_node(
            cls._write_texture(png), name=f"{base}{cls.INFIX}map", color_space="Raw"
        )
        cmds.connectAttr(f"{file_node}.outColor", f"{fx}.gHorizonTex", force=True)

        # The frame: origin and three world axes off the contact's matrix.
        dm = cls._node("decomposeMatrix", f"{base}{cls.INFIX}contact_dm")
        cmds.connectAttr(f"{contact}.worldMatrix[0]", f"{dm}.inputMatrix")
        cmds.connectAttr(f"{dm}.outputTranslate", f"{fx}.gOrigin", force=True)
        axis_a = cls._axis(base, "axisA", contact, ShadowRig.HORIZON_FRAME[0])
        axis_b = cls._axis(base, "axisB", contact, ShadowRig.HORIZON_FRAME[1])
        cmds.connectAttr(f"{axis_a}.output", f"{fx}.gAxisA", force=True)
        cmds.connectAttr(f"{axis_b}.output", f"{fx}.gAxisB", force=True)
        # The frame's up is the contact's own +Y -- never a cross product of
        # A and B, whose sign follows the bearing sense (Maya's (X, Z) and
        # Blender's (X, Y) frames are mirror images of each other).
        up = cls._axis(base, "axisUp", contact, (0.0, 1.0, 0.0))
        cmds.connectAttr(f"{up}.output", f"{fx}.gAxisUp", force=True)

        # The ground plane's height along that up: (0, groundHeight, 0) minus
        # the origin, dotted with up. The map's intervals were baked as
        # elevations seen FROM that plane; the body projects each fragment
        # onto it, and the plane's own lift (GROUND_OFFSET) must not enter.
        pma = cls._node("plusMinusAverage", f"{base}{cls.INFIX}ground_pma")
        cmds.setAttr(f"{pma}.operation", 2)  # subtract
        cmds.setAttr(f"{pma}.input3D[0]", 0.0, 0.0, 0.0, type="double3")
        cmds.connectAttr(f"{plane}.groundHeight", f"{pma}.input3D[0].input3Dy")
        cmds.connectAttr(f"{dm}.outputTranslate", f"{pma}.input3D[1]")
        dot = cls._node("vectorProduct", f"{base}{cls.INFIX}ground_vp")
        cmds.setAttr(f"{dot}.operation", 1)  # dot product
        cmds.connectAttr(f"{pma}.output3D", f"{dot}.input1")
        cmds.connectAttr(f"{up}.output", f"{dot}.input2")
        cmds.connectAttr(f"{dot}.outputX", f"{fx}.gGround", force=True)

        # The source: a position, or the direction a directional light SHINES
        # (its world -Z) with w = 0 -- the reference's vocabulary.
        if source and cmds.objExists(source):
            if ShadowRig.source_is_directional(source):
                vp = cls._node("vectorProduct", f"{base}{cls.INFIX}source_vp")
                cmds.setAttr(f"{vp}.operation", 3)  # vector x matrix
                cmds.setAttr(f"{vp}.input1", 0.0, 0.0, -1.0, type="double3")
                cmds.setAttr(f"{vp}.normalizeOutput", 1)
                cmds.connectAttr(f"{source}.worldMatrix[0]", f"{vp}.matrix")
                cmds.connectAttr(f"{vp}.output", f"{fx}.gSource", force=True)
                cmds.setAttr(f"{fx}.gSourceW", 0.0)
            else:
                sdm = cls._node("decomposeMatrix", f"{base}{cls.INFIX}source_dm")
                cmds.connectAttr(f"{source}.worldMatrix[0]", f"{sdm}.inputMatrix")
                cmds.connectAttr(f"{sdm}.outputTranslate", f"{fx}.gSource", force=True)
                cmds.setAttr(f"{fx}.gSourceW", 1.0)
        # The source's size rides the plane's stamp LIVE (the panel's Softness
        # restamps it through Recalculate), in the record's split: a
        # positional source's diameter, a directional one's angle.
        stamped = cmds.attributeQuery("sourceSize", node=plane, exists=True)
        directional = bool(source) and ShadowRig.source_is_directional(source)
        diameter, angle = "gSourceDiameter", "gSourceAngle"
        live, fixed = (angle, diameter) if directional else (diameter, angle)
        if stamped:
            cmds.connectAttr(f"{plane}.sourceSize", f"{fx}.{live}", force=True)
        else:
            cmds.setAttr(f"{fx}.{live}", float(record.get("source_size", 0.0)))
        cmds.setAttr(f"{fx}.{fixed}", 0.0)

        # The layout, as the record carries it (DCC units: no unit scale).
        rect = horizon.get("rect") or [1.0, 1.0, 0.0, 0.0]
        bounds = horizon.get("bounds") or [-1.0, 1.0, -1.0, 1.0]
        constants = {
            "gSize": horizon.get("size", ptk.ShadowHorizon.DEFAULT_SIZE),
            "gSpans": horizon.get("spans", ptk.ShadowHorizon.DEFAULT_SPANS),
            "gLevels": horizon.get("levels", 0),
            "gBoundsA0": bounds[0],
            "gBoundsA1": bounds[1],
            "gBoundsB0": bounds[2],
            "gBoundsB1": bounds[3],
            "gHeightScale": horizon.get("height_scale", 1.0),
            "gRectSX": rect[0],
            "gRectSY": rect[1],
            "gRectOX": rect[2],
            "gRectOY": rect[3],
        }
        for name, value in constants.items():
            cmds.setAttr(f"{fx}.{name}", float(value))
        # Opacity carries the expression's fade; intensity the artist's dial.
        cmds.connectAttr(
            f"{plane}.{ShadowRig.OPACITY_ATTR}", f"{fx}.gOpacity", force=True
        )
        cmds.connectAttr(f"{plane}.shadowIntensity", f"{fx}.gIntensity", force=True)

    @staticmethod
    def _node(node_type: str, name: str) -> str:
        if cmds.objExists(name):
            cmds.delete(name)
        return cmds.createNode(node_type, name=name)

    @classmethod
    def _axis(cls, base: str, role: str, contact: str, local) -> str:
        """A normalised ``vectorProduct`` rotating the contact-local axis
        *local* into world space -- the rig's own ``_make_world_direction``
        idiom, for the frame's two horizontal axes."""
        vp = cls._node("vectorProduct", f"{base}{cls.INFIX}{role}_vp")
        cmds.setAttr(f"{vp}.operation", 3)  # vector x matrix
        cmds.setAttr(f"{vp}.input1", *[float(v) for v in local], type="double3")
        cmds.setAttr(f"{vp}.normalizeOutput", 1)
        cmds.connectAttr(f"{contact}.worldMatrix[0]", f"{vp}.matrix")
        return vp

    @staticmethod
    def _ensure_string_attr(node: str, name: str, value: str) -> None:
        if not cmds.attributeQuery(name, node=node, exists=True):
            cmds.addAttr(node, ln=name, dt="string")
        cmds.setAttr(f"{node}.{name}", value, type="string")
